---
title: "Conferences"
---

# Conference Programme

We plan to showcase the CAMIS project at a number of conferences throughout 2023 and 2024. See below the list of conferences the CAMIS team will be at and please come say hello to us !

+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| Conference                                                                       | 2023/2024 Planning dates                       | 2023 Date & Location                             | 2023 Main Contact (also attending)                               |                    | Details                                                                           |
+==================================================================================+================================================+==================================================+==================================================================+====================+===================================================================================+
| JSM                                                                              | Abstract Feb 2024                              |                                                  | Leon Shih                                                        |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PHUSE US Connect                                                                 | TBC for 2024                                   | 5-8 March 2023 Orlando, Florida                  | Soma Sekhar                                                      |                    | Presentation                                                                      |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| DISS (Duke industry statistics symposium)                                        | TBC for 2024                                   | 29-31st March 2023 Virtual                       | Molly MacDiarmid                                                 |                    | Poster                                                                            |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PSDM(Pharmaceutical statistics and data management)                              |                                                | 19 Apr 2023 Netherlands                          |                                                                  |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| IASCT (ConSPIC - conference for statistics and programming in clinical research) | Abstract submission 14 Mar-3rd Apr             | 4-6 May 2023 Bengaluru, India                    | Harshal Khanolkar                                                | Harshal Khanolkar  | Talk. and/or poster                                                               |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| Society of Clinical Trials (SCT                                                  |                                                | 21-24 May 2023                                   | Michael Kane                                                     |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PSI 2023 Conference                                                              | Talk submission Nov.                           | 11-14 June 2023 Hammersmith London West, England | Martin Brown                                                     | Christina Fillmore | Oral & poster submission completed                                                |
|                                                                                  |                                                |                                                  |                                                                  |                    |                                                                                   |
|                                                                                  | Poster submission Feb.                         |                                                  |                                                                  | Lyn Taylor         |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  |                    |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  | Molly Macdiarmid   |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  |                    |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  | Martin Brown       |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  |                    |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  | Aiming Yang        |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| DIA 2023 Global Annual Meeting                                                   |                                                | 25-29 June 2023 Boston MA, USA                   |                                                                  |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| Joint statistical meeting (JSM)                                                  | Feb 2024 submission for next year              | 5-10 Aug 2023 Toronto, Ontario, Canada           |                                                                  |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| ISCB Conference                                                                  |                                                | 27-31 Aug 2023 Milan-Italy                       |                                                                  |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| RSS conference                                                                   | Abstract by 6th April                          | 4-7 sept 2023 Harrogate, England                 | Lyn Taylor                                                       |                    | Poster/talk TBC?                                                                  |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PHUSE CSS                                                                        | 15th June Abstract open, register by 30th june | Sept 18-20, Maryland USA                         | Soma Sekhar                                                      | Vikash Jain        |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  |                    |                                                                                   |
|                                                                                  |                                                |                                                  |                                                                  | Aditee Dani        |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| ASA Bio pharmaceutical Section Regulatory-industry Statistics Workshop           |                                                | 27-29 Sept 2023 Rockville, Maryland, USA         |                                                                  |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| EASD 2023 - European Association for study of diabetes                           |                                                | 02-06 Oct 2023 Hamberg Germany                   |                                                                  |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| SESUG (South East SAS user group)                                                |                                                | 17-19 Oct 2023                                   | Brian Varney                                                     |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PHUSE EU Connect 2023                                                            |                                                | 5-8 November 2023 ICC Birmingham, England        | Christina Fillmore                                               |                    | Abstract for talk not accepted.                                                   |
|                                                                                  |                                                |                                                  |                                                                  |                    |                                                                                   |
|                                                                                  |                                                |                                                  | Jayashree vendanayagam                                           |                    | @jayashree - do you have a poster?                                                |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| R in Pharma \                                                                    |                                                | Nov Virtual                                      | Brian Varney/ Christina Fillmore?                                |                    | R Validation Hub team will include a slide for us. (Juliane Manitz/Doug Kelkhoff) |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| POSIT conf.                                                                      | Invite only                                    | September - Chicago                              | TBC if anyone has any contact going that could help advertise us |                    |                                                                                   |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PHUSE (Single day events) SDEs                                                   |                                                | Toronto Mississauga?                             | ?                                                                |                    | ?                                                                                 |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
| PHUSE (Single day events) SDEs                                                   |                                                | New York (Oct 16th)                              | Aiming Yang                                                      |                    | Emailed host to have poster/ talk/ advert                                         |
+----------------------------------------------------------------------------------+------------------------------------------------+--------------------------------------------------+------------------------------------------------------------------+--------------------+-----------------------------------------------------------------------------------+
