---
title: "Contributions"
---

### Request for Contributions

Although this project does have a core team, the endeavor of tracking all these comparisons will fail without community contributions. We welcome a wide verity of contributions from correcting small typos all the way to full write-ups comparing software (languages) for a method.

Please contribute by submitting a pull request to and our team will review it. If you are adding a page please follow one of our templates:

-   [R template](https://github.com/PSIAIMS/CAMIS/blob/main/templates/R_template.qmd)

**Instructions for Contributions to** [**the CAMIS repository**](https://github.com/PSIAIMS/CAMIS)

1.  Set up RStudio to clone the CAMIS github repo -- See this [guidance for more detail](https://github.com/PSIAIMS/CAMIS/blob/main/minutes/posts/13Feb2023_Contributing%20to%20the%20CAMIS%20project_Setting%20up%20communication%20between%20github%20and%20R%20studio.docx)

2.  If this is your first contribution, contact [christina.e.fillmore\@gsk.com](mailto:christina.e.fillmore@gsk.com) and give her your github username, requesting to access the CAMIS repo for contributions

3.  Go into RStudio and Create a branch --Within RStudio click the branch button (on the git tab top right). Within the box that comes up ensure you are on the "remote=origin" and "Sync branch with remote" is checked. You can name the branch something to do with the amends you intend to make.

4.  Edit and /or add files within the CAMIS directories. If you are adding SAS guidance store under sas folder, R guidance store under r folder, for "SAS vs R" comparison store under comp. Follow the naming convention of the files already stored in those folders.

5.  Within R studio - Commit each change or new file added, and push to the repo from within R studio.

6.  Go into github and do a pull request to sync your branch back to the origin. See [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for more detail. Note that your change will need a reviewer, so please add *DrLynTaylor* and *statasaurus* as reviewers.

7.  Once your change is approved, and merged into the origin, the branch will be deleted and you will need to create a new branch to add further contributions. NOTE: you can make the new branch called the same as the old one if you wish but ensure you select to overwrite the previous one.
