---
title: "Confidence Intervals Poisson Exposure Adjusted Incidence Rates (EAIR)"
bibliography: references.bib
csl: nature.csl 
---

# Introduction

A unified family of methods covering the single rate and all contrasts for independent Poisson rates was described by Laud[@laud2017], with the addition of a bias correction for the OR case[@laud2018].

Adverse events (AEs) are often collected on clinical trials. AEs can be summarized using number of subjects experiencing the event (n) and percentage of events calculated out of total subjects who received the drug. However, if the average duration of exposure differs significantly between treatment groups within a trial or between trials included in an analysis, due to drop-out rates or study design, such incidence of AEs will need some adjustment to make the comparison meaningful.

The exposure adjusted event rate (EAER) or exposure adjusted incidence rate (EAIR) may be calculated to perform this adjustment, where the denominator for the calculation is the exposure duration expressed in person-time such as person-year or patient-year.

Suppose we have two treatments (A and B), we want to calculate the difference in EAIR (risk difference) along with a 95% Confidence interval. Because we have count data, our CI derivation is based on the poisson distribution. One appropriate method to use to derive the EAIR CI, is the Miettinen Nurminen method for risk differences.

# Summary

This page is a placeholder whilst further content is being developed.

SAS does not have any available procedure to derive the CI's using Miettinen Nurminen method for risk differences (following poisson distribution). However, there is a SAS macro developed by Pete Laud. For more information see [here](https://github.com/PeteLaud/ratesci-sas/blob/main/scoreci.sas)

```         
NOTE that: skew = FALSE indicates no skewness correction which gives us the miettinen-nurminen method 

eair <- scoreci( x1 = nn1, #events treatment 1
                 n1 = ex1, #exposure treatment 1
                 x2 = nn2, #events treatment2 (reference)
                 n2 = ex2, #exposure treatment 2 (reference)
                 distrib = "poi", #poisson 
                 contrast = "RD", #risk difference
                 level = 0.95, #alpha for CI (95%CI)
                 skew = FALSE, #MN method )|>
              as_tibble()
```

NOTE: depending on your computer environment the macro may use different floating point rounding and as such, rows 449 and 450 of the macro may need updating from using 1E-15 (15 decimals) to be 1E-9 (9 decimals).

```         
%else %if "&distrib." = "poi" %then %do;

  D1t = round(tan(pi * max((-1 + 1E-15), min(D1, (1 - 1E-15))) / 2), &converge./100);
  D2t = round(tan(pi * max((-1 + 1E-15), min(D2, (1 - 1E-15))) / 2), &converge./100);
  
%end;
 
```

# References
