---
title: "Competing Risks Analysis Using SAS"
---

# Name of Method

## Available SAS procedures for competing risks analysis

**Optional** If there is only one available package this can be deleted. Otherwise please make a short list, paragraph or table. If there is a reason to use one package vs another please include it. Please make sure to include what version of the packages you are using

## Data used

The bone marrow transplant (BTM) dataset as presented by Guo & So (2018) is used. The dataset has the following variables:

-   `Group` have three levels, indicating three disease groups.

-   `T` is the disease-free survival time in days.

-   `Status` has value 0 if `T` is censored; 1 if `T` is time to relapse; 2 if `T` is time to death.

-   `WaitTime` is the waiting time to transplant in days, used as a covariate in Guo & So (2018).

-   For illustrating, an additional categorical variable `waitcat` is defined as a stratification factor.

```{r message=FALSE, warning=FALSE}
require(dplyr, quietly = TRUE)
bmt <- read.delim("../data/bmt.txt") %>%
  mutate(waitcat = as.numeric(WaitTime > 500),
         DGroup = ifelse(Group == 1, 'ALL',
                         ifelse(Group == 2, 'AML-Low Risk',
                                'AML-High Risk')))
head(bmt)
```

## Example Code

### Example using {package name}

**Optional** if there is more than one package

## Comparison

If you are comparing more than one package or between different languages, consider adding in a table to illustrate some of the differences. When comparing between languages it can be nice to have a table with links to the pages with deeper dive of each language for a given method method like this table from the ANCOVA page:

| Analysis                                      | Supported in R          | Supported in SAS          | Results Match | Notes                                                                                    |
|---------------|---------------|---------------|---------------|---------------|
| ANCOVA using general linear model and lsmeans | [Yes](../R/ancova.html) | [Yes](../SAS/ancova.html) | [Yes](#comp)  | `GLM()` function from **sasLM** with `EMEANS=TRUE` is the easiest to use and matches SAS |

But, even if you are just comparing the difference in same language it can be helpful to have a table with values of interest across different packages. Using dynamic content you can add the values to a table without manually putting in each value

## Conclusion

**Optional** add a conclusion

## Reference

Guo C and So Y. (2018). "Cause-specific analysis of competing risks using the PHREG procedure." In Proceedings of the SAS Global Forum 2018 Conference. Cary, NC: SAS Institute Inc. https://support.sas.com/resources/papers/proceedings18/2159-2018.pdf.
