---
title: "A comparison of MMRM methodology in SAS and R software"
---

**NOTE: This project is no longer available for selection.**

**Abstract:**

The mixed model for repeated measures (MMRM) is commonly used in individual clinical trials due to its suitability to model longitudinal continuous data outcomes measured at set timepoints over time. However, there is much complexity in this methodology such that replication of analysis methods and results produced in SAS vs open source software such as R may not be straight forward.

The primary objective of this project is to build on the information already documented here [CAMIS - A PHUSE DVOST Working Group (psiaims.github.io)](https://psiaims.github.io/CAMIS/) under Repeated Measures (Linear Mixed Model (MMRM) section) and provide both PAREXEL and the wider pharmaceutical industry with a comprehensive guide for how to implement and replicate MMRMs analysis methods in SAS and R.

It is expected that the project will consist of performing a thorough comparison of MMRM analysis methods in SAS (using Proc Mixed and Proc GLIMMIX) versus in R (nlme::gls, lme4::lmer, and glmmTMB::glmmTMB and mmrm::mmrm). The project will discuss and document the options available in each, detailing similarities and differences in default options, available options and analysis results.

The project plan for this study is expected to consist of

1 Self teaching in the MMRM methodology to understand how to apply the methods, the common options available when model fitting, their strengths and limitations in clinical research

2 Literature search to investigate

a.  Latest advance in current methods and guidance

b.  R packages available for use to apply these methods

c.  SAS procedures available to apply these methods

d.  Any current research or evidence of researchers comparing methods in SAS vs R.

3 Using one or more datasets (simulated or existing in open source, testing both small and large datasets), fit a selection of MMRM modelling methods using various software/package and options to see if SAS and R return the same results. Investigate and document the reasons for any differences. 

Possible extensions (if time permits):

a.  Investigate Categorical MMRMs

b.  Investigate the Bayesian MMRM options available in both software and document any differences.

c.  Investigate pythons application of such methods with comparison to SAS and R
