---
  title: "Confidence intervals for Proportions: General Information"
  bibliography: references.bib
  csl: nature.csl 
---

## Introduction

The methods to use for calculating confidence intervals (CI) for binomial proportions depend on the situation:

-   1 sample proportion, p (1 proportion calculated from 1 group of subjects)

-   2 sample proportions (\$p_1\$ and $p_2$) and you want a CI for a contrast parameter, such as the difference in the 2 proportions (risk difference, $RD = p_1 - p_2$), the ratio (relative risk, $RR = p_1 / p_2$), or the odds ratio ($OR = p_1 (1-p_2) / (p_2 (1-p_1))$).

    -   If the 2 samples come from 2 independent samples (different subjects in each of the 2 treatment groups)

    -   If the 2 samples are matched (i.e. the same subject has 2 results, one from each treatment \[paired data\]).

The production of a confidence interval for such contrasts is useful for giving a clinically interpretable estimate of the magnitude of a treatment effect. Moreover, it is particularly relevant for non-inferiority (NI) or equivalence trials, where the hypothesis test is an assessment of whether the confidence interval spans a pre-specified NI margin or not.

Some sources suggest selecting a different method depending on your sample size and whether your proportion is close to 0 or 1 (rather than near to the 0.5 midpoint). Similarly, for a 2x2 table, there is a widely-held belief that an 'exact' method should be used if expected cell counts are less than 5. These conventions originated at a time when the Wald method was the only available alternative. However, options are now available for CI methods that have appropriate coverage properties across the whole parameter space, which with modern computing software are easily obtained, so there is no need for such a data-driven approach to method selection or reliance on overly conservative methods.

The poor performance of the Wald method is well documented - it can fail to achieve the nominal confidence level even with large sample sizes, and there is a consensus in the literature that it should be avoided[@brown2001, p128]. Inexplicably, it remains a default output component in SAS, so continues to be widely used, but alternative methods are strongly recommended. \[Note in particular that most other methods become conservative for very small cell counts, which suggests there is no need to resort to 'exact' methods.\]

### Strictly conservative vs proximate coverage

Because of the discrete nature of binomial data, it is impossible for any CI method to cover the true value of the estimated proportion precisely 95% of the time for all values of p. CI methods may be designed to achieve the nominal confidence level **as a minimum**, but many researchers find such a criterion to be excessive, producing CIs that are unnecessarily wide. The alternative position is to aim for coverage probability that is close to the nominal confidence level **on average.** These two opposing positions are described as "aiming to align either the minimum or the mean coverage with the nominal $(1-\alpha)$"[@newcombe2012], or in other words aiming for coverage to be either "strictly conservative" or "proximate"[@laud2017]. \[It has been pointed out that the proximate stance is consistent with most other types of statistical models, based on approximate assumptions[@brown2001].\] Many alternative CI methods are designed to meet the latter criterion, but some employ computationally intensive approaches (often labelled as 'exact' methods) to guarantee the former, or include an optional adjustment ("continuity correction") to emulate the same effect using asymptotic formulae. The term "continuity correction" may be more reasonably termed a "continuity adjustment"[@newcombe1998c][@campbell2007].

It is worth noting that although one might assume that regulatory authorities would take the latter stance and insist on strictly conservative coverage (noting that one-sided non-coverage equates to the type 1 error of a NI test), in recent years it appears that the FDA's preferred method for RD is the Miettinen-Nurminen (MN) method (e.g. see <https://www.accessdata.fda.gov/drugsatfda_docs/nda/2010/200327orig1s000statr.pdf>). In contrast, for a single proportion, the 'exact' Clopper-Pearson method seems (anecdotally) to be more commonly preferred.

### Consistency with hypothesis tests, and one-sided coverage

Depending on the analysis plan, it may be desirable for a reported confidence interval to be consistent with the result of a hypothesis test, so that for example the 95% CI will exclude the null hypothesis value if and only if the test p-value is less than 0.05 (or 0.025 one-sided). This includes the special case of a superiority test (where the null hypothesis is of 0 difference between the groups), but also the more general case of a non-zero null hypothesis for NI or equivalence testing. It should be noted that not all CI methods satisfy this criterion.

A related issue is whether it is sufficient for two-sided coverage probability to be aligned with the nominal $(1-\alpha)$, or whether the tail probabilities (i.e. one-sided non-coverage at each end) should also be aligned with the nominal $\alpha/2$. Clearly the latter criterion (described as 'central interval location' by Newcombe) is essential for non-inferiority testing, but it is also a desirable property for any confidence interval.

# Overarching methods

There are some methods that apply (or have variants which apply) across all contrast parameters (i.e. $\theta=p$ or $\theta=RD$ etc.), which are outlined below.

### Normal Approximation Methods (Also known as the Wald Method)

The Wald confidence interval is constructed simply from the the point estimate plus and minus a multiple of its estimated standard error: $(L_{Wald}, U_{Wald}) = \hat \theta \pm z_{\alpha/2} \sqrt{\hat V(\hat\theta)}$ where $z_{\alpha/2}$ is the $1-\alpha/2$ quantile of a standard normal distribution corresponding to the confidence level $(1-\alpha)$.

For RR and OR, $\theta$ is log-transformed to improve the normal approximation, and $(L_{Wald}, U_{Wald}) = exp[ ln(\hat \theta) \pm z_{\alpha/2} \sqrt{\hat V(ln(\hat\theta))}]$, which requires a modification for boundary cases.

### Asymptotic Score Methods

The Score confidence interval is also based on an asymptotic normal approximation, but uses a score statistic $Z(\theta) = S(\theta)/\sqrt {\tilde V}$ based on contrast function $S(\theta)$ and its true variance $\tilde V = V(S(\theta))$. For example, for the single proportion, $S(p) = \hat p - p$, or for RD, $S(\theta) = \hat p_1 - \hat p_2 - \theta$.

$Z(\theta)$ can be evaluated at any value of $\theta$ to find the range of values for which $|Z(\theta)|< z_{\alpha/2}$. For the single proportion (Wilson score interval), this process simplifies to solving a quadratic equation in $p$.

For the contrast parameters, score methods were derived for independent proportions by Miettinen & Nurminen and others in the 1980s[@miettinen1985][@Mee1984][@koopman1984], and related methods for paired data followed later[@tango1998][@tango1999][@nam2002][@tang2003]. In each case, the variance is a function of both $p_1$ and $p_2$, or of $\theta$ and a 'nuisance parameter', which is eliminated using the maximum likelihood estimate for $p_2$ (or for the paired case, the cell probability $p_{21}$) for the given value of $\theta$.

### SCAS Methods

Originating from papers published in 1985-1990 by Gart and Nam, the skewness-corrected asymptotic score ('SCAS') methods introduce a further term within the score statistic that involves $\tilde \mu$, the third central moment of $S(\theta)$:

$$
Z(\theta) = \frac{S(\theta)}{\sqrt {\tilde V}} - \frac{(Z(\theta)^2 - 1)\tilde \mu_3}{6 \tilde V^{3/2}}
$$

Hence these are an extension of the asymptotic score intervals, designed to address asymmetric coverage which was observed for the score method, particularly for the RR contrast. The same principle is applied to the Wilson score interval for a single proportion, which has also been noted to have a systematic bias in one-sided coverage. A unified family of methods covering the single proportion and all independent contrasts was described by Laud[@laud2017], with the addition of a bias correction for the OR case[@laud2018], amd a further publication currently under review for paired data.

\[SCAS intervals are not yet implemented in SAS PROC freq, but can be obtained using the %SCORECI and %PAIRBINCI macros.\]

### MOVER Methods

This class of methods was popularised by Newcombe for the RD contrast, and is therefore labelled as the Newcombe method in current SAS PROC FREQ documentation. It has since been generalised to other contrasts and for paired data (though not implemented in SAS), and renamed as the Method of Variance Estimates Recovery (MOVER). It is also referred to as the 'Square-and-add' approach.

MOVER intervals are produced by combining CIs for each of the two separate proportions involved (and an estimate of their correlation, in the paired data case). Originally Wilson intervals were used (hence earlier versions of SAS labelled the method as WILSON), but improved performance may be obtained by using Jeffreys intervals instead.

### 'Exact' Methods

So-called 'exact' methods are designed to guarantee strictly conservative coverage. (Newcombe points out some problems with the use of the term 'exact' here, hence the quotation marks.) For the single proportion, the Clopper-Pearson confidence interval is the range of p for which $P(X \ge x | p) = \alpha / 2$ and $P(X \le x | p) = \alpha / 2$. More complex calculations are involved for the contrast parameters, which eliminate the nuisance parameter by taking the supremum of all p-values across the range of combinations of $p_1$ and $p_2$ for a given $\theta$.

There are actually a few different versions of 'exact' methods for each contrast, with alternatives aimed at reducing the conservatism of coverage. For example, Chan-Zhang is an improvement on Santner-Snell. However, it should be noted that some methods (e.g. Blaker, Agresti-Min) achieve reduced conservatism by inverting a two-sided exact test, but as a result they do not satisfy the strictly conservative criterion for one-sided coverage (and therefore would produce inflated type 1 error rates if used for a non-inferiority test).

Several asymptotic methods offer a continuity adjustment, which aims to emulate 'exact' methods and achieve almost conservative coverage, by for example adding a quantity of the order $0.5 \times n$ to the formula. Generally this is not a successful modification to the Wald method, but can produce good results for the score methods. It has been suggested that an adjustment of smaller magnitude such as $0.25 \times n$ (or any other selected value on a 'sliding scale' from 0 to 0.5) could be used for almost-but-not-quite-strictly conservative coverage. (Note that such an adjustment is also possible for methods based on Jeffreys intervals, such as MOVER.)

### 'Mid-P' Methods

Exact methods may be adapted to be less conservative (i.e. to achieve proximate coverage) by applying a mid-P adjustment, essentially including half the probability of the observed data in the calculations. This is like a reversal of the continuity adjustment for asymptotic methods.

Although theoretically possible for any contrast, the mid-P method is only implemented in SAS for CIs for the single proportion and the odds ratio contrast.
