---
title: "Content updates"
date: "08 Sep 2025"
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false
attend_list <- readr::read_csv("../CAMIS team members 2025")
knitr::kable(
       list(attend_list[c(1,9)]), "html")
```

# Agenda & Minutes

**New Content This Month**

-   Recurrent events page: Sarah/Yannick <https://psiaims.github.io/CAMIS/Comp/r-sas_recurrent_events.html> - R, SAS & R vs SAS recurrent events pages are present.

-   Wilcoxon rank sum test: Yannick [CAMIS - A PHUSE DVOST Working Group](https://psiaims.github.io/CAMIS/) - added asht:wmwTest() function available which wasn't in the other packages that do WRS.

-   Propensity score matching R page:  Chi  <https://psiaims.github.io/CAMIS/R/causal_ps_matching.html>

-   ANOVA, ANCOVA:  Christina [ANOVA](https://psiaims.github.io/CAMIS/R/anova.html)

-   Tidied up Help pages\

**Standards:**  use the package::function approach when writing up your pages

**Conferences:**

-   Brian presenting at SESUG: September 22-24 2025 on SAS Campus in Cary, NC

-   Chi asked if we are doing any main session at R/pharma this year. There is the diversity hackathon again - reach out to christina if interested, but so far not aware of any CAMIS main session at R/pharma.

**AOB:**

Phil Bowsher: reached out to our group to see if we could investgiate operating system descrepancies, when doing comparisons SAS to R. Eg. the difference is not just in the underlying algorithms, but differences in operating system (R on linux on a server vs SAS on a PC windows or even language engines (SAS vs Altair for example). Could CAMIS add this sort of comparison to the repo?  

-   Perhaps have another section in CAMIS in main table (or another page if lots of content).

-   When submitted to Cran, it is run in different OS (to check it runs), but we dont think any checks are done to check you get the same results. (but we think SAS does do this).

-   Would be interesting to see example, and see size of any difference. Are they always tiny and inconsequential?

-   Could allocate to students to investigate....?  LT:  project for Sheffield Hallam University ?

-   How would we do this when each person only has 1 operating system ! -  simple table of results & code, then email out & ask everyone to run it & confirm code or new result

-   To discuss further at leadership meeting & then come up with a plan
