---
title: "FDA quartely meeting, 1st survey feedback - general updates"
date: "09 Oct 2023"
categories:
  - 2023
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2023_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 12)]),
  "html"
)
```

# Agenda

**Welcome New Members:** Vikrant Vijay FDA, Ismael Rodriguez (Appsilon)

**PHUSE SDE: Missisauga:** June 8th feedback: Jayashreee

**CAMIS-ONCO update:** Soma Sekhar / Vikash Jain

PHUSE US Connect 2024 planning (Poster accepted, will find out re: workshop oct 20th)

White paper planning

**FDA meeting update** **/survey results**.: presented to around 15 FDA representatives, but didn't get any questions/ comments on the call. However, follow the meeting, our slides were passed to others at the FDA and Vikrant Vijay got in touch to join the group. He's not available today, but will attend in future.

Questionnaire only got 16 responses, 9/16 had heard of CAMIS, 13/16 used R for GXP, 4/15 used python for GXP, 1/16 used Julia for GXP. 9/16 had experienced discrepancies whilst trying to replicate analysis between languages.

**ACTION**: To re-run maybe just before CSS 2024 / or each year to assess progress and use for conference presentations.

Common programming challenges

-   Whilst executing Analysis in R, I come across challenge in Numerical Differences in Statistical results. Would it be great if Industry & regulatory work together to build Standard R package for Statistical Methods & details in CAMIS repository would be highly appreciated.

-   Ensuring reproducible environments and having people accept that different results for different implementations of an algorithm should perhaps be interpreted as a hint towards the accuracy, rather than one of the methods being wrong.

-   Standard deviation initially did not match between and SAS. Later resolved by using the type option

-   Challenges to figure out array of methods to replicate the same results across different software platforms/ Finding why resutls differ / unclear documentation/ discrepancy in values

-   LS means contrasts from GLMs or MMRMs between SAS and R (vis lme4/mmrm + emmeans)

-   Parsing issues, scalability issues and network crash.

-   Implementation of median seem to differ between R and SAS.... Sometimes joins in dplyr can also behave differently than i would expect with raw SQL

-   Different methodologies (e.g for sample size calculation0 and lack of non-standard methods in SAS (e.g sample size for adaptive design).

**Social Media update** : Harshal\
Newsletter, (quarterly, or monthly) to advertise progress (ie. content we created) & conferences we are attending. Can we advertize ourself more to EMA, PMDA etc.. Can send to Frank Petavy (methodological working party). ACTION: Harshal/Lyn put togther summary for newsletter & send to Wilmar to reach out to Frank & others. Lyn to email David to see if any wider participation.

https://www.ema.europa.eu/en/committees/working-parties-other-groups/chmp/methodology-working-party

**Website** Christina/ Chi / Jayashree

-   All pull requests accepted & everything up to date

-   MMRM update - No update. ACTION: Chi Zhang: will follow up to see if we can get someone to add in MMRM package to our existing content.

-   github training plan (R/Pharma workshop & PSI training course) - ongoing prep for workshop & course through PSI AIMS team.

-   Agnieszka (PAREXEL) and Chi -- working on Wilcoxon test content for paired & unpaired data.

-   ACTION: Chi & Christina to talk about local rendering & renv issue with not having the packages to be able to render... once we know a fix, can write up and put on the website.

**Upcoming conference planning**

-   PHUSE SDE New York: Oct 16th : Aiming

-   PHUSE US Connect: Soma/Vikash

-   R/Pharma -- Christina?

-   SESUG (South East SAS user group) late october 2023, Brian will present on CAMIS.

-   North Carolina - SDE if anyone wants to volunteer to attend let us know.

**AOB** - None.
