---
title: "New Website Discussion"
date: "23Jan2023"
categories:
  - 2023
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2023_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 3)]),
  "html"
)
```

# Meeting minutes

## Christina provided a summary of work to date on the website

Repo now live: $$https://psiaims.github.io/CAMIS/$$

Primary mode of navigation will be the table of contents..

Comprehensive Search function is available to supplement the use of the TOC.

The website is build from 3 folders in github:\
R SAS Comp

These folders, map to the columns of the table, I.e. everything about R is in Quarto files under R.

Comp folder: for the Comparison -- name sure you name the two software you are using r-sas - so we can use this when dynamically selecting.

In future we can add Python / Julia directories.

The idea would be for people to use the: $$CAMIS/templates/R_template.qmd$$ - A template of how to write documentation for the R part of the site. They'd Edit template & save it back into the R folder naming it clearly for what it is. Template should also contain name packages being used at start of each method comparison. It'd be difficult to be exhaustive with all the survival analysis packages i.e. accelerated failure time packages, etc.., but as long as stated hopefully can grow over time.

The Data-info folder -- contains description of all data being used for the comparisons. Going forward if different data used, the information about the data would be put into this folder. This allows the data description to sit outside of the comparison folders & where possible same data be used across comparisons.

### Questions & Discussion

Joe & Michael raised that the About tab which has information about the project is out of date, so should be updated. We also have no detail on the driving mechanism... I.e. what we would like from collaborators. Add "How to collaborate" button.

Items to be discussed further which may need to be included in the site:

1.  update Methods: needs to make it more robust to future uploads - i.e. topics within linear models? (Sub categories) focus on methods, but how sort the methods for inclusion of all in future

2.  Rating the software discrepancies. I..e How severe the difference is?

3.  Need to create a template for comparisons. Discuss if we would have a purpose/highlight of comparison/ summary/conclusions at the top first. Also if we put List of R packages this comparison uses (use Tags?) - Need to consider if package superseeded/ multiple packages whether they go in 1 document or multiple.

4.  How to expand to sort by: therapeutic area relevance (would be good to link from methods to Oncology somehow

5.  What if a different package.., does same analysis... have to make it clear which package is being used & include multiple packages. It was agreed that as long as we are clear on what we have compared then Its ok to not be all inclusive. That can be added by other collaborators later. It was noted by Kyle that for survival (I.e. accelerated failure time packages), it may be hard to include all. The recommendation is to start with 1 and can expand further as it grows. We may have to re-think website design as it grows to accommodate. Hence why we want everything written in smaller parts to can easily manipulate going forward.

## Min-Hua provided an update on the white paper:

In its final stages of review by team, and will now be sent for wider review.

# Summary of actions: Due early march.

### Lyn: review/update the "About" tab on website to ensure it's accuracy.

Show who it's sponsored by / who the group are that are supporting it and ensure that it's legally ok: PHUSE, PSI and ASA -- Trancelerate?

### Christina: Add "How to collaborate" tab & info.

### Convert the CSRMLW content into the new format CAMIS site.

Do let Lyn know if you need help, advice and we can also ask for other volunteers to assist:

### Mia Qi/ Min-Hua Jen: Survival

### Brian Varney: Linear models

### Ben Arancibia: Mixed models: -- NOTE: new MMRM package to also be added if possible.

### Aiming Yang: CMH: -- set up a separate meeting with Lyn/Christina to discuss how.

### All: Continue to document any differences you find ready to load to new website. Follow R template so we can get them loaded as soon as we have the website ready

### Soma Sekhar: Consider starting to set up CAMIS-ONCO group to focus on Oncology analyses differences

# Next meeting: 13th Feb 2023: 4:30 UTC, 11:30 EST.