---
title: "Lessons learnt- Novartis Hackathon, Diversity Alliance, OSTCDA"
date: "9 Sept 2024"
categories:
  - 2024
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2024_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 10)]),
  "html"
)
```

# Agenda & Minutes

### Novartis Hackathon

Orla presented back to the group on Novartis's Open-Source in Action: Hackathon. Key points were:

-   Aim: to encourage more people to be confident to work in open source and break down barriers in their contributing (such as through git training). To give people exposure to open-source resources that are applicable to their daily work as well as building their network with external experts.

-   How: Novartis open-source enablement team will hold hackathons on a regular basis selecting topics that have the potential to impact day-to-day work. External experts to guide Novartis employees on key initiatives and packages. This time CAMIS was selected with Christina providing support.

-   When: Prep session 16th July 2024, Intro to git training 17th July, then 2 weeks of hackathon w/c 22nd July and 29th July with support during daily office hours.

-   Who: 158 signed up from Advanced quantitative science (AQS), 100+ attended git training, 25+ submitted contributions. 8 SAS, 7 R, 1 Python, 3 SAS vs R and 1 template

-   Feedback: Awards for First PR (Quick draw), most closed PRs (Busy bees), Most complex methodology (trailblazing) and Above and beyond (thinking beyond the methods).

-   Learnings:

    -   Timing: aligned to 'summer rejuvenation' period where Novartis get 2 weeks to catch up with reduced meeting loads

    -   Training: git and renv were a steep learning curve for newcomers, but daily office hours and teams channels helped. Little direction was needed to write content in quarto.

    -   CAMIS: the natural structure of CAMIS minimized prep work as the gaps in the table show what content is missing. It provided a nice culture to work in, focusing on good quality content over perfection. It was inclusive as it's a multi-language project so could include people who only work in SAS or in R.

    -   CAMIS repo cloning often hangs if network is busy. Suggestion to reduce size of repo by removing the powerpoint presentations which would improve cloning.

### Content update

-   Suggest to add page on how to run/ conduct a hackathon for CAMIS

-   Only 4 current open pull requests which all require changes by author so we are up to date

-   We still have a lot of open issues, but are making progress. Aim to get issues to 1 page by End of year

### Diversity Alliance Hackathon

The R in Pharma diversity alliance aspire to be an inclusive R community for developers who wok in the pharma space. Their goal is to provide a welcoming, equitable and supportive space for people to upskill, share knowledge and build a community of diverse voices.

They are holding an upcoming hackathon as part of the R in Pharma conference, where anyone who considers themselves as under-represented in the R in Pharma space, can participate. The event requires volunteers experienced in open source collaboration to lead attendees in small groups helping them to contribute open source collaborations. If you would like more information, to volunteer or attend, please contact Christina @statasaurus

See [here](https://opensourceinpharma.github.io/RinPharmaDiversityAlliance/) for more information

### Conferences

The conferences tab is up to date, we didn't get any volunteers to represent us at PHUSE US connect.

### OSTCDA numeric matching page

Michael Rimler is putting together a repo containing information about "Open Source Technology in Clinical Data Analysis (OSTCDA) for PHUSE. We now have a 'numerical matching' page [here](https://phuse-org.github.io/OSTCDA/match.html).\
Please review and feel free to suggest changes to the content. Contact Lyn @drlyntaylor for any further information.

**AOB**

-   Sarah raised an issue regarding retrieval of the documentation associated with 'old' versions of the R 'stats' package. For contributed packages, the documentation is present, but she's struggling to find the same for the 'stats' package. ACTION: Christina to help investigate.\
    The issue highlighted that we may have 1 version of a package which mis-matched with SAS, but that later versions would have different functionality, and may match. Keeping the repo up to date will be a challenge, but hopefully if people are using it, issues will be identified and corrected.\
    It's a reminder to ensure the code runs, from the data wherever possible. An issue for the SASvsR comparison pages is the comparison table is often typed in, such that if numbers change it wont be automatically updated. This is something we could consider in future. Perhaps running the code to populate the comparison table, and putting out a FAIL if conclusion changes from previous run, highlighting we need to update our written text.
