---
title: "Blogs, New content, Conferences"
date: "14 Apr 2025"
categories:
  - 2025
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2025_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 5)]),
  "html"
)
```

# Agenda & Minutes

-   Welcome new members !

    -   Mariusz Zięba (AZ)

    -   NOTE: for any questions/ discussion best to add into github issues or discussion tab.\
        We dont routinely look at teams so may miss your questions if loaded there.\
        Alternatively email: Email: [Lyn.taylor\@parexel.com](Lyn.taylor@parexel.com) or [Christina.e.fillmore\@gsk.com](mailto:Christina.e.fillmore@gsk.com){.email}

    -   ACTION: Lyn to check SAS PR from Jaskaran in Teams. Also go onto PHUSE TEAMS channel and add comment to ask people to contact us over github or email as we dont check teams.

-   Blog Update

    -   Yannick's Tobit regression blog was sent to PSI enews, and is on the CAMIS blog page.
    -   ACTION: Vikash to work on Blog for PHUSE US.
    -   Format for blogs
        -   PSI want short blog & cross reference to our repo for longer version.
        -   PHUSE want longer blogs.\
            ACTION: May be worth discussing with PHUSE the blogs, our plan to have monthly short blog pointing to recently content that has been added, but they requested the below?!
            -   Add a summary describing CAMIS

            -   Perhaps expand on when Tobit regression (for example) would be used

            -   Provide an example of use, input, output, explanation of results

            -   And to increase the length of this and make it more in the style of a blog (usual blogs limit is 1000 words)

-   Content updates in the last month ! Thank you All !

    -   Introduction to Machine learning - Andrey\
        ACTION : Christina to play with where it fits best & update TOC.

    -   Tobit Regression Yannick - updated to 1 sided p-values

    -   Sample size general summary and cochran-armitage trend test.

    -   CMH (to include risk differences) & RMST (to include more methods) - Lyn

    -   Soon - Propensity score matching will be loaded to repo today !

-   Repo Tech

    -   Repo now only re-builds when changes - Reduction in time from \>30 min now \<6 mins

    -   PR Previews - coming soon :) Thank you Michael Walshe!!

-   Conferences

    -   Yannick was accepted for Poster at ISBC46 24-28th Aug

    -   Fedor Logvin (PXL), is applying for PHUSE EU Connect 16-19 Nov.

        -   Yannick & Michael & Miriam (GLMM) may also submit & go

    -   R/Medicine - Final call for abstracts is 18th April\
        **ACTION:** If anyone wants to present let Lyn know by Wednesday this week, if no volunteers Christina and/or Lyn would go. Let Michael Kane know if we need 1-2 days extra to submit.\
        Schedule announcment 9th May, Pre-recorded video submission due 2nd June & Conference is 12th-13th June (via TC)

    -   R/Pharma Nov 3-7th info TBC. call for abstracts not yet open.

    -   R in HTA workshop - conference. Stephen attending in June.\
        <https://r-hta.org/events/workshop/2025/>

    -   Jaskaran is presenting in PHUSE CSS: Synthetic data.

    -   PSI event in Cambridge England re: moving to R: 3rd July. Yannick attending & can mention CAMIS.
