---
title: "SAS Viya, sasquatch, CAMIS End of Year Nominations, US Connect Poster"
date: "13 Oct 2025"
categories:
  - 2025
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2025_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 10)]),
  "html"
)
```

# Agenda & Minutes

-   SAS Viya for Learners (SASQUATCH)

    -   If you have SAS Viya, then you may be able to use sasquatch in R, to run SAS code.  If you can run sasPy, then you can also run sasquatch.

        <https://github.com/ropensci/sasquatch>

        The advantage here would be being able to compare R vs SAS numerically from code running.\
        Logan is going to create a guide & load to repo, then will hopefully present at a future meeting.  Initially, it will be an optional method, or you can continue to use normal SAS & image screen shot.

-   Within the repo:issues, anything labelled as 'Hackathon' was raised for adding package (session info) to pages -  Volunteers needed to add to current pages missing the session info.

-   Use the Discussions channel for technical stats discussions to share issues & progress.

    -   ACTION: Christina /Lyn to write something on Contrasts\....  ANCOVA / MMRM etc\...  how to output your contrast being made in the design.matrix.

-   Nominations for CAMIS End of Year Awards by 28^th^ Nov.

    -   Announcements in the December meeting.

-   US Connect Poster - There are a number of poster slots that have become available to Working Groups for US Connect. Time is limited to take advantage of this opportunity.  If you would like to submit a poster for consideration, please reply to this email with:

    -   Poster Title

    -   Poster Abstract

    -   Presenter Names

    By This **Friday 17 October COB** \
    \
    Please send poster submission direct to : workinggroups\@phuse.global   if you want to apply and say it's on behalf of CAMIS.

-   AOB

    -   Andy Miskell (Eli Lilly)  - Created a list of all their stats methods that they use.  They are going to go through and compare how they do it in SAS and how they do it in R. Will reference CAMIS if we have it available, or research it themselves, (and will hopefully add to CAMIS).  Will also write packages if there are gaps. Open to getting other companies to collaborate across organizations.

    -   Teaching proposal submitted by Yannick for a masters thesis student Feb/mar until June/July 2026.

    -   AZ organizing R conference for March 2026, CAMIS could be a presenter (30mins). Mariusz to offer one of us to present.

    -   ACTION Lyn: Reduce calls to 30 mins going forward.
