---
title: "Tipping point, ISBC Poster"
date: "11 Aug 2025"
categories:
  - 2025
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2025_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 8)]),
  "html"
)
```

# Agenda & Minutes

**New Content This Month**

-   Christina's guidance for how to select an appropriate R package to use for your work is now available [here](https://psiaims.github.io/CAMIS/contribution/Package-Review.html). You can also access it from [contribution](Get%20Involved) page, under the 'Asking for help' section using the short guidance link.

-   Sarah talked us through her Tipping point analysis [R page](https://psiaims.github.io/CAMIS/R/tipping_point.html) using {rbmi}. This page now contains a description of what tipping point analysis is, variations you can use and a case study example of how to investigate various delta to find the tipping point. The page demonstrates really helpful plots and easy to write code (so easy compared to SAS)!. Keep watch of the repo table of contents for arrival of the SAS page & Comparison page in the near future. With enough simulations R & SAS were found to match to 3 decimal places.

-   Lyn raised that Christina and her are still finding interesting issues with even simple analyses such as ANOVA. More information will be added shortly to the [ANOVA](ANOVA) page with regards to contr.treatment (the default which should not be used due to non-orthogonal contrasts), and the rationale of why we use contr.sum and contr.poly instead !

-   Miriam is writing GLMM pages including the methods using Laplace, GHQ & PQL, and will present this work at the PHUSE EU conference in Hamburg in November. Watch the repo for these pages in the near future.\

**Conferences.**

-   Miriam & Yannick are both presenting at PHUSE EU, so reach out to them if you are going and would like to meet up.

-   Yannick showed the team his ISBC CAMIS summary poster which will soon be available on the repo. Remember if you are attending any conferences or need to present a poster there is content you can use on the repo under [Conferences](Conferences).
