---
title: "General meeting updates"
date: "10 Feb 2025"
categories:
  - 2025
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2025_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 3)]),
  "html"
)
```

# Agenda & Minutes

-   **Volunteers needed for**

    -   CI for props section (See r page).

        -   any R packages that can do CI for matched 2 proportions using wilson or normal approximation methods.

        -   any R packages that can do CI for unmatched 2 proportions using newcombe (or wilson method)\
            (Stephen M suggested: <https://search.r-project.org/CRAN/refmans/DescTools/html/BinomDiffCI.html> and <https://cran.r-project.org/web/packages/presize/presize.pdf>\
            ACTION: Lyn to investigate & write up.

    -   NOTE: logistic regression will be updated soon to include Multiple treatment contrasts.\

-   **Conference planning** See latest Conference Tab on website (lyn updated today but needs PR approving)

```         
-   posit::conf(2025) deadline 3rd Feb in person atlanta

-   PHUSE US connect 16th-19th march. lyn to send content to Hamming Tu (Vikash attending) Lyn to CC vikash let Hamming know you are going. Vikash & Hamming to discuss any presenting plan for CAMIS

-   ISBC 14th Feb submission deadline. Yannick submitting abstract

-   Any others? Please add to the page
```

-   **Communication team update (Vikash & Molly)**

    -   Blog ideas

        -   latest repo updates (CI for Props)

        -   Key interesting findings

        -   Conferences

        -   Molly will maintain conferences tab going forward

-   **Content updates**\
    Anyone with any questions about what they are working on or how to assign themselves?

    -   MMRM (stephen waugh)

    -   CMH (Lyn)

    -   Sample size (agnieska)

    -   Reference based MI (Yannick)

    -   Generalized (binomial & multi-nom?) MMRM (Miriam)

    -   Wilcoxon signed rank coin package - Martin

    -   Propensity scores restriction on SAS vs R (Stephen McCawille & Christina)\

-   **Objective to get more regulatory input - ongoing**\
    Work with PSI AIMS as they plan a EMA regulatory panel discussion on R Any other ideas?\
    FDA/ Other regulators input/discussion.

-   Think about white paper.. on robustness of results and finding local minima in convergence that are actually issues?....

-   **University contacts - ongoing**

    -   Christina has a new student looking for CAMIS project

    -   Michael Kane : R medicine

    -   Yannick may have a intern in summer 8-10 weeks CAMIS research

    -   Stephen W doing MSc dissertation project on MMRM

-   **Technical back end improvements - ongoing**

-   **CAMIS- 3 x workshops - ongoing**

    -   Introduction to CAMIS project / how to contribute - Christina.

    -   Key findings of CAMIS project - Lyn

    -   How do you do comparisons in software

ACTION :Lyn to ask Orla if she can update renv for Yannicks PR. (And also explain how to do it so others can do it in future).\
