---
title: "2025 Awards"
date: "08 December 2025"
categories:
  - 2025
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2025_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 11)]),
  "html"
)
```

# Agenda & Minutes

**CAMIS 2025 Awards\
**As we approach the end of the year, Christina, Yannick and Lyn would like to Thank you All for your ongoing contributions and support.

Today we announced a few special awards  for people who have really impacted the project during 2025, helping CAMIS to continue to grow and improve,

-   **For Technical Innovation:  Michael Walshe -** Thank you for adding Caching to the website to make it run so much faster !

-   **For Shaping our Future:  Logan Johnson -** Thank you for challenging our core roots to be better - updates to the table of contents, help pages, running SAS and parallization

-   **For Communications: Molly Mcdiarmid -** Thank you for organizing all our wondering blogs this year

-   **For Student of the Year: Sarah Brosens -** Thank you for your amazing work on tipping point and recurrent event analysis

-   **For Newcomer of the Year: Miriam Amor -** Thank you for your amazing work on GEEs and presenting at PHUSE

-   **For Best Editor: Abi Terry -** Thank you for correcting and explanding our previous work on Cox PH tie handling

-   **For Stretching Boundaries: Fedor Logvin -** Thank you for adding great sections on propensity score matching and weighting

-   **For Being an All Star Contributor : Chi-Rong Li -** Thank you for completing R, SAS, EAST & Comparison pages on group sequential design for survival sample size.

Thank you all so much!

**AOB**

Brian Varney & David Bosak recently presented a single day event on behalf of PHUSE, showcasing ChatGPT for code conversion (e.g. SAS to R) and gave a shout out to the CAMIS project. In general, AI has shown to performed well on DM / manipulation processes, but needed human input for stats methods (which really highlights the need for the CAMIS project). 

Mariusz Zieba is organizing a AZ R conference 2^nd^ week march and will invite CAMIS leadership team to speak. Will follow up with more information in the new year. 

**Next Meeting**

At our first meeting in 2026, on the 12th January at 4:30 GMT, 5:30 CET, 11:30 EST, we will have a feedback session where we evaluate what is working well, what not so well, what you would like us to change, and will identify our key priorities for CAMIS in 2026.  If you have any ideas, please come along and share them with us. If you aren't able to attend, you are welcome to email any ideas you have for 2026 to Lyn prior to the meeting (lyn.taylor\@parexel.com).

The CAMIS leadership team would like to wish you a very happy festive season and look forward to working with you in 2026.
