---
title: "2026 PHUSE EU Call for papers" 
date: "13 April 2026" 
categories:   
  - 2026 
output:   
  html_document:      
    toc: true     
    toc_float: false     
    toc_level: 5     
    df_print: paged 
---

# Attendees

```{r}
#| label: attendees 
#| echo: false 
#| message: false 
#| warning: false  
attend_list <- readr::read_csv("../2026_team_members.csv") 
knitr::kable(   
  list(attend_list[c(1, 4)]), 
  "html" 
)
```

# Agenda & Minutes

New content in

-   Confidence intervals - single proportion and 2 independent proportions updated & live on repo. Thankyou to Peter Laud! Paired proportion, stratified designs & CIs for Rates expected hopefully in future

-   Binomial test updated

-   'Standard slides' to use at conference or internal team presentations available [here](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content/conferences/2026/CAMIS%20slides%20April%202026.pptx)

**Ongoing planned new content for 2026**

-   See last minutes for content still being worked on. Miriam kindly picked up survival: accelerated failure time models.

-   Please keep issues of issues up to date & add new where needed

**Blogs**

-   Miriams GEE/GLMM blog- Is ready for Molly to publish.

-   Sarah is working on Tipping point blog.

**Conference schedule**

-   PHUSE EU Connect 2026 15-18 Nov in Glasgow- call for papers is now open until 8th May. Michael Walshe is a steam chair for emerging trends and technology.

-   All - to try to attend conferences & represent CAMIS within your organizations to spread the word about our content !\
    We can provide attendees at conferences with PHUSE CAMIS t-shirts and/or stickers as needed.\

**Next meeting: 11th May 4:30 GMT, 5:30 CET and 11:30 EST**
