---
title: "2026 Welcome Abi !" 
date: "08 June 2026" 
categories:   
  - 2026 
output:   
  html_document:      
    toc: true     
    toc_float: false     
    toc_level: 5     
    df_print: paged 
---

# Attendees

```{r}
#| label: attendees 
#| echo: false 
#| message: false 
#| warning: false  
attend_list <- readr::read_csv("../2026_team_members.csv") 
knitr::kable(   
  list(attend_list[c(1, 6)]), 
  "html" 
)
```

# Agenda & Minutes

**Welcome Abi !**  \
Abi joins us from GSK to help cover for Christina who is now on maternity leave

**Content updates:** 

-   Clinton Arum - created a new readme, to explain the dataset files

-   Miriam Amor - created files for Survival - accelerated failure time models (R, SAS & Comp)

-   Yannick's student (\@griffinOyoo) creates files for Survival - weighted log rank test.

-   Miriam Amors blog: [Generalised Linear Mixed Models (GLMM) and Generalised Estimating Equations (GEE)](https://psiaims.github.io/CAMIS/blogs/posts/2026-05-27_GLMM-GEE/)

**Blogs:**

Tipping point is ready & sent to PHUSE.  May need to chase re: GLMM/GEE.   And then we have weighted log rank & AFT models.

**Conferences:**

-   PHARMASUG:  Brian gave an intro R programming workshop & plugged CAMIS. 

-   Martin Brown is at PSI with a CAMIS poster.

**AOB:** 

Miriam will update R page for AFT models, & Abi is reviewing RMST R file.

Abi, Lyn & Yannick will meet to go through open issues, assignments & strategic next steps for the project.

**Next meeting: 13th June 4:30 GMT, 5:30 CET and 11:30 EST**
