---
title: "2026 new content in for GLMM and CI for props" 
date: "09 March 2026" 
categories:   
  - 2026 
output:   
  html_document:      
    toc: true     
    toc_float: false     
    toc_level: 5     
    df_print: paged 
---

# Attendees

```{r}
#| label: attendees 
#| echo: false 
#| message: false 
#| warning: false  
attend_list <- readr::read_csv("../2026_team_members.csv") 
knitr::kable(   
  list(attend_list[c(1, 3)]), 
  "html" 
)
```

# Agenda & Minutes

New content in

-   GLMM - Miriam

-   CI for props - split into 5 sections Poisson rate CI's separate to binomial, PR in, awaiting review/approval.

-   Survival Cox_PH model using survival::strata, issue prior to Version 3.8.0

-   Upgrade of renv to later R version, led to many files changing 100+ files. So make sure you pull down latest repo before you do a PR.

-   upgrade also led to different code needed for SAS code / SAS files. Use 3 back ticks & {SAS} instead of {r} and #\|eval: false . see Generalized Linear Mixed Models (GLMM) SAS file as a good example.

**Ongoing planned new content for 2026**

-   CI for props binomial using cicalc - Christina

-   MMRM - Stephen Waugh

-   Kolmogorov-Smirnov test - My Luong Vuong: R, Molly MacDiarmid- SAS. Mariusz Zieba - python

-   Marginal homogenicity (SAS only) -  Molly / Lyn.

-   weighted log rank/ recurrent events - Yannick

-   RMST - GSK investigating

**Blogs**

-   [PHUSE DVOST CAMIS blog: Reference-Based Multiple Imputation](https://phuse.global/Communications/PHUSE_Blog/phuse-dvost-camis-blog-reference-based-multiple-imputation)

-   Next blogs could be

    -   Miriams GEE/GLMM content

    -   CI for props

**Conference schedule**

-   Lyn will create a Create 2026 template: Abstract, poster /  summary of progress to date/ latest content that could be used in conferences?  [2026 Conference material](https://phuseaccount.sharepoint.com/:f:/r/sites/ClinicalStatisticalReportinginaMultilingualWorld/Shared%20Documents/General/2026%20Conference%20material?csf=1&web=1&e=Yv8Tff "Original URL: https://phuseaccount.sharepoint.com/:f:/r/sites/ClinicalStatisticalReportinginaMultilingualWorld/Shared%20Documents/General/2026%20Conference%20material?csf=1&web=1&e=Yv8Tff. Click or tap if you trust this link.")

-   Becca Krouse (GSK) will represent us at PHUSE US connect.

-   PHUSE EU Connect - could do a workshop 1.5 hrs to identify issues & fix (like the diversity hackathon).

-   Christina presenting on Friday 13th March to the PSI apprentices\

**Next meeting: 13th April 4:30 GMT, 5:30 CET and 11:30 EST**
