---
title: "New Blog,  updates " 
date: "10 August 2026" 
categories:   
  - 2026 
output:   
  html_document:      
    toc: true     
    toc_float: false     
    toc_level: 5     
    df_print: paged 
---

# Attendees

```{r}
#| label: attendees 
#| echo: false 
#| message: false 
#| warning: false  
attend_list <- readr::read_csv("../2026_team_members.csv") 
knitr::kable(   
  list(attend_list[c(1, 8)]), 
  "html" 
)
```

# Agenda & Minutes

**Blogs**

The [Comparison of GLMMs and GEEs for Categorical Endpoints](https://phuse.global/Communications/PHUSE_Blog/phuse-dvost-camis-blog-comparison-of-glm-ms-and-ge-es-for-categorical-endpoints) blog is now live.

**Next Blogs plan:**

-   Weighted log rank test. Yannick & Molly to follow up.

**New content published in July:**

-   R-sas_glmm - substantial new section on translating common SAS PROC GLIMMIX model specifications into R, with 10 examples! [Generalized Linear Mixed Models (GLMM)](https://psiaims.github.io/CAMIS/Comp/r-sas_glmm.html)

-   PR issue (package conflict) to pull in the RMST new content (for R, SAS & R vs SAS). [Pull requests · PSIAIMS/CAMIS](https://github.com/PSIAIMS/CAMIS/pulls)

**If anyone is an expert on renv and wants to try to help please reach out to abigail.h.terry\@gsk.com and yvanden2\@its.jnj.com**

**Conferences:**

-   Molly presenting at R\\Pharma

-   Lyn submitting abstracts for PHUSE US Connect march Dallas, USA. 14-18th march 2027. One abstract will be a talk on Agentic AI using CAMIS as a skills agent and a second abstract will be submitted for a workshop/hackathon introducing people with how to contribute to the CAMIS repo.

**NOTE: If you are able to attend PHUSE US connect (eg. Have funding from your company to attend) and would be willing to volunteer to help Lyn run the hackathon please contact lyn.taylor\@parexel.com**

Idea for ICE breaker - collect info on who has heard of CAMIS, frequency of visits to CAMIS repo, Are they a contributor. Would also be useful to get github stats on frequency of visits to assess our impact.

**AOB**

-   Case studies: Suggestion to create user stories of people who are using CAMIS & how it's helped. Could be future blogs. \
    **If anyone would like to volunteer to write a short blog about how you've used CAMIS on a real study or project please get in touch with Molly.MacDiarmid\@parexel.com\
    **

-   LinkedIn article on fishers exact test in R vs python. Python default was restrictive, R default was most common method.

    Michael Kane - will check article vs our content to see we need to update anything.

**Next meeting: 14th September 4:30 GMT, 5:30 CET and 11:30 EST**
