---
title: "2026 Plans"
date: "12 January 2026"
categories:
  - 2026
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false

attend_list <- readr::read_csv("../2026_team_members.csv")
knitr::kable(
  list(attend_list[c(1, 2)]),
  "html"
)
```

# Agenda & Minutes

**Ideas for the CAMIS project in 2026 and volunteer needs !**

-   **Existing content review:**

    Volunteers needed to do existing content review & fixes / updates (content auditors). Action needed to go look through existing documentation and check it makes sense and all links still working. If you or anyone you know would like to volunteer to do this task let the leadership team know. For example, it would be a great activity for a junior statistician or programmer who wants exposure to new skills in open source programming and statistical analysis.

    -   **If you know of any issues/gaps in current content please add as issues  [Issues · PSIAIMS/CAMIS](https://github.com/PSIAIMS/CAMIS/issues)**

    -   **If you know of anyone who would be willing to volunteer please let us know! \
        New Year.. New you.. New project !!**

    -   **If your company would like us to run a hackathon sharing open source techniques wider with your colleagues which we could use to fix some of these issues then please contact us !**

-   **Comparison pages** - Python vs R vs SAS

    -   Current documentation is mostly focused on SAS & R.

    -   **Volunteers needed to update Comparison pages bringing in the python information**

    -   In some case may need separate docs (eg. Python vs R), but in most cases hopefully can put in same document as; R vs SAS vs Python - decision depends on size of content.

    -   Could consider Julia too to the project.

-   **Planned new content for 2026**

    -   update pages to be CMH Only (no CIs), Cis for props for single sample, add new page for CIs for proportion differences, ORs, Risk differences taking content from other pages & Updating to use cicalc package. (new cicalc version released now on cran) - Christina to action

    -   MMRM - Stephen Waugh hopes to complete in Jan

    -   Kolmogorov-Smirnov test - My Luong Vuong: R, Molly MacDiarmid- SAS. Mariusz Zieba - python

    -   Marginal homogenicity (SAS only) -  Molly / Lyn.

    -   Comparison pages for sample size - Agnieska doing in jan

    -   weighted log rank/ recurrent events - Yannick

    -   RMST Stephen McCawille no longer available to do this. Lyn or Yannick student to do R page.

    -   Remove LMM (DF row) or update to be linear mixed models (without repeated measures). Lyn & Christina to discuss with Stephen W & agree best titles for this section\
        \

-   Conference schedule & ensuring we are marketing our latest content & progress

    -   New blog released [CAMIS Blog](https://psiaims.github.io/CAMIS/blogs/) re: 2025 awards.

    -   Conference tab updated to be 2026. Please let us know if you want to present on CAMIS in 2026.

    -   Lyn & Yannick will create a Create 2026 template: Abstract, poster /  summary of progress to date/ latest content that could be used in conferences?  [2026 Conference material](https://phuseaccount.sharepoint.com/:f:/r/sites/ClinicalStatisticalReportinginaMultilingualWorld/Shared%20Documents/General/2026%20Conference%20material?csf=1&web=1&e=Yv8Tff "Original URL: https://phuseaccount.sharepoint.com/:f:/r/sites/ClinicalStatisticalReportinginaMultilingualWorld/Shared%20Documents/General/2026%20Conference%20material?csf=1&web=1&e=Yv8Tff. Click or tap if you trust this link.")

    -   Lyn has approval from Parexel to present to AZ R conference

    -   Becca Krouse (GSK) will represent us at PHUSE US connect.

    -   PHUSE EU Connect - could do a workshop 1.5 hrs to identify issues & fix (like the diversity hackathon).

    -   R in medicine - Christina potentially doing a workshop for diversity alliance.\
        \

-   AI & LLM on CAMIS repo - Long term goal ?? 

```{=html}
<!-- -->
```
-   PHUSE TEAMS area - has been updated. Welcome to store / communicate using it. 

-   **Communications update:**

    NOTE: new blog is now posted here: [CAMIS Blog](https://psiaims.github.io/CAMIS/blogs/)

    Lyn & Molly to meet with Alex re: PHUSE blogs because now there is a form, & 2 x review cycle.\
    Discuss sending Blogs vs sending emails to the team

    PSI process for blog delivery is working well, they link to our blogs via their newsletters.

-   **Next meeting: 9th February 4:30 GMT, 5:30 CET and 11:30 EST**
