{
  "hash": "d564d85ae12cce876ad5165ccf15dac3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R Recurrent Events\"\n---\n\n\n\n\n\n# Recurrent event models\n\n## Setup\n\n### General libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(gt)\n```\n:::\n\n\n\n### Methodology specific libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\n```\n:::\n\n\n\n## Modelling recurrent events\n\n### Methodology introduction\n\nTraditionally, survival analysis focuses on the time to a *single* first event. While there are many applications for such time-to-event analysis in clinical trials, this approach falls short when events of interest can occur multiple times within the same subject. Recurrent event models extend the traditional Cox proportional hazards framework to account for *multiple* events per subject ([Ozga et al. 2018](https://pubmed.ncbi.nlm.nih.gov/29301487/), [Amorim & Cai 2015](https://pubmed.ncbi.nlm.nih.gov/25501468/)).\n\nIn this tutorial, we will demonstrate how to implement different recurrent event models in R, specifically the Andersen-Gill, proportional means/rates, Prentice-Williams-Peterson, and Wei-Lin-Weissfeld models, using the well-known [`survival` package](https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf). The R code follows the layout of [Amor 2023](https://www.lexjansen.com/phuse/2023/as/PAP_AS05.pdf), with additional insights taken from [Lu et al. 2018](https://www.lexjansen.com/pharmasug/2018/EP/PharmaSUG-2018-EP02.pdf).\n\nRecurrent event models can roughly be divided in three categories: counting process models, conditional models and marginal models. In the section below, we will explore the difference between each of these approaches. In addition, important aspects of data structure will be discussed by means of two fictional subjects, one with 4 events and 0 censored observations (events at time 6, 9, 56 and 88), and another with 2 events and 1 censored observation (events at time 42, 57, and censored at time 91).\n\nDefine the following:\n\n::: callout-note\n$$*$$\n\n$\\lambda_i(t)$: hazard function for the $i$th subject at time $t$\n\n$\\lambda_{ij}(t)$: hazard function for the $j$th event of the $i$th subject at time $t$\n\n$\\lambda_0(t)$: common baseline hazard for all events\n\n$\\lambda_{0j}(t)$: event-specific baseline hazard for the $j$th event at time $t$\n\n$\\beta$: common parameter vector\n\n$\\beta_j$: event-specific parameter vector for the $j$th event\n\n$X_{ij}$: covariate vector for the $j$th event of the $i$th subject\n:::\n\n### Counting process models\n\n#### Andersen-Gill model ([Andersen & Gill 1982](https://projecteuclid.org/journals/annals-of-statistics/volume-10/issue-4/Coxs-Regression-Model-for-Counting-Processes--A-Large-Sample/10.1214/aos/1176345976.full))\n\n$$\n\\lambda_i(t) = \\lambda_0(t) \\exp \\left( \\beta X_{ij}(t) \\right) \\ *\n$$\n\n-   Counting process approach: treats each subject as a multiple events counting process\n\n-   Common baseline hazard $\\lambda_0(t)$\n\n-   Common regression coefficients $\\beta$\n\n-   Unrestricted risk set: a subject contributes to the risk set for an event as long as the subject is under observation, i.e. it can be at risk for a subsequent event even though the previous event did not yet occur\n\n-   Order of events is not important\n\nAn essential assumption of the Andersen-Gill model is that of **independent events** within subjects. This, however, is often not realistic in clinical trial data. For example, let's say that we are modelling myocardial infarction (MI). If a patient has already experienced one MI, their risk of subsequent events may increase due to underlying cardiovascular damage or presence of other risk factors. Thus, the more events a patient has, the more likely they are to experience future events, indicating dependence rather than independence. To accurately model this within-subject correlation, extensions like time-varying covariates, a robust sandwich covariance estimator or frailty terms may be needed. In this tutorial, we will discuss the sandwich correction.\n\n**Lin-Wei-Yang-Ying (LWYY) model or proportional means/rates model ([Lin, Wei, Yang & Ying 2000](https://www.jstor.org/stable/2680616))**\n\nLin, Wei, Yang, and Ying introduced an improved version of the Andersen-Gill model in 2000 (often referred to as proportional means/rates model), featuring a robust sandwich estimator that explicitly accounts for individual subject clusters. These robust standard errors yield wider confidence intervals and provide asymptotically valid inference even when the independence assumption does not hold ([Lee et al. 2025](https://pubmed.ncbi.nlm.nih.gov/40490702/)). The original and improved Andersen-Gill model often appear interchangeable in the literature, and while they produce identical estimates, their robust standard errors can differ substantially, which may impact the conclusions drawn from statistical inference.\n\nFor both versions of the Andersen-Gill model, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (6, 9\\]       | 1     | 1       |\n| 1       | (9, 56\\]      | 1     | 1       |\n| 1       | (56, 88\\]     | 1     | 1       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (42, 87\\]     | 1     | 1       |\n| 2       | (87, 91\\]     | 0     | 1       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/AG_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nIn both versions of the Andersen-Gill model, each new time interval starts where the previous one ends.\n\n### Conditional models\n\n#### Prentice-Williams-Peterson model ([Prentice, Williams & Peterson 1981](https://academic.oup.com/biomet/article-abstract/68/2/373/260402?redirectedFrom=fulltext))\n\n-   Conditional approach: incorporates conditional strata to account for ordering/dependence of events\n\n-   Stratified baseline hazard $\\lambda_{0j}(t)$\n\n-   Stratified regression coefficients $\\beta_j$: can be pooled ($\\beta$) or kept as event-specific ($\\beta_j$) in the output\n\n-   Restricted risk set: contributions to the risk set for a subsequent event are restricted to only consider subjects that already experienced the previous event\n\n-   Order of events is important\n\nThe Prentice-Williams-Peterson model can incorporate both overall and event-specific effects $\\beta_j$ for each covariate. An often made assumption is to set $\\beta_1 = \\beta_2 = ... = \\beta_k = \\beta$ to estimate a common parameter $\\beta$.\n\nDepending on the outcome of interest, Prentice, Williams and Peterson suggested two distinct models:\n\n1.  **Total time model**\n\n$$\n\\lambda_{ij}(t) = \\lambda_{0j}(t) \\exp \\left( \\beta_j X_{ij}(t) \\right) \\ *\n$$\n\nThe total time variant of the Prentice-Williams-Peterson model uses the same time intervals as the counting process approach (Andersen-Gill model), which is useful for modelling the full time course ($t$) of the recurrent event process, i.e. the hazard of *any* recurrence.\n\nFor the total time model, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (6, 9\\]       | 1     | 2       |\n| 1       | (9, 56\\]      | 1     | 3       |\n| 1       | (56, 88\\]     | 1     | 4       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (42, 87\\]     | 1     | 2       |\n| 2       | (87, 91\\]     | 0     | 3       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/PWPtt_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nAgain, in the total time model, each new time intervals starts where the previous one ends.\n\n2.  **Gap time model**\n\n$$\n\\lambda_{ij}(t) = \\lambda_{0j}(t - t_{j-1}) \\exp \\left( \\beta_j X_{ij}(t) \\right) \\ *\n$$\n\nThe gap time variant of the Prentice-Williams-Peterson model uses time intervals that start at zero and end at the length of time until the next event, which is useful for modelling the time between each of the recurring events ($t - t_{j-1}$), i.e. the hazard of recurrence *after the previous event*.\n\nFor the gap time model, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (0, 3\\]       | 1     | 2       |\n| 1       | (0, 47\\]      | 1     | 3       |\n| 1       | (0, 32\\]      | 1     | 4       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (0, 45\\]      | 1     | 2       |\n| 2       | (0, 3\\]       | 0     | 3       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/PWPgt_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nIn the gap time model, each time interval starts at zero and has a length equal to the gap time between two neighboring events.\n\n### Marginal models\n\n#### Wei-Lin-Weissfeld model ([Wei, Lin & Weissfeld 1989](https://www.jstor.org/stable/2290084))\n\n$$\n\\lambda_{ij}(t) = \\lambda_{0j}(t) \\exp \\left( \\beta_j X_{ij}(t) \\right) \\ * \n$$\n\n-   Marginal approach: treats each (recurrent) event as having a separate, marginal process\n\n-   Stratified baseline hazard $\\lambda_{0j}(t)$\n\n-   Stratified regression coefficients $\\beta_j$: can be pooled ($\\beta$) or kept as event-specific ($\\beta_j$) in the output\n\n-   Semi-restricted risk set: all subjects contribute follow-up times to all *potential* events, i.e. each subject is at risk for all *potential* events, regardless of how many events that subject actually experiences\n\n-   Order of events is not important\n\nAlthough the Wei-Lin-Weissfeld model has it roots in competing risks analysis, it conveniently lends itself to model recurrent events as well. Like the Andersen-Gill model, the Wei-Lin-Weissfeld model also assumes **independence** of events, which is often not feasible in practice. In addition, it is assumed there is no specific order among the events or that the events are different types of events, and not necessarily *recurrent* events.\n\nLike the Prentice-Williams-Peterson models, the Wei-Lin-Weissfeld model can incorporate both overall and event-specific effects $\\beta_j$ for each covariate. An often made assumption is to set $\\beta_1 = \\beta_2 = ... = \\beta_k = \\beta$ to estimate a common parameter $\\beta$. Another approach is to combine event-specific effects $\\beta_j$ to get an estimator of the average effect, as described in [Wei, Lin & Weissfeld 1989](https://www.jstor.org/stable/2290084) (this is not discussed further here).\n\nFor Wei-Lin-Weissfeld models, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (0, 9\\]       | 1     | 2       |\n| 1       | (0, 56\\]      | 1     | 3       |\n| 1       | (0, 88\\]      | 1     | 4       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (0, 87\\]      | 1     | 2       |\n| 2       | (0, 91\\]      | 0     | 3       |\n| 2       | (0, 91\\]      | 0     | 4       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/WLW_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nIn the Wei-Lin-Weissfeld model, each time intervals starts at zero and ends at its respective event time.\n\n### Overview of all models\n\nIn summary, the selection of the model to use would depend on the type of events, the importance of the order of the events and the time intervals to be analyzed. We made an effort to summarize the similarities and differences between the models in the table below.\n\n|   | **AG** | **PWPtt** | **PWPgt** | **WLW** |\n|---------------|---------------|---------------|---------------|---------------|\n| **Approach** | counting process | conditional | conditional | marginal |\n| **Baseline hazard** | common | stratified | stratified | stratified |\n| **Regression coefficients** | common | stratified possible | stratified possible | stratified possible |\n| **Risk set** | unrestricted | restricted | restricted | semi-restricted |\n| **Time interval** | total time | total time | gap time | total time |\n| **Order of events** | not important | important | important | not important |\n| **Hazard ratio (HR)** | risk of any recurrence | risk of any recurrence | risk of recurrence after previous event | risk of event of any type, not necessarily recurrent event |\n\nNote that, because the ordering of events is not important in the Andersen-Gill and Wei-Lin-Weissfeld model, these models come with the assumption of **independence** of events. In contrast, the Prentice-Williams-Peterson models overcome the need for this assumption by capturing the dependence structure between recurrent events in conditional strata. Consequently, events are assumed to be *conditionally* independent in the Prentice-Williams-Peterson models.\n\nA nice visual representation of the stratification and time interval structure of each model is given below. The correct data structure is pivotal when modelling recurrent events and depends on the methodology you want to use, as illustrated in the figure.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/combined_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Modelling recurrent events using the `survival` package\n\n### Data\n\nFor this tutorial we will use the [`bladder` data](https://rdrr.io/cran/survival/man/bladder.html) from the [`survival` package](https://cran.r-project.org/web/packages/survival/survival.pdf), which captures recurrences of bladder cancer from a clinical trial for an oncolytic called thiotepa. The `bladder` data is regularly used by many statisticians to demonstrate methodology for recurrent event modelling. Somewhat confusingly, there are three versions of this data available:\n\n-   `bladder1`: original data from the study on all subjects (294 records)\n\n-   `bladder2`: data in Andersen-Gill format on subset of subjects with nonzero follow-up time (178 records)\n\n-   `bladder`: data in Wei-Lin-Weissfeld format on subset of subjects with nonzero follow-up time (340 records)\n\nFor this tutorial, we will use `bladder2` to illustrate Andersen-Gill and Prentice-Williams-Peterson models, and `bladder` to illustrate the Wei-Lin-Weissfeld model.\n\nThe variables included in both datasets are:\n\n-   **id**: patient id\n\n-   **rx**: treatment group (1 = placebo, 2 = thiotepa)\n\n-   **number**: initial number of tumors (8 = 8 or more)\n\n-   **size**: size in cm of largest initial tumor\n\n-   **start**: start of time interval; this variable is **not** present in `bladder`\n\n-   **stop**: (recurrent) event or censoring time\n\n-   **event**: event indicator (1 = event, 0 = censored)\n\n-   **enum**: order of recurrence\n\nImportantly, both datasets collect the data in a **counting process** structure. This means that there is one record for each subject and time interval, where a time interval is defined as the time to its respective event (**event** = 1), or the time to follow-up if the event did not occur (**event** = 0).\n\nLet's look more closely at the `bladder2` and `bladder` data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder2 <- survival::bladder2\ngt(head(bladder2, 6))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xmguuysfps\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xmguuysfps table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xmguuysfps thead, #xmguuysfps tbody, #xmguuysfps tfoot, #xmguuysfps tr, #xmguuysfps td, #xmguuysfps th {\n  border-style: none;\n}\n\n#xmguuysfps p {\n  margin: 0;\n  padding: 0;\n}\n\n#xmguuysfps .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xmguuysfps .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xmguuysfps .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xmguuysfps .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xmguuysfps .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xmguuysfps .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xmguuysfps .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xmguuysfps .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xmguuysfps .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xmguuysfps .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xmguuysfps .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xmguuysfps .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xmguuysfps .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xmguuysfps .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xmguuysfps .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xmguuysfps .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xmguuysfps .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xmguuysfps .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xmguuysfps .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xmguuysfps .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xmguuysfps .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xmguuysfps .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xmguuysfps .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xmguuysfps .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xmguuysfps .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xmguuysfps .gt_left {\n  text-align: left;\n}\n\n#xmguuysfps .gt_center {\n  text-align: center;\n}\n\n#xmguuysfps .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xmguuysfps .gt_font_normal {\n  font-weight: normal;\n}\n\n#xmguuysfps .gt_font_bold {\n  font-weight: bold;\n}\n\n#xmguuysfps .gt_font_italic {\n  font-style: italic;\n}\n\n#xmguuysfps .gt_super {\n  font-size: 65%;\n}\n\n#xmguuysfps .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xmguuysfps .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xmguuysfps .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xmguuysfps .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xmguuysfps .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xmguuysfps .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xmguuysfps .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xmguuysfps .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xmguuysfps div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rx\">rx</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number\">number</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"size\">size</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"start\">start</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stop\">stop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"event\">event</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">6</td>\n<td headers=\"event\" class=\"gt_row gt_right\">1</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">6</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder2 %>%\n  group_by(enum) %>% summarise(n = n()) %>% gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nzglksluaq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nzglksluaq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nzglksluaq thead, #nzglksluaq tbody, #nzglksluaq tfoot, #nzglksluaq tr, #nzglksluaq td, #nzglksluaq th {\n  border-style: none;\n}\n\n#nzglksluaq p {\n  margin: 0;\n  padding: 0;\n}\n\n#nzglksluaq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nzglksluaq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nzglksluaq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nzglksluaq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nzglksluaq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nzglksluaq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nzglksluaq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nzglksluaq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nzglksluaq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nzglksluaq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nzglksluaq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nzglksluaq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nzglksluaq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nzglksluaq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nzglksluaq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzglksluaq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nzglksluaq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nzglksluaq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nzglksluaq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzglksluaq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nzglksluaq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzglksluaq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nzglksluaq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzglksluaq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nzglksluaq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nzglksluaq .gt_left {\n  text-align: left;\n}\n\n#nzglksluaq .gt_center {\n  text-align: center;\n}\n\n#nzglksluaq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nzglksluaq .gt_font_normal {\n  font-weight: normal;\n}\n\n#nzglksluaq .gt_font_bold {\n  font-weight: bold;\n}\n\n#nzglksluaq .gt_font_italic {\n  font-style: italic;\n}\n\n#nzglksluaq .gt_super {\n  font-size: 65%;\n}\n\n#nzglksluaq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nzglksluaq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nzglksluaq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nzglksluaq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nzglksluaq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nzglksluaq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nzglksluaq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nzglksluaq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nzglksluaq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">2</td>\n<td headers=\"n\" class=\"gt_row gt_right\">46</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">3</td>\n<td headers=\"n\" class=\"gt_row gt_right\">27</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">4</td>\n<td headers=\"n\" class=\"gt_row gt_right\">20</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nIn `bladder2`, in the Andersen-Gill format, each subject has a variable amount of records, depending on the amount of events that subject experienced.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder <- survival::bladder\ngt(head(bladder, 20))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nrhxkfnmot\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nrhxkfnmot table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nrhxkfnmot thead, #nrhxkfnmot tbody, #nrhxkfnmot tfoot, #nrhxkfnmot tr, #nrhxkfnmot td, #nrhxkfnmot th {\n  border-style: none;\n}\n\n#nrhxkfnmot p {\n  margin: 0;\n  padding: 0;\n}\n\n#nrhxkfnmot .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nrhxkfnmot .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nrhxkfnmot .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nrhxkfnmot .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nrhxkfnmot .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nrhxkfnmot .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nrhxkfnmot .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nrhxkfnmot .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nrhxkfnmot .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nrhxkfnmot .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nrhxkfnmot .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nrhxkfnmot .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nrhxkfnmot .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nrhxkfnmot .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nrhxkfnmot .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrhxkfnmot .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nrhxkfnmot .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nrhxkfnmot .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nrhxkfnmot .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrhxkfnmot .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nrhxkfnmot .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrhxkfnmot .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nrhxkfnmot .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrhxkfnmot .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nrhxkfnmot .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrhxkfnmot .gt_left {\n  text-align: left;\n}\n\n#nrhxkfnmot .gt_center {\n  text-align: center;\n}\n\n#nrhxkfnmot .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nrhxkfnmot .gt_font_normal {\n  font-weight: normal;\n}\n\n#nrhxkfnmot .gt_font_bold {\n  font-weight: bold;\n}\n\n#nrhxkfnmot .gt_font_italic {\n  font-style: italic;\n}\n\n#nrhxkfnmot .gt_super {\n  font-size: 65%;\n}\n\n#nrhxkfnmot .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nrhxkfnmot .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nrhxkfnmot .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nrhxkfnmot .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nrhxkfnmot .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nrhxkfnmot .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nrhxkfnmot .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nrhxkfnmot .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nrhxkfnmot div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rx\">rx</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number\">number</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"size\">size</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stop\">stop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"event\">event</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">6</td>\n<td headers=\"event\" class=\"gt_row gt_right\">1</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder %>%\n  group_by(enum) %>% summarise(n = n()) %>% gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rugtpcxhyt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rugtpcxhyt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rugtpcxhyt thead, #rugtpcxhyt tbody, #rugtpcxhyt tfoot, #rugtpcxhyt tr, #rugtpcxhyt td, #rugtpcxhyt th {\n  border-style: none;\n}\n\n#rugtpcxhyt p {\n  margin: 0;\n  padding: 0;\n}\n\n#rugtpcxhyt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rugtpcxhyt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rugtpcxhyt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rugtpcxhyt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rugtpcxhyt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rugtpcxhyt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rugtpcxhyt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rugtpcxhyt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rugtpcxhyt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rugtpcxhyt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rugtpcxhyt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rugtpcxhyt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rugtpcxhyt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rugtpcxhyt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rugtpcxhyt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rugtpcxhyt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rugtpcxhyt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rugtpcxhyt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rugtpcxhyt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rugtpcxhyt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rugtpcxhyt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rugtpcxhyt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rugtpcxhyt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rugtpcxhyt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rugtpcxhyt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rugtpcxhyt .gt_left {\n  text-align: left;\n}\n\n#rugtpcxhyt .gt_center {\n  text-align: center;\n}\n\n#rugtpcxhyt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rugtpcxhyt .gt_font_normal {\n  font-weight: normal;\n}\n\n#rugtpcxhyt .gt_font_bold {\n  font-weight: bold;\n}\n\n#rugtpcxhyt .gt_font_italic {\n  font-style: italic;\n}\n\n#rugtpcxhyt .gt_super {\n  font-size: 65%;\n}\n\n#rugtpcxhyt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rugtpcxhyt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rugtpcxhyt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rugtpcxhyt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rugtpcxhyt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rugtpcxhyt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rugtpcxhyt .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rugtpcxhyt .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rugtpcxhyt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">2</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">3</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">4</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nIn `bladder`, in the Wei-Lin-Weissfeld format, each subject has four records, regardless of how many events that subject actually experienced. In addition, there is no `start` variable, as all time intervals start at zero.\n\n### Analysis\n\nIn the `survival` package, any survival analysis based on the Cox proportional hazard model can be conducted using the `coxph()` function. Hence, conveniently, when modelling time-to-event data with recurrent events, the same function can be used. The caveat here is that an adequate data structure is required, which must be in correspondence with the model you want to use.\n\nIn this section of the tutorial, we will explain how the arguments of the `coxph()` function and data structure must be defined to fit every type of recurrent event model correctly.\n\n#### Andersen-Gill model\n\n1.  **Improved Andersen-Gill model (LWYY model or proportional means/rates model)**\n\nFor the improved version of the Andersen-Gill model you must specify:\n\n-   `formula = Surv(start, stop, event) ~ 'predictors'`\n\n-   `cluster = id`\n\nAnd the data structure must be:\n\n| Id  | Time interval | Start | Stop | Event |\n|-----|---------------|-------|------|-------|\n| 1   | (0, 1\\]       | 0     | 1    | 0     |\n| 2   | (0, 4\\]       | 0     | 4    | 0     |\n| 3   | (0, 7\\]       | 0     | 7    | 0     |\n| 4   | (0, 10\\]      | 0     | 10   | 0     |\n| 5   | (0, 6\\]       | 0     | 6    | 1     |\n| 5   | (6, 10\\]      | 6     | 10   | 0     |\n\nWe will use the `bladder2` data for this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAG <- coxph(Surv(start, stop, event) ~ as.factor(rx) + number + size,\n            ties = \"breslow\",\n            cluster = id,\n            data = bladder2)\nsummary(AG)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(start, stop, event) ~ as.factor(rx) + number + \n    size, data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                   coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nas.factor(rx)2 -0.45979   0.63142  0.19996   0.25801 -1.782  0.07474 . \nnumber          0.17164   1.18726  0.04733   0.06131  2.799  0.00512 **\nsize           -0.04256   0.95833  0.06903   0.07555 -0.563  0.57317   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.6314     1.5837    0.3808     1.047\nnumber            1.1873     0.8423    1.0528     1.339\nsize              0.9583     1.0435    0.8264     1.111\n\nConcordance= 0.634  (se = 0.032 )\nLikelihood ratio test= 16.77  on 3 df,   p=8e-04\nWald test            = 11.76  on 3 df,   p=0.008\nScore (logrank) test = 18.57  on 3 df,   p=3e-04,   Robust = 11.44  p=0.01\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\nBy defining the `cluster` argument, `coxph()` will automatically set `robust = TRUE`, and compute a robust sandwich covariance. The summary function will then display both the non-robust (`se(coef)`) and robust (`robust se`) standard error estimates. Under the hood, the robust standard errors will consider all **id** clusters separately and ultimately sum up the score residuals for each distinct cluster.\n\n2.  **Original Andersen-Gill model**\n\nTo our knowledge, the original Andersen-Gill model of 1989 can only be fitted in R by adding an artificial clustering variable with unique entries to the `bladder2` data, which we call `id2`. This artificial clustering variable will ignore any clustering that is actually present in the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder2 <- bladder2 %>%\n  dplyr::mutate(id2 = row_number())\n```\n:::\n\n\n\nExcept for `cluster = id2`, the rest of the code remains the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAG_original <- coxph(Surv(start, stop, event) ~ as.factor(rx) + number + size,\n            ties = \"breslow\",\n            cluster = id2,\n            data = bladder2)\nsummary(AG_original)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(start, stop, event) ~ as.factor(rx) + number + \n    size, data = bladder2, ties = \"breslow\", cluster = id2)\n\n  n= 178, number of events= 112 \n\n                   coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nas.factor(rx)2 -0.45979   0.63142  0.19996   0.22902 -2.008  0.04468 * \nnumber          0.17164   1.18726  0.04733   0.06469  2.653  0.00797 **\nsize           -0.04256   0.95833  0.06903   0.07325 -0.581  0.56119   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.6314     1.5837    0.4031    0.9891\nnumber            1.1873     0.8423    1.0459    1.3477\nsize              0.9583     1.0435    0.8302    1.1063\n\nConcordance= 0.634  (se = 0.032 )\nLikelihood ratio test= 16.77  on 3 df,   p=8e-04\nWald test            = 9.36  on 3 df,   p=0.02\nScore (logrank) test = 18.57  on 3 df,   p=3e-04,   Robust = 14.27  p=0.003\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\nAlthough the original Andersen-Gill model does not consider separate **id** clusters, it still computes robust standard errors using the sandwich estimator, as `robust = TRUE`. The resulting robust standard errors (`robust se`) differ from those provided for the improved Andersen-Gill model, while the estimated coefficients (`coef`) and non-robust standard errors (`se(coef)`) remain perfectly unchanged.\n\n#### Prentice-Williams-Peterson model\n\n1.  **Total time model**\n\nFor the Prentice-Williams-Peterson total time model you must specify:\n\n-   `formula = Surv(start, stop, event) ~ 'predictors' + strata(enum)`\n\n-   `cluster = id`\n\nAnd the data structure must be:\n\n| Id  | Time interval | Start | Stop | Event | Enum |\n|-----|---------------|-------|------|-------|------|\n| 1   | (0, 1\\]       | 0     | 1    | 0     | 1    |\n| 2   | (0, 4\\]       | 0     | 4    | 0     | 1    |\n| 3   | (0, 7\\]       | 0     | 7    | 0     | 1    |\n| 4   | (0, 10\\]      | 0     | 10   | 0     | 1    |\n| 5   | (0, 6\\]       | 0     | 6    | 1     | 1    |\n| 5   | (6, 10\\]      | 6     | 10   | 0     | 2    |\n\nWe will use the `bladder2` data for this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPWPtt <- coxph(Surv(start, stop, event) ~ as.factor(rx) + number + size + strata(enum),\n            ties = \"breslow\",\n            cluster = id,\n            data = bladder2)\nsummary(PWPtt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(start, stop, event) ~ as.factor(rx) + number + \n    size + strata(enum), data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                    coef exp(coef)  se(coef) robust se      z Pr(>|z|)  \nas.factor(rx)2 -0.334295  0.715842  0.216087  0.197064 -1.696   0.0898 .\nnumber          0.115653  1.122606  0.053681  0.049913  2.317   0.0205 *\nsize           -0.008051  0.991982  0.072725  0.060124 -0.134   0.8935  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.7158     1.3970    0.4865     1.053\nnumber            1.1226     0.8908    1.0180     1.238\nsize              0.9920     1.0081    0.8817     1.116\n\nConcordance= 0.615  (se = 0.032 )\nLikelihood ratio test= 6.11  on 3 df,   p=0.1\nWald test            = 7.19  on 3 df,   p=0.07\nScore (logrank) test = 6.45  on 3 df,   p=0.09,   Robust = 8.76  p=0.03\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\nThe conditional strata of the Prentice-Williams-Peterson model are set by `strata(enum)` in the formula, where `enum` captures the ordering of recurrent events.\n\n2.  **Gap time model**\n\nFor the Prentice-Williams-Peterson gap time model you must specify:\n\n-   `formula = Surv(gtime, event) ~ 'predictors' + strata(enum)`\n\n-   `cluster = id`\n\nAnd the data structure must be:\n\n| Id  | Time interval | Start | Stop | Event | Enum |\n|-----|---------------|-------|------|-------|------|\n| 1   | (0, 1\\]       | 0     | 1    | 0     | 1    |\n| 2   | (0, 4\\]       | 0     | 4    | 0     | 1    |\n| 3   | (0, 7\\]       | 0     | 7    | 0     | 1    |\n| 4   | (0, 10\\]      | 0     | 10   | 0     | 1    |\n| 5   | (0, 6\\]       | 0     | 6    | 1     | 1    |\n| 5   | (0, 4\\]       | 0     | 4    | 0     | 2    |\n\nThis data structure can be achieved in `bladder2` by adding a `gtime` variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder2 <- bladder2 %>%\n  dplyr::mutate(gtime = stop - start)\n  \ngt(head(bladder2, 6))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mwpidsqutb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mwpidsqutb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mwpidsqutb thead, #mwpidsqutb tbody, #mwpidsqutb tfoot, #mwpidsqutb tr, #mwpidsqutb td, #mwpidsqutb th {\n  border-style: none;\n}\n\n#mwpidsqutb p {\n  margin: 0;\n  padding: 0;\n}\n\n#mwpidsqutb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mwpidsqutb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mwpidsqutb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mwpidsqutb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mwpidsqutb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mwpidsqutb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mwpidsqutb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mwpidsqutb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mwpidsqutb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mwpidsqutb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mwpidsqutb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mwpidsqutb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mwpidsqutb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mwpidsqutb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mwpidsqutb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwpidsqutb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mwpidsqutb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mwpidsqutb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mwpidsqutb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwpidsqutb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mwpidsqutb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwpidsqutb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mwpidsqutb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwpidsqutb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mwpidsqutb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mwpidsqutb .gt_left {\n  text-align: left;\n}\n\n#mwpidsqutb .gt_center {\n  text-align: center;\n}\n\n#mwpidsqutb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mwpidsqutb .gt_font_normal {\n  font-weight: normal;\n}\n\n#mwpidsqutb .gt_font_bold {\n  font-weight: bold;\n}\n\n#mwpidsqutb .gt_font_italic {\n  font-style: italic;\n}\n\n#mwpidsqutb .gt_super {\n  font-size: 65%;\n}\n\n#mwpidsqutb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mwpidsqutb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mwpidsqutb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mwpidsqutb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mwpidsqutb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mwpidsqutb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mwpidsqutb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mwpidsqutb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mwpidsqutb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rx\">rx</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number\">number</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"size\">size</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"start\">start</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stop\">stop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"event\">event</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id2\">id2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"gtime\">gtime</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"id2\" class=\"gt_row gt_right\">1</td>\n<td headers=\"gtime\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"id2\" class=\"gt_row gt_right\">2</td>\n<td headers=\"gtime\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"id2\" class=\"gt_row gt_right\">3</td>\n<td headers=\"gtime\" class=\"gt_row gt_right\">7</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"id2\" class=\"gt_row gt_right\">4</td>\n<td headers=\"gtime\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">6</td>\n<td headers=\"event\" class=\"gt_row gt_right\">1</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"id2\" class=\"gt_row gt_right\">5</td>\n<td headers=\"gtime\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">6</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td>\n<td headers=\"id2\" class=\"gt_row gt_right\">6</td>\n<td headers=\"gtime\" class=\"gt_row gt_right\">4</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nWe artificially set start = 0 for each gap time interval by including `gtime` instead of `start, stop` in the `Surv()` object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPWPgt <- coxph(Surv(gtime, event) ~ as.factor(rx) + number + size + strata(enum),\n            ties = \"breslow\",\n            cluster = id,\n            data = bladder2)\nsummary(PWPgt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(gtime, event) ~ as.factor(rx) + number + \n    size + strata(enum), data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                   coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nas.factor(rx)2 -0.26952   0.76375  0.20766   0.20808 -1.295  0.19522   \nnumber          0.15353   1.16595  0.05211   0.04889  3.140  0.00169 **\nsize            0.00684   1.00686  0.07001   0.06222  0.110  0.91246   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.7637     1.3093    0.5080     1.148\nnumber            1.1659     0.8577    1.0594     1.283\nsize              1.0069     0.9932    0.8913     1.137\n\nConcordance= 0.596  (se = 0.032 )\nLikelihood ratio test= 8.76  on 3 df,   p=0.03\nWald test            = 12.14  on 3 df,   p=0.007\nScore (logrank) test = 9.6  on 3 df,   p=0.02,   Robust = 10.21  p=0.02\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\n#### Wei-Lin-Weissfeld model\n\nFor the Wei-Lin-Weissfeld model you must specify:\n\n-   `formula = Surv(stop, event) ~ 'predictors' + strata(enum)`\n\n-   `cluster = id`\n\nAnd the data structure must be:\n\n| Id  | Time interval | Start | Stop | Event | Enum |\n|-----|---------------|-------|------|-------|------|\n| 1   | (0, 1\\]       | 0     | 1    | 0     | 1    |\n| 1   | (0, 1\\]       | 0     | 1    | 0     | 2    |\n| 1   | (0, 1\\]       | 0     | 1    | 0     | 3    |\n| 1   | (0, 1\\]       | 0     | 1    | 0     | 4    |\n| 2   | (0, 4\\]       | 0     | 4    | 0     | 1    |\n| 2   | (0, 4\\]       | 0     | 4    | 0     | 2    |\n| 2   | (0, 4\\]       | 0     | 4    | 0     | 3    |\n| 2   | (0, 4\\]       | 0     | 4    | 0     | 4    |\n| 3   | (0, 7\\]       | 0     | 7    | 0     | 1    |\n| 3   | (0, 7\\]       | 0     | 7    | 0     | 2    |\n| 3   | (0, 7\\]       | 0     | 7    | 0     | 3    |\n| 3   | (0, 7\\]       | 0     | 7    | 0     | 4    |\n| 4   | (0, 10\\]      | 0     | 10   | 0     | 1    |\n| 4   | (0, 10\\]      | 0     | 10   | 0     | 2    |\n| 4   | (0, 10\\]      | 0     | 10   | 0     | 3    |\n| 4   | (0, 10\\]      | 0     | 10   | 0     | 4    |\n| 5   | (0, 6\\]       | 0     | 6    | 1     | 1    |\n| 5   | (0, 10\\]      | 0     | 10   | 0     | 2    |\n| 5   | (0, 10\\]      | 0     | 10   | 0     | 3    |\n| 5   | (0, 10\\]      | 0     | 10   | 0     | 4    |\n\nWe will use the `bladder` data for this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWLW <- coxph(Surv(stop, event) ~ as.factor(rx) + number + size + strata(enum),\n            ties = \"breslow\",\n            cluster = id,\n            data = bladder)\nsummary(WLW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(stop, event) ~ as.factor(rx) + number + \n    size + strata(enum), data = bladder, ties = \"breslow\", cluster = id)\n\n  n= 340, number of events= 112 \n\n                   coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nas.factor(rx)2 -0.57986   0.55998  0.20118   0.30344 -1.911   0.0560 . \nnumber          0.20849   1.23182  0.04691   0.06567  3.175   0.0015 **\nsize           -0.05094   0.95034  0.06967   0.09304 -0.548   0.5840   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.5600     1.7858    0.3089     1.015\nnumber            1.2318     0.8118    1.0830     1.401\nsize              0.9503     1.0523    0.7919     1.140\n\nConcordance= 0.663  (se = 0.036 )\nLikelihood ratio test= 24.71  on 3 df,   p=2e-05\nWald test            = 15.56  on 3 df,   p=0.001\nScore (logrank) test = 27.89  on 3 df,   p=4e-06,   Robust = 11.75  p=0.008\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\nImportantly, the strata of the Wei-Lin-Weissfeld model as set by `strata(enum)` are substantially different from the conditional strata of the Prentice-Williams-Peterson model. The `enum` variable is now no longer assumed to be an ordinal variable.\n\n#### Notes\n\n[**Note:**]{.underline} For all recurrent event models, another way of defining the subject clusters is by using `cluster(id)` in the formula, rather than setting `cluster = id`. This results in the same outcomes, as shown below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAG_v1 <- coxph(Surv(start, stop, event) ~ as.factor(rx) + number + size,\n            ties = \"breslow\",\n            cluster = id,\n            data = bladder2)\n\nsummary(AG_v1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(start, stop, event) ~ as.factor(rx) + number + \n    size, data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                   coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nas.factor(rx)2 -0.45979   0.63142  0.19996   0.25801 -1.782  0.07474 . \nnumber          0.17164   1.18726  0.04733   0.06131  2.799  0.00512 **\nsize           -0.04256   0.95833  0.06903   0.07555 -0.563  0.57317   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.6314     1.5837    0.3808     1.047\nnumber            1.1873     0.8423    1.0528     1.339\nsize              0.9583     1.0435    0.8264     1.111\n\nConcordance= 0.634  (se = 0.032 )\nLikelihood ratio test= 16.77  on 3 df,   p=8e-04\nWald test            = 11.76  on 3 df,   p=0.008\nScore (logrank) test = 18.57  on 3 df,   p=3e-04,   Robust = 11.44  p=0.01\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nAG_v2 <- coxph(Surv(start, stop, event) ~ as.factor(rx) + number + size + cluster(id),\n            ties = \"breslow\",\n            data = bladder2)\n\nsummary(AG_v2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(start, stop, event) ~ as.factor(rx) + number + \n    size, data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                   coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nas.factor(rx)2 -0.45979   0.63142  0.19996   0.25801 -1.782  0.07474 . \nnumber          0.17164   1.18726  0.04733   0.06131  2.799  0.00512 **\nsize           -0.04256   0.95833  0.06903   0.07555 -0.563  0.57317   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n               exp(coef) exp(-coef) lower .95 upper .95\nas.factor(rx)2    0.6314     1.5837    0.3808     1.047\nnumber            1.1873     0.8423    1.0528     1.339\nsize              0.9583     1.0435    0.8264     1.111\n\nConcordance= 0.634  (se = 0.032 )\nLikelihood ratio test= 16.77  on 3 df,   p=8e-04\nWald test            = 11.76  on 3 df,   p=0.008\nScore (logrank) test = 18.57  on 3 df,   p=3e-04,   Robust = 11.44  p=0.01\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\n[**Note:**]{.underline} R uses `ties = \"efron\"` by default, while SAS uses `ties = breslow` by default. In this tutorial, we forced R to use `ties = \"breslow\"` to match SAS for all recurrent event models. For more information, be sure to check the [CAMIS webpage](https://psiaims.github.io/CAMIS/Comp/r-sas_survival.html) on the comparison of Cox proportional hazards models in R and SAS.\n\n### Interpretation\n\nIn terms of interpretation, hazard ratios ($\\exp(\\beta_j)$) are often used when making inferences based on Cox proportional hazards models. Now, as you may remember from the overview presented earlier, it is important to recognize that each of the recurrent event models comes with a slightly different interpretation of the hazard ratio, as defined by the assumptions around the model.\n\n|   | **AG** | **PWPtt** | **PWPgt** | **WLW** |\n|---------------|---------------|---------------|---------------|---------------|\n| **Hazard ratio (HR)** | risk of any recurrence | risk of any recurrence | risk of recurrence after previous event | risk of event of any type, not necessarily recurrent event |\n\nThis means that, for the `bladder` data, we can draw slightly different conclusions on the hazard ratio of the group treated with thiotepa (**rx** = 2) versus the placebo group (**rx** = 1).\n\n| Model       | HR: rx2 vs rx1 | 95% CI         | P-value |\n|-------------|----------------|----------------|---------|\n| AG          | 0.631          | 0.381 to 1.047 | 0.0747  |\n| Original AG | 0.631          | 0.403 to 0.989 | 0.0447  |\n| PWPtt       | 0.716          | 0.487 to 1.053 | 0.0898  |\n| PWPgt       | 0.764          | 0.508 to 1.148 | 0.1952  |\n| WLW         | 0.560          | 0.309 to 1.015 | 0.0560  |\n\nThese conclusions are:\n\n-   **Andersen-Gill**: the risk of having *any new tumor recurrence* in the treatment group is 0.631 (0.381 - 1.047) times that of the placebo group\n\n-   **Prentice-Williams-Peterson: total time**: the risk of having *any new tumor recurrence* in the treatment group is 0.716 (0.487 - 1.053) times that of the placebo group\n\n-   **Prentice-Williams-Peterson: gap time**: the risk of having *a new tumor recurrence after a previous event* in the treatment group is 0.764 (0.508 - 1.148) times that of the placebo group\n\n-   **Wei-Lin-Weissfeld**: the risk of having *any type of event* in the treatment group is 0.560 (0.309 - 1.015) times that of the placebo group\n\n[**Note:**]{.underline} The improved Andersen-Gill model (LWYY model or proportional means/rates model) is preferred over the original Andersen-Gill model.\n\n### Event-specific estimates\n\nFor the Prentice-Williams-Peterson and Wei-Lin-Weissfeld models we can incorporate both overall ($\\beta$) and event-specific ($\\beta_j$) effects for each covariate. To arrive at pooled model parameters these models assume that $\\beta_1 = \\beta_2 = ... = \\beta_k = \\beta$. Until now, we have only considered pooled model parameters, but given the underlying stratification of these two models in particular, it may be valuable to look into the event-specific estimates as well ([Amorim & Cai 2015](https://pubmed.ncbi.nlm.nih.gov/25501468/)).\n\nTo output event-specific estimates for the treatment effect (**rx**), we simply specify `rx:strata(enum)` in the formula.\n\n#### Prentice-Williams-Peterson model\n\n**Total time model**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPWPtt_stratified <- coxph(Surv(start, stop, event) ~ rx:strata(enum) + number + size,\n                          ties = \"breslow\", cluster = id, data = bladder2)\nsummary(PWPtt_stratified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(start, stop, event) ~ rx:strata(enum) + \n    number + size, data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                           coef exp(coef)  se(coef) robust se      z Pr(>|z|)  \nnumber                 0.111071  1.117475  0.054397  0.050063  2.219   0.0265 *\nsize                  -0.006674  0.993349  0.073173  0.061409 -0.109   0.9135  \nrx:strata(enum)enum=1 -0.409893  0.663721  0.304293  0.286737 -1.430   0.1529  \nrx:strata(enum)enum=2 -0.416339  0.659457  0.398266  0.423632 -0.983   0.3257  \nrx:strata(enum)enum=3 -0.142970  0.866780  0.593818  0.405303 -0.353   0.7243  \nrx:strata(enum)enum=4  0.105362  1.111112  0.679095  0.469706  0.224   0.8225  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                      exp(coef) exp(-coef) lower .95 upper .95\nnumber                   1.1175     0.8949    1.0130     1.233\nsize                     0.9933     1.0067    0.8807     1.120\nrx:strata(enum)enum=1    0.6637     1.5067    0.3784     1.164\nrx:strata(enum)enum=2    0.6595     1.5164    0.2875     1.513\nrx:strata(enum)enum=3    0.8668     1.1537    0.3917     1.918\nrx:strata(enum)enum=4    1.1111     0.9000    0.4425     2.790\n\nConcordance= 0.609  (se = 0.033 )\nLikelihood ratio test= 6.73  on 6 df,   p=0.3\nWald test            = 8.22  on 6 df,   p=0.2\nScore (logrank) test = 7.02  on 6 df,   p=0.3,   Robust = 9.37  p=0.2\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\n**Gap time model**\n\nPWPgt_stratified \\<- coxph(Surv(gtime, event) \\~ rx:strata(enum) + number + size,\n\nties = \"breslow\", cluster = id, data = bladder2)\n\nsummary(PWPgt_stratified)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPWPgt_stratified <- coxph(Surv(gtime, event) ~ rx:strata(enum) + number + size,\n                          ties = \"breslow\", cluster = id, data = bladder2)\nsummary(PWPgt_stratified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(gtime, event) ~ rx:strata(enum) + number + \n    size, data = bladder2, ties = \"breslow\", cluster = id)\n\n  n= 178, number of events= 112 \n\n                          coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nnumber                 0.15193   1.16408  0.05259   0.04864  3.124  0.00179 **\nsize                   0.01319   1.01328  0.07021   0.06297  0.209  0.83406   \nrx:strata(enum)enum=1 -0.43665   0.64620  0.30521   0.28376 -1.539  0.12385   \nrx:strata(enum)enum=2 -0.30182   0.73947  0.39752   0.38907 -0.776  0.43789   \nrx:strata(enum)enum=3  0.01485   1.01497  0.47722   0.49843  0.030  0.97622   \nrx:strata(enum)enum=4  0.06019   1.06204  0.58289   0.53982  0.112  0.91122   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                      exp(coef) exp(-coef) lower .95 upper .95\nnumber                   1.1641     0.8590    1.0582     1.281\nsize                     1.0133     0.9869    0.8956     1.146\nrx:strata(enum)enum=1    0.6462     1.5475    0.3705     1.127\nrx:strata(enum)enum=2    0.7395     1.3523    0.3449     1.585\nrx:strata(enum)enum=3    1.0150     0.9853    0.3821     2.696\nrx:strata(enum)enum=4    1.0620     0.9416    0.3687     3.059\n\nConcordance= 0.603  (se = 0.032 )\nLikelihood ratio test= 9.73  on 6 df,   p=0.1\nWald test            = 14.45  on 6 df,   p=0.02\nScore (logrank) test = 10.49  on 6 df,   p=0.1,   Robust = 11.41  p=0.08\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\n#### Wei-Lin-Weissfeld model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWLW_stratified <- coxph(Surv(stop, event) ~ rx:strata(enum) + number + size,\n                        ties = \"breslow\", cluster = id, data = bladder)\nsummary(WLW_stratified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(stop, event) ~ rx:strata(enum) + number + \n    size, data = bladder, ties = \"breslow\", cluster = id)\n\n  n= 340, number of events= 112 \n\n                          coef exp(coef) se(coef) robust se      z Pr(>|z|)   \nnumber                 0.20747   1.23056  0.04685   0.06573  3.156   0.0016 **\nsize                  -0.05187   0.94945  0.06966   0.09300 -0.558   0.5770   \nrx:strata(enum)enum=1 -0.47890   0.61947  0.30583   0.28313 -1.691   0.0908 . \nrx:strata(enum)enum=2 -0.64914   0.52249  0.39217   0.36826 -1.763   0.0779 . \nrx:strata(enum)enum=3 -0.71783   0.48781  0.45971   0.42148 -1.703   0.0885 . \nrx:strata(enum)enum=4 -0.56175   0.57021  0.56143   0.49592 -1.133   0.2573   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                      exp(coef) exp(-coef) lower .95 upper .95\nnumber                   1.2306     0.8126    1.0818     1.400\nsize                     0.9494     1.0532    0.7912     1.139\nrx:strata(enum)enum=1    0.6195     1.6143    0.3556     1.079\nrx:strata(enum)enum=2    0.5225     1.9139    0.2539     1.075\nrx:strata(enum)enum=3    0.4878     2.0500    0.2135     1.114\nrx:strata(enum)enum=4    0.5702     1.7537    0.2157     1.507\n\nConcordance= 0.661  (se = 0.036 )\nLikelihood ratio test= 24.95  on 6 df,   p=3e-04\nWald test            = 16.54  on 6 df,   p=0.01\nScore (logrank) test = 28.19  on 6 df,   p=9e-05,   Robust = 11.92  p=0.06\n\n  (Note: the likelihood ratio and score tests assume independence of\n     observations within a cluster, the Wald and robust score tests do not).\n```\n\n\n:::\n:::\n\n\n\n## References\n\n[Amor 2023](https://www.lexjansen.com/phuse/2023/as/PAP_AS05.pdf). Eat, Sleep, R, Repeat.\n\n[Amorim & Cai 2015](https://pubmed.ncbi.nlm.nih.gov/25501468/). Modelling recurrent events: a tutorial for analysis in epidemiology. *International Journal of Epidemiology*. 2015 Feb;44(1):324-33.\n\n[Andersen & Gill 1982](https://www.jstor.org/stable/2240714). Cox’s Regression Model for Counting Processes: A Large Sample Study. *The Annals of Statistics*. 10(4):1100–1120.\n\n[bladder data](https://rdrr.io/cran/survival/man/bladder.html)\n\n[Lee et al. 2025](https://pubmed.ncbi.nlm.nih.gov/40490702/). Comparison of total event analysis and first event analysis in relation to heterogeneity in cardiovascular trials. *BMC Medical Research Methodology*. 2025 Jun 9;25(1):159.\n\n[Lin, Wei, Yang & Ying 2000](https://www.jstor.org/stable/2680616). Semiparametric regression for the mean and rate functions of recurrent events. *Journal of the Royal Statistical Society: Series B.* 62(4):711–730.\n\n[Lu & Shen 2018](https://www.lexjansen.com/pharmasug/2018/EP/PharmaSUG-2018-EP02.pdf). Application of Survival Analysis in Multiple Events Using SAS. *PharmaSUG 2018*.\n\n[Ozga et al. 2018](https://pubmed.ncbi.nlm.nih.gov/29301487/). A systematic comparison of recurrent event models for application to composite endpoints. *BMC Medical Research Methodology*. 2018 Jan 4;18(1):2.\n\n[Prentice, Williams & Peterson 1981](https://www.jstor.org/stable/2335582). On the Regression Analysis of Multivariate Failure Time Data. *Biometrika*. 68(2):373–379.\n\n[survival package](https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf)\n\n[Wei, Lin & Weissfeld 1989](https://www.jstor.org/stable/2290084). Regression Analysis of Multivariate Incomplete Failure Time Data by Modeling Marginal Distributions. *Journal of the American Statistical Association*. 84(408):1065–1073.\n\n::: {.callout-note collapse=\"true\" title=\"Session info\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.4.2 (2024-10-31)\n os       macOS Sequoia 15.6.1\n system   aarch64, darwin20\n ui       X11\n language (EN)\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Europe/London\n date     2025-08-29\n pandoc   3.4 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n ! package     * version date (UTC) lib source\n P BiocManager   1.30.25 2024-08-28 [?] CRAN (R 4.4.1)\n P cli           3.6.3   2024-06-21 [?] CRAN (R 4.4.0)\n P digest        0.6.37  2024-08-19 [?] CRAN (R 4.4.1)\n P dplyr       * 1.1.4   2023-11-17 [?] CRAN (R 4.4.0)\n P evaluate      1.0.0   2024-09-17 [?] CRAN (R 4.4.1)\n P fansi         1.0.6   2023-12-08 [?] CRAN (R 4.4.0)\n P fastmap       1.2.0   2024-05-15 [?] CRAN (R 4.4.0)\n P generics      0.1.3   2022-07-05 [?] CRAN (R 4.4.0)\n P glue          1.8.0   2024-09-30 [?] CRAN (R 4.4.1)\n P gt          * 0.11.1  2024-10-04 [?] CRAN (R 4.4.1)\n P htmltools     0.5.8.1 2024-04-04 [?] CRAN (R 4.4.0)\n P htmlwidgets   1.6.4   2023-12-06 [?] CRAN (R 4.4.0)\n P jsonlite      1.8.9   2024-09-20 [?] CRAN (R 4.4.1)\n   knitr         1.50    2025-03-16 [1] RSPM (R 4.4.0)\n   lattice       0.22-6  2024-03-20 [2] CRAN (R 4.4.2)\n P lifecycle     1.0.4   2023-11-07 [?] CRAN (R 4.4.0)\n P magrittr      2.0.3   2022-03-30 [?] CRAN (R 4.4.0)\n   Matrix        1.7-1   2024-10-18 [2] CRAN (R 4.4.2)\n P pillar        1.9.0   2023-03-22 [?] CRAN (R 4.4.0)\n P pkgconfig     2.0.3   2019-09-22 [?] CRAN (R 4.4.0)\n P R6            2.5.1   2021-08-19 [?] CRAN (R 4.4.0)\n   renv          1.0.10  2024-10-05 [1] CRAN (R 4.4.1)\n P rlang         1.1.4   2024-06-04 [?] CRAN (R 4.4.0)\n P rmarkdown     2.28    2024-08-17 [?] CRAN (R 4.4.0)\n P rstudioapi    0.16.0  2024-03-24 [?] CRAN (R 4.4.0)\n P sass          0.4.9   2024-03-15 [?] CRAN (R 4.4.0)\n P sessioninfo   1.2.2   2021-12-06 [?] CRAN (R 4.4.0)\n P survival    * 3.7-0   2024-06-05 [?] CRAN (R 4.4.0)\n P tibble        3.2.1   2023-03-20 [?] CRAN (R 4.4.0)\n P tidyselect    1.2.1   2024-03-11 [?] CRAN (R 4.4.0)\n P utf8          1.2.4   2023-10-22 [?] CRAN (R 4.4.0)\n P vctrs         0.6.5   2023-12-01 [?] CRAN (R 4.4.0)\n P withr         3.0.1   2024-07-31 [?] CRAN (R 4.4.0)\n   xfun          0.52    2025-04-02 [1] RSPM (R 4.4.0)\n P xml2          1.3.6   2023-12-04 [?] CRAN (R 4.4.0)\n P yaml          2.3.10  2024-07-26 [?] CRAN (R 4.4.0)\n\n [1] /Users/christinafillmore/Documents/GitHub/CAMIS/renv/library/macos/R-4.4/aarch64-apple-darwin20\n [2] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library\n\n P ── Loaded and on-disk path mismatch.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}