{
  "hash": "859f2601b50b8ddc83fcda0363baa68b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R vs SAS Wilcoxon Rank-Sum Test\"\n---\n\n\n\n\n\n## Introduction\n\nThis page compares the Wilcoxon rank-sum test, Hodges-Lehmann estimator, and estimation of the Mann-Whitney parameter in R and SAS.\n\n\n### Example Data\n\nFor this example we are using a dataset of birth weights for smoking and non-smoking mothers (*Data source: Table 30.4, Kirkwood BR. and Sterne JAC. Essentials of medical statistics. Second Edition. ISBN 978-0-86542-871-3*). This dataset is both small (so an exact test is recommended) and has ties in it.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_ns <- c(3.99, 3.89, 3.6, 3.73, 3.31, \n            3.7, 4.08, 3.61, 3.83, 3.41, \n            4.13, 3.36, 3.54, 3.51, 2.71)\nbw_s <- c(3.18, 2.74, 2.9, 3.27, 3.65, \n           3.42, 3.23, 2.86, 3.6, 3.65, \n           3.69, 3.53, 2.38, 2.34)\n\nsmk_data <- data.frame(\n  value = c(bw_ns, bw_s), \n  smoke = as.factor(rep(c(\"non\", \"smoke\"), c(length(bw_ns), length(bw_s))))\n) \n# Relevel the factors to make it smoker - non-smokers \nsmk_data$smoke <- forcats::fct_relevel(smk_data$smoke, \"smoke\")\nhead(smk_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  value smoke\n1  3.99   non\n2  3.89   non\n3  3.60   non\n4  3.73   non\n5  3.31   non\n6  3.70   non\n```\n\n\n:::\n:::\n\n\n\nTo view the code implementations, see the [SAS](../SAS/ranksum.qmd) and [R](../R/nonpara_wilcoxon_ranksum.qmd) pages, respectively.\n\n\n## Comparison\n\n### Software Capabilities\n\nThe following table provides an overview of the supported analyses between R and SAS. A specific comparison of the results and whether they match are provided below.\n\n| Analysis | Supported in R {stats} | Supported in R {coin} | Supported in R {asht} | Supported in SAS | Notes |\n|----------|------------------------|-----------------------|-----------------------|------------------|-------|\n| Wilcoxon Rank-Sum -- Normal approximation **with** continuity correction | Yes | No | Yes | Yes | In {coin}, one can add `correct=TRUE`, but note that no error is given and the results of a normal approximation approach **without** continuity correction are provided.\n| Wilcoxon Rank-Sum -- Normal approximation **without** continuity correction | Yes | Yes | Yes | Yes |\n| Wilcoxon Rank-Sum -- Exact | Partly | Yes | Partly | Yes | In {stats}, one can only do the exact method when no ties are present.; In {asht}, exact test is possible but the run time is long for larger sample size.\n| Wilcoxon Rank-Sum -- Approximative (Monte Carlo simulation) | No | Yes | Yes | No |\n| Hodges-Lehmann estimator -- Asymptotic | Yes | No | No | Yes |\n| Hodges-Lehmann estimator -- Exact | Partly | Yes | No | Yes | In {stats}, one can only do the exact method when no ties are present.\n| Hodges-Lehmann estimator -- Approximative (Monte Carlo simulation) | No | Yes | No | No |\n| Mann-Whitney parameter | No | No | Yes | No | In {asht}, confidence intervals can be obtained using asymptotic approximation, Monte Carlo simulations, or exact methods (for small sample size)\n\n\n### Wilcoxon Rank Sum test\n\nIn the below table the p-values of the Wilcoxon Rank Sum Test with different options are compared.\n\n| Analysis | R {stats} | R {coin} | R {asht} | SAS | Match | Notes |\n|----------|-----------|----------|----------|-----|-------|-------|\n| Wilcoxon Rank-Sum -- Normal approximation **with** continuity correction | 0.0100 | / | 0.0100 | 0.0100 | Yes | Not possible with {coin}\n| Wilcoxon Rank-Sum -- Normal approximation **without** continuity correction | 0.0094 | 0.0094 | 0.0094 | 0.0094 | Yes | \n| Wilcoxon Rank-Sum -- Exact | / | 0.0082 | / | 0.0082 | Yes | Not possible with {stats} since there are ties.; In {asht} run-time very long. \n| Wilcoxon Rank-Sum -- Approximative (Monte Carlo simulation) | / | 0.0083 | 0.0083 | / | Yes | With 100,000 simulations\n\n\n### Hodges-Lehmann estimator\n\nIn the below table the Hodges-Lehmann estimate and 95% confidence intervals are compared.\n\n| Analysis | R {stats} | R {coin} | R {asht} | SAS | Match | Notes |\n|----------|-----------|----------|----------|-----|-------|-------|\n| Hodges-Lehmann estimator -- Asymptotic | -0.426 (-0.770 to -0.090) | -0.426 (-0.760 to -0.100) | / | -0.425 (-0.770 to -0.090) | No | In {coin}, the CI is the exact CI. The CIs match between {stats} and SAS.\n| Hodges-Lehmann estimator -- Exact | / | -0.425 (-0.760 to -0.100) | / | -0.425 (-0.760 to -0.100) | Yes | Not possible with {stats} since there are ties; In {asht} run-time very long.\n| Hodges-Lehmann estimator -- Approximative (Monte Carlo simulation) | / | -0.425 (-0.760 to -0.100) | / | /| / | With 500,000 simulations\n\n\n### Mann-Whitney Parameter\nThe estimation of the Mann-Whitney parameter is only possible in R `asht` package.\n\n\n\n## Special considerations for one-sided p-values\n\nIt is important to note that in SAS you can get an *unexpected* one-sided p-value. In the SAS documentation for [PROC NPAR1WAY](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_npar1way_details04.htm) it is stated that: \n\n*\"PROC NPAR1WAY computes one-sided and two-sided asymptotic p-values for each two-sample linear rank test. When the test statistic z is greater than its null hypothesis expected value of 0, PROC NPAR1WAY computes the right-sided p-value, which is the probability of a larger value of the statistic occurring under the null hypothesis. When the test statistic is less than or equal to 0, PROC NPAR1WAY computes the left-sided p-value, which is the probability of a smaller value of the statistic occurring under the null hypothesis\"* (similar for the exact p-value). \n\nThus SAS reports the one-sided p-value in the direction of the test statistic. This can cause an *unexpected* one-sided p-value, if your data provides a test statistic in the other direction of the pre-specified one-sided hypothesis.\n\nConsider the following data example to showcase this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_used <- data.frame(\n  ID = c(\"001\", \"002\", \"003\", \"004\", \"005\", \"006\", \"007\", \"008\", \"009\", \"010\",\n         \"011\", \"012\", \"013\", \"014\", \"015\", \"016\", \"017\", \"018\", \"019\", \"020\",\n         \"021\", \"022\", \"023\", \"024\", \"025\", \"026\", \"027\", \"028\", \"029\", \"030\"),\n  ARM = c(\"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\", \"Placebo\",\n          \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\", \"Low\",\n          \"High\", \"High\", \"High\", \"High\", \"High\", \"High\", \"High\", \"High\", \"High\", \"High\"),\n  Y = c(8.5, 8.9, 8.2, 8.1, 7.1, 7.4, 6.0, 6.5, 7.0, 7.0,\n        6.5, 9.4, 8.9, 8.8, 9.6, 8.3, 8.9, 7.0, 9.1, 6.9,\n        8.0, 7.3, 7.1, 6.2, 4.7, 4.7, 4.2, 4.1, 3.4, 3.9)\n)\ndat_used\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    ID     ARM   Y\n1  001 Placebo 8.5\n2  002 Placebo 8.9\n3  003 Placebo 8.2\n4  004 Placebo 8.1\n5  005 Placebo 7.1\n6  006 Placebo 7.4\n7  007 Placebo 6.0\n8  008 Placebo 6.5\n9  009 Placebo 7.0\n10 010 Placebo 7.0\n11 011     Low 6.5\n12 012     Low 9.4\n13 013     Low 8.9\n14 014     Low 8.8\n15 015     Low 9.6\n16 016     Low 8.3\n17 017     Low 8.9\n18 018     Low 7.0\n19 019     Low 9.1\n20 020     Low 6.9\n21 021    High 8.0\n22 022    High 7.3\n23 023    High 7.1\n24 024    High 6.2\n25 025    High 4.7\n26 026    High 4.7\n27 027    High 4.2\n28 028    High 4.1\n29 029    High 3.4\n30 030    High 3.9\n```\n\n\n:::\n:::\n\n\n\nSuppose we would have the following two hypothesis, where for both Low Dose and High Dose we expect smaller values (Y) than Placebo:\n\n- $H_{0}$: No difference between Placebo and Low Dose, vs $H_{1}$: Placebo has higher values (Y) than Low Dose\n\n- $H_{0}$: No difference between Placebo and High Dose, vs $H_{1}$: Placebo has higher values (Y) than High Dose\n\n\n### Asymptotic results without continuity correction\n\n**Placebo and High Dose group**\n\nLet us the {coin} package in R to compare the Placebo and High Dose group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: greater implies that H1 is Y1 - Y2 = Placebo - High > 0\ncoin::wilcox_test(\n  Y ~ factor(ARM, levels = c(\"Placebo\", \"High\")),\n  distribution = \"asymptotic\",\n  alternative = \"greater\",\n  data = dat_used %>% dplyr::filter(ARM %in% c(\"Placebo\", \"High\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic Wilcoxon-Mann-Whitney Test\n\ndata:  Y by\n\t factor(ARM, levels = c(\"Placebo\", \"High\")) (Placebo, High)\nZ = 2.5352, p-value = 0.005619\nalternative hypothesis: true mu is greater than 0\n```\n\n\n:::\n:::\n\n\n\nIn SAS, the following results is obtained. As can be seen in both R and SAS the one-sided p-value is 0.0056.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/ranksum/SAS_one_sided_pvalue.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n**Placebo and Low Dose group**\n\nLet us the {coin} package in R to compare the Placebo and Low Dose group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: greater implies that H1 is Y1 - Y2 = Placebo - High > 0\ncoin::wilcox_test(\n  Y ~ factor(ARM, levels = c(\"Placebo\", \"Low\")),\n  distribution = \"asymptotic\",\n  alternative = \"greater\",\n  data = dat_used %>% dplyr::filter(ARM %in% c(\"Placebo\", \"Low\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic Wilcoxon-Mann-Whitney Test\n\ndata:  Y by\n\t factor(ARM, levels = c(\"Placebo\", \"Low\")) (Placebo, Low)\nZ = -1.7066, p-value = 0.9561\nalternative hypothesis: true mu is greater than 0\n```\n\n\n:::\n:::\n\n\n\nIn SAS, the following results is obtained. The one-sided p-values clearly do not match ({coin} p-value = 0.9561; SAS p-value = 0.0439). As mentioned above, SAS reports the p-value in the direction of the test statistic. This can cause an *unexpected* one-sided p-value, if your data provides a test statistic in the other directiont than the pre-specified one-sided hypothesis. Do note that $1 - 0.9561 = 0.0439$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/ranksum/SAS_one_sided_pvalue2.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n### Exact results\n\n**Placebo and High Dose group**\n\nLet us the {coin} package in R to compare the Placebo and High Dose group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: greater implies that H1 is Y1 - Y2 = Placebo - High > 0\ncoin::wilcox_test(\n  Y ~ factor(ARM, levels = c(\"Placebo\", \"High\")),\n  distribution = \"exact\",\n  alternative = \"greater\",\n  data = dat_used %>% dplyr::filter(ARM %in% c(\"Placebo\", \"High\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact Wilcoxon-Mann-Whitney Test\n\ndata:  Y by\n\t factor(ARM, levels = c(\"Placebo\", \"High\")) (Placebo, High)\nZ = 2.5352, p-value = 0.004682\nalternative hypothesis: true mu is greater than 0\n```\n\n\n:::\n:::\n\n\n\nIn SAS (see above), the same one-sided p-value of 0.0047 is obtained.\n\n\n**Placebo and Low Dose group**\n\nLet us the {coin} package in R to compare the Placebo and Low Dose group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: greater implies that H1 is Y1 - Y2 = Placebo - High > 0\ncoin::wilcox_test(\n  Y ~ factor(ARM, levels = c(\"Placebo\", \"Low\")),\n  distribution = \"exact\",\n  alternative = \"greater\",\n  data = dat_used %>% dplyr::filter(ARM %in% c(\"Placebo\", \"Low\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact Wilcoxon-Mann-Whitney Test\n\ndata:  Y by\n\t factor(ARM, levels = c(\"Placebo\", \"Low\")) (Placebo, Low)\nZ = -1.7066, p-value = 0.9574\nalternative hypothesis: true mu is greater than 0\n```\n\n\n:::\n:::\n\n\n\nPlease see above for the SAS result. The one-sided p-values clearly do not match ({coin} p-value = 0.9574; SAS p-value = 0.0455).\n\n\n\n## Summary and Recommendation\n\nWilcoxon Rank Sum test and the associated Hodges-Lehmann CI are able to be consistently computed in both SAS and R. The user needs to be aware of some small differences:\n\n- In SAS the `exact wilcoxon hl` statement is needed to get both the exact p-value and CI.\n\n- In {stats} exact values are only possible when there are no ties and the exact parameter is set to true (`exact = TRUE`). This will give the exact p-value and CI.\n\n- In {coin} it is not possible to do a normal approximation **with** continuity correction.\n\n- For the asymptotic Hodges-Lehmann estimator, {stats} and {coin} use an algorithm to define the estimate, whereas SAS provides the *traditional* Hodges-Lehmann estimator. \n\nIf you have a study where you would like to use R for the exact Wilcoxon Rank Sum test and there is the risk of ties, {coin} would be recommended.\n\n\n\n## Ties\n\nIn all presented R packages and SAS, when there are tied values, the average score method (mid-ranks) is used. This is done by first sorting the observations in ascending order and assigning ranks as if there were no ties. The procedure averages the scores for tied observations and assigns this average score to each of the tied observations. Thus, all tied data values have the same score value.\n\n\n## Additional References\n\nProvided are references and additional reading materials for both R and SAS documentation related to the analysis.\n\n**R Documentation:**\n\n-   `wilcox.test` function: <https://rdrr.io/r/stats/wilcox.test.html>\n\n-   `wilcox_test` function: <https://rdrr.io/cran/coin/man/LocationTests.html>\n\n**SAS Documentation:**\n\n-   `PROC npar1way`: <https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_npar1way_gettingstarted.htm>\n\n::: {.callout-note collapse=\"true\" title=\"Session Info\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.4.2 (2024-10-31)\n os       macOS Sequoia 15.6.1\n system   aarch64, darwin20\n ui       X11\n language (EN)\n collate  en_US.UTF-8\n ctype    en_US.UTF-8\n tz       Europe/London\n date     2025-10-13\n pandoc   3.4 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n ! package * version date (UTC) lib source\n P coin    * 1.4-3   2023-09-27 [?] CRAN (R 4.4.0)\n\n [1] /Users/christinafillmore/Documents/GitHub/CAMIS/renv/library/macos/R-4.4/aarch64-apple-darwin20\n [2] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library\n\n P ── Loaded and on-disk path mismatch.\n\n─ External software ──────────────────────────────────────────────────────────\n setting value\n SAS     9.04.01M7P080520\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}