---
title: "R vs SAS - Estimating Cumulative Incidence Functions"
---

# Comparison of R and SAS

The following table shows the options available in R and SAS for estimating cumulative incidence functions (CIFs) in a competing risk analysis, especially the capabilities and whether the results match.

| Analysis                                                            | Supported in R package `tidycmprsk`                                                            | Supported in SAS `PROC LIFETEST`                        | Results Match |
|--------------------|------------------|------------------|------------------|
| CIF estimates                                                       | Yes: with function `cuminc()`                                                                  | Yes: with `eventcode` option in `TIME` statement        | Yes           |
| Gray's test for equality across groups                              | Yes: default when the group variable (a factor) is on the right-hand side of the input formula | Yes: default with `strata` statement                    | Yes           |
| Variance estimates for the CIF estimates using Aalen (1978)         | Yes: default                                                                                   | Yes (default)                                           | Yes           |
| Variance estimates for the CIF estimates using the delta method     | No                                                                                             | Yes: with option `error=delta` in `PROC TEST` statement | N/A           |
| Confidence intervals for CIF estimates using log-log transformation | Yes: default                                                                                   | Yes: default                                            | Yes           |
| Confidence intervals for CIF estimates using other transformations  | No                                                                                             | Yes: with `conftype` option in `LIFETEST` statement     | N/A           |
| CIF estimates for specified time points                             | Yes: with `times` option when summarizing results, e.g., using `tidy()`                        | Yes: with `timelist` option in `LIFETEST` statement     | Yes           |
| CIF plot by groups                                                  | Yes: with `ggsurvfit::ggcumin()`                                                               | Yes: with `plots=cif` option in `LIFETEST` statement    | N/A           |

Additional details for using `tidycmprsk` are given [here](https://psiaims.github.io/CAMIS/R/survival_cif.html "cif in r") and for SAS `PROC LIFETEST` [here](https://psiaims.github.io/CAMIS/SAS/survival_cif.html "cif in sas") .


::: {.callout-note collapse="true" title="Session Info"}
```{r}
#| echo: false
si <- sessioninfo::session_info(
 c("cmprsk", "tidycmprsk", "survival"), #Vector of packages used 
 dependencies = FALSE)
si$external <- structure(list("SAS" = "9.04.01M7P080520"), class = c("external_info", "list"))
si
```
:::

# References

[SAS PROC LIFETEST Documentation on CIF estimates](https://documentation.sas.com/doc/en/statug/15.2/statug_lifetest_details25.htm#statug.lifetest.lftcifest "cif in sas")

[R package 'tidycmprsk' Documentation](https://github.com/MSKCC-Epi-Bio/tidycmprsk "cif in r")
