<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R vs SAS: Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-ebfcb0ed0ac0539375ffcf22e0e9fa78.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/logo.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../contribution/contribution.html"> 
<span class="menu-text">Contribute</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-publications-and-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Publications and projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-publications-and-projects">    
        <li>
    <a class="dropdown-item" href="../publication/white_paper.html">
 <span class="dropdown-text">White paper</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../publication/conference.html">
 <span class="dropdown-text">Conferences</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../publication/dissertation.html">
 <span class="dropdown-text">Academic projects</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-news" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">News</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-news">    
        <li>
    <a class="dropdown-item" href="../minutes/index.html">
 <span class="dropdown-text">Meeting minutes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../blogs/index.html">
 <span class="dropdown-text">Blogs</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/PSIAIMS/CAMIS/">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/PSIAIMS/CAMIS/issues/">
            Report a Difference
            </a>
          </li>
      </ul>
    </div>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#goal" id="toc-goal" class="nav-link" data-scroll-target="#goal">Goal</a></li>
  <li><a href="#scope" id="toc-scope" class="nav-link" data-scroll-target="#scope">Scope</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">Findings</a></li>
  </ul></li>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites</a>
  <ul class="collapse">
  <li><a href="#r-packages" id="toc-r-packages" class="nav-link" data-scroll-target="#r-packages">R packages</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#logistic-regressions" id="toc-logistic-regressions" class="nav-link" data-scroll-target="#logistic-regressions">Logistic regressions</a></li>
  <li><a href="#g-computation" id="toc-g-computation" class="nav-link" data-scroll-target="#g-computation">g-computation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#logistic-regression-1" id="toc-logistic-regression-1" class="nav-link" data-scroll-target="#logistic-regression-1">Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#parameterisation-comparison" id="toc-parameterisation-comparison" class="nav-link" data-scroll-target="#parameterisation-comparison">Parameterisation Comparison</a></li>
  <li><a href="#sec-num-comp" id="toc-sec-num-comp" class="nav-link" data-scroll-target="#sec-num-comp">Numerical Comparison</a>
  <ul class="collapse">
  <li><a href="#glm-in-r" id="toc-glm-in-r" class="nav-link" data-scroll-target="#glm-in-r"><code>glm</code> in R</a></li>
  <li><a href="#proc-logistic-in-sas-without-firth-option" id="toc-proc-logistic-in-sas-without-firth-option" class="nav-link" data-scroll-target="#proc-logistic-in-sas-without-firth-option"><code>PROC LOGISTIC</code> in SAS (without firth option)</a></li>
  <li><a href="#comment-on-model-selection" id="toc-comment-on-model-selection" class="nav-link" data-scroll-target="#comment-on-model-selection">Comment on model selection</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#firth-logistic-regression-1" id="toc-firth-logistic-regression-1" class="nav-link" data-scroll-target="#firth-logistic-regression-1">Firth logistic regression</a>
  <ul class="collapse">
  <li><a href="#parameterisation-comparison-1" id="toc-parameterisation-comparison-1" class="nav-link" data-scroll-target="#parameterisation-comparison-1">Parameterisation Comparison</a></li>
  <li><a href="#numerical-comparison" id="toc-numerical-comparison" class="nav-link" data-scroll-target="#numerical-comparison">Numerical Comparison</a>
  <ul class="collapse">
  <li><a href="#logistf-in-r" id="toc-logistf-in-r" class="nav-link" data-scroll-target="#logistf-in-r"><code>logistf</code> in R</a></li>
  <li><a href="#proc-logistic-in-sas-with-firth-option" id="toc-proc-logistic-in-sas-with-firth-option" class="nav-link" data-scroll-target="#proc-logistic-in-sas-with-firth-option"><code>PROC LOGISTIC</code> in SAS (with firth option)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#g-computation-with-covariate-adjustment-1" id="toc-g-computation-with-covariate-adjustment-1" class="nav-link" data-scroll-target="#g-computation-with-covariate-adjustment-1">g-computation with covariate adjustment</a>
  <ul class="collapse">
  <li><a href="#numerical-comparison-1" id="toc-numerical-comparison-1" class="nav-link" data-scroll-target="#numerical-comparison-1">Numerical Comparison</a>
  <ul class="collapse">
  <li><a href="#get_marginal_effect-in-r" id="toc-get_marginal_effect-in-r" class="nav-link" data-scroll-target="#get_marginal_effect-in-r"><code>get_marginal_effect</code> in R</a></li>
  <li><a href="#margins-macro-in-sas" id="toc-margins-macro-in-sas" class="nav-link" data-scroll-target="#margins-macro-in-sas"><code>%Margins</code> macro in SAS</a></li>
  <li><a href="#lr-macro-in-sas-ge-et-al-2011" id="toc-lr-macro-in-sas-ge-et-al-2011" class="nav-link" data-scroll-target="#lr-macro-in-sas-ge-et-al-2011"><code>%LR</code> macro in SAS (Ge et al, 2011)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#final-remarks" id="toc-final-remarks" class="nav-link" data-scroll-target="#final-remarks">Final remarks</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R vs SAS: Logistic Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="summary" class="level1">
<h1>Summary</h1>
<section id="goal" class="level2">
<h2 class="anchored" data-anchor-id="goal">Goal</h2>
<p>Comparison of results between SAS vs R for different applications of logistic regression; where possible we try to ensure the same statistical method or algorithm is specified. However, there are some underlying differences between the algorithms in SAS vs R that cannot be (at least not easily) “tweaked”. The document also provides some remarks on what parameters to look out for and what could have caused the numerical differences.</p>
</section>
<section id="scope" class="level2">
<h2 class="anchored" data-anchor-id="scope">Scope</h2>
<div class="columns">
<div class="column" style="width:45%;">
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Methodologies
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Logistic regression</li>
<li>Firth’s bias-reduced logistic regression</li>
<li>g-computation / standardization with covariate adjustment</li>
</ul>
</div>
</div>
</div>
</div><div class="column" style="width:55%;">
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Technical implementations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>SAS: <code>PROC LOGISTIC</code> (with and without firth option) and <code>%margins</code> macro<br>
</li>
<li>R: <code>stats::glm</code>, <code>logistf::logistf</code> and <code>beeca::get_marginal_effect</code></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<p>Below are summary of findings from a numerical comparison using example data, where possible we specify the same algorithm in R and SAS.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Logistic regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Maximum Likelihood Estimates and p-values for the Model Parameters have an exact match (at 0.001 level) using <code>glm</code> in R vs <code>PROC LOGISTIC</code> procedure (without Firth option) in SAS.</p>
<p>When using GLM parameterization (see <a href="https://psiaims.github.io/CAMIS/SAS/logistic-regr.html">SAS page</a> for explanation of parameterization types), the parameters estimates (and 95% CIs) can be exponentiated to provide odds ratios and 95% CIs for odds ratios.</p>
<p>An exact match (at 0.001 level) is obtained for the Odds ratios and CIs when the same method is used, however SAS Proc Logistic can only calculate Wald CI’s. Profile likelihood CIs are not available.</p>
<p>R using glm() function, can use the confint() function to calculate CI’s using the profile likelihood method or the confint.default() function to calculate CIs using the Wald method.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Firth logistic regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Exact match cannot be obtained for all estimates using <code>logistf</code> vs <code>PROC LOGISTIC</code> procedure (with Firth option). More specifically:<br>
- Coefficient estimate and 95% CI matched at 0.001 level;<br>
- Standard error are not the same (e.g., 0.02023 for age in R vs 0.02065 in SAS);<br>
- p-value is not the same (0.6288 in R for age vs 0.6348 in SAS);<br>
</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
g-computation with covariate adjustment
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Exact match (at 0.001 level) can be obtained using <code>get_marginal_effect</code> in R vs <code>%margins</code> macro in SAS.</p>
</div>
</div>
</div>
<p>In the following sections, the parameterisation of logistic regression implementation (with an without Firth option) will be compared followed by numerical comparison using example data.</p>
</section>
</section>
<section id="prerequisites" class="level1">
<h1>Prerequisites</h1>
<section id="r-packages" class="level2">
<h2 class="anchored" data-anchor-id="r-packages">R packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr hidden">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival) <span class="co"># for example data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(logistf) <span class="co"># for firth regression</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(beeca) <span class="co"># for covariate adjustment</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="logistic-regressions" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regressions">Logistic regressions</h3>
<p>We use the <code>lung</code> dataset provided with {survival} R package. Initial data preparation involves generating a new binary outcome based on the weight change.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the lung dataset is available in ./data/lung_cancer.csv</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>lung2 <span class="ot">&lt;-</span> survival<span class="sc">::</span>lung <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">wt_grp =</span> <span class="fu">factor</span>(wt.loss <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"weight loss"</span>, <span class="st">"weight gain"</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  ) </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(lung2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 228
Columns: 11
$ inst      &lt;dbl&gt; 3, 3, 3, 5, 1, 12, 7, 11, 1, 7, 6, 16, 11, 21, 12, 1, 22, 16…
$ time      &lt;dbl&gt; 306, 455, 1010, 210, 883, 1022, 310, 361, 218, 166, 170, 654…
$ status    &lt;dbl&gt; 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
$ age       &lt;dbl&gt; 74, 68, 56, 57, 60, 74, 68, 71, 53, 61, 57, 68, 68, 60, 57, …
$ sex       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, …
$ ph.ecog   &lt;dbl&gt; 1, 0, 0, 1, 0, 1, 2, 2, 1, 2, 1, 2, 1, NA, 1, 1, 1, 2, 2, 1,…
$ ph.karno  &lt;dbl&gt; 90, 90, 90, 90, 100, 50, 70, 60, 70, 70, 80, 70, 90, 60, 80,…
$ pat.karno &lt;dbl&gt; 100, 90, 90, 60, 90, 80, 60, 80, 80, 70, 80, 70, 90, 70, 70,…
$ meal.cal  &lt;dbl&gt; 1175, 1225, NA, 1150, NA, 513, 384, 538, 825, 271, 1025, NA,…
$ wt.loss   &lt;dbl&gt; NA, 15, 15, 11, 0, 0, 10, 1, 16, 34, 27, 23, 5, 32, 60, 15, …
$ wt_grp    &lt;fct&gt; NA, weight gain, weight gain, weight gain, weight loss, weig…</code></pre>
</div>
</div>
</section>
<section id="g-computation" class="level3">
<h3 class="anchored" data-anchor-id="g-computation">g-computation</h3>
<p>We use the <code>trial01</code> dataset provided with {beeca} R package. Initial data preparation involves setting the treatment indicator as a categorical variable and removing any incomplete cases.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"trial01"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>trial01<span class="sc">$</span>trtp <span class="ot">&lt;-</span> <span class="fu">factor</span>(trial01<span class="sc">$</span>trtp) <span class="do">## set treatment to a factor</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>trial01 <span class="ot">&lt;-</span> trial01 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(aval)) <span class="do">## remove missing data i.e complete cases analysis</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># save the dataset to be imported in SAS</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># write.csv(trial01, file = "data/trial01.csv", na = ".")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="logistic-regression-1" class="level1">
<h1>Logistic Regression</h1>
<section id="parameterisation-comparison" class="level2">
<h2 class="anchored" data-anchor-id="parameterisation-comparison">Parameterisation Comparison</h2>
<p>The following set of tables compare how to configure particular parameters / attributes of the methodologies.</p>
<div id="tbl-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Standard Logistic Regression in SAS vs R
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">SAS <br> <code>PROC LOGISTIC</code></th>
<th style="text-align: center;">R <br><code>stats::glm</code></th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Likelihood optimization algorithm</td>
<td style="text-align: center;">Default</td>
<td style="text-align: center;">Default</td>
<td style="text-align: left;">Fisher’s scoring method (i.e., iteratively reweighted least squares (IRLS))</td>
<td style="text-align: left;">For logistic regression, parameter estimates and covariance matrices estimated should be the same for both Fisher’s and Newton-Raphson algorithm for maximum likelihood.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Convergence criteria</td>
<td style="text-align: center;">Default</td>
<td style="text-align: center;">NA</td>
<td style="text-align: left;">Specifies relative gradient convergence criterion (GCONV=1E–8)</td>
<td style="text-align: left;">In<code>PROC LOGISTIC</code> there are three other convergence criteria which can be specified. However, there is no exact criterion that matches the criteria in <code>stats::glm</code>.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Convergence criteria</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">Default</td>
<td style="text-align: left;">Specifies relative difference between deviance &lt; 1E–8.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Confidence interval (CI) estimation method</td>
<td style="text-align: center;">Default</td>
<td style="text-align: center;"><code>confint.default()</code></td>
<td style="text-align: left;">Wald CI</td>
<td style="text-align: left;">In <code>stats::glm</code> in R, function confint.default() gives the Wald confidence limits; whereas function confint() gives the profile-likelihood limits.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Hypothesis tests for regression coefficients</td>
<td style="text-align: center;">Default</td>
<td style="text-align: center;">Default</td>
<td style="text-align: left;">Wald tests, which are based on estimates for the regression coefficients and its corresponding standard error.</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-num-comp" class="level2">
<h2 class="anchored" data-anchor-id="sec-num-comp">Numerical Comparison</h2>
<p>Every effort is made to ensure that the R code employs estimation methods/ optimization algorithms/ other components that closely match (as much as possible) those used in the SAS code.</p>
<section id="glm-in-r" class="level3">
<h3 class="anchored" data-anchor-id="glm-in-r"><code>glm</code> in R</h3>
<p>Note, the default fitting method in <code>glm</code> is consistent with the default fitting method in <code>PROC LOGISTIC</code> procedure.</p>
<ul>
<li>Default fitting method in <code>glm</code> is iteratively reweighted least squares, and the documentation can be found <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/glm">here</a>.</li>
<li>Default fitting method for <code>PROC LOGISTIC</code> procedure is Fisher’s scoring method, which is reported as part of the SAS default output, and it is equivalent to “Iteratively reweighted least squares” method as reported in this <a href="https://support.sas.com/documentation/cdl/en/statug/63347/HTML/default/viewer.htm#statug_logistic_sect033.htm">documentation</a>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># stats::glm function</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(wt_grp <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal, <span class="at">data =</span> lung2, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span><span class="st">"logit"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># model coefficients summary</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate   Std. Error    z value   Pr(&gt;|z|)
(Intercept)  3.2631672833 1.6488206996  1.9790917 0.04780569
age         -0.0101717451 0.0208107243 -0.4887742 0.62500157
sex         -0.8717357187 0.3714041991 -2.3471348 0.01891841
ph.ecog      0.4179665342 0.2588653214  1.6146100 0.10639518
meal.cal    -0.0008869427 0.0004467405 -1.9853642 0.04710397</code></pre>
</div>
</div>
<p>Note, function <code>confint.default</code> gives the Wald confidence limits, which is the default option in SAS <code>PROC LOGISTIC</code> procedure; whereas <code>confint</code> gives the profile-likelihood limits. Conditional odds ratio is calculated by taking the exponential of the model parameters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">est =</span> <span class="fu">coef</span>(m1), </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">confint.default</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      est        2.5 %        97.5 %
(Intercept)  3.2631672833  0.031538095  6.494796e+00
age         -0.0101717451 -0.050960015  3.061653e-02
sex         -0.8717357187 -1.599674572 -1.437969e-01
ph.ecog      0.4179665342 -0.089400173  9.253332e-01
meal.cal    -0.0008869427 -0.001762538 -1.134731e-05</code></pre>
</div>
</div>
</section>
<section id="proc-logistic-in-sas-without-firth-option" class="level3">
<h3 class="anchored" data-anchor-id="proc-logistic-in-sas-without-firth-option"><code>PROC LOGISTIC</code> in SAS (without firth option)</h3>
<div class="cell">
<pre class="sas cell-code"><code>PROC LOGISTIC DATA=LUNG2; # import lung
    MODEL WT_GRP(EVENT="weight_gain") = AGE SEX PH_ECOG MEAL_CAL;
    ods output ESTIMATEs=estimates;
run;</code></pre>
</div>
<p>Below is screenshot of output tables summarizing coefficient estimates and confidence intervals</p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/logistic_regression/sas_logistic_estimates.png" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/logistic_regression/sas_logistic_ci.png" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
</section>
<section id="comment-on-model-selection" class="level3">
<h3 class="anchored" data-anchor-id="comment-on-model-selection">Comment on model selection</h3>
<p>As indicated in <a href="https://psiaims.github.io/CAMIS/R/logistic_regr.html">Logistic regression in R</a> and <a href="https://psiaims.github.io/CAMIS/SAS/logistic-regr.html">Logistic regression in SAS</a>, the chi-Sq test statistics and p-values are different when performing model selections in R vs.&nbsp;SAS. The reason for this discrepancy is that the chi-Sq statistics from <code>anova()</code> in R is based on deviance test using residual deviance while the chi-Sq statistics from <code>PROC LOGISTIC</code> w/ <code>SELECTION</code> option in SAS is based on Wald test using z-values squared.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conclusion for logistic regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Exact match (at 0.001 level) can be obtained using <code>glm</code> in R vs <code>PROC LOGISTIC</code> procedure (without Firth option) in SAS, for coefficient estimates, 95% CI, and for p-value.</p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="firth-logistic-regression-1" class="level1">
<h1>Firth logistic regression</h1>
<p>The following set of tables compare how to configure particular parameters / attributes of the methodologies.</p>
<section id="parameterisation-comparison-1" class="level2">
<h2 class="anchored" data-anchor-id="parameterisation-comparison-1">Parameterisation Comparison</h2>
<div id="tbl-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Firth’s Bias-Reduced Logistic Regression in SAS vs R
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: left;">SAS <br> <code>PROC LOGISTIC</code> w/ Firth option</th>
<th style="text-align: left;">R <br><code>logistf::logistf</code></th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Likelihood optimization algorithm</td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;"><code>control =</code><br><code>logistf.control</code> <br><code>(fit =“IRLS”)</code></td>
<td style="text-align: left;">Fisher’s scoring method (i.e., iteratively reweighted least squares (IRLS))</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Likelihood optimization algorithm</td>
<td style="text-align: left;"><code>TECHNIQUE = NEWTON</code></td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;">Newton-Raphson algorithm</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Convergence criteria</td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Specifies relative gradient convergence criterion (GCONV=1E–8).</td>
<td style="text-align: left;">In<code>PROC LOGISTIC</code> there are three other convergence criteria which can be specified. If more than one convergence criterion is specified, the optimization is terminated as soon as one of the criteria is satisfied.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Convergence criteria</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;">Specifies three criteria that need to be met: the change in log likelihood is less than lconv (default is 1E-5), the maximum absolute element of the score vector is less than gconv (default is 1E-5), and the maximum absolute change in beta is less than xconv (default is 1E-5).</td>
<td style="text-align: left;">The gconv criteria in <code>logistif</code> is different from <code>GCONV</code> in SAS. The lconv criteria is also not exactly the same as the <code>ABSFCONV</code> or <code>FCONV</code> in <code>PROC LOGISTIC</code> in SAS, although the criteria use log likelihood. However, the <code>xconv</code> in R and <code>XCONV</code> in SAS seems to be consistent.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Convergence criteria</td>
<td style="text-align: left;"><code>XCONV = 1E–8</code></td>
<td style="text-align: left;"><code>control = logistf.control( xconv = 1E–8, lconv = 1, gconv = 1)</code></td>
<td style="text-align: left;">Specifies the maximum absolute change in beta &lt; 1E–8.</td>
<td style="text-align: left;">In <code>logistf</code>, three convergence criteria are checked at the same time. So here we use a large convergence criteria value for <code>lconv</code> and <code>gconv</code> to mimic the scenario where only <code>xconv</code> is checked.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Confidence interval (CI) estimation method</td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;"><code>pl= FALSE</code></td>
<td style="text-align: left;">Wald CI</td>
<td style="text-align: left;">For <code>logistf</code>: “Note that from version 1.24.1 on, the variance-covariance matrix is based on the second derivative of the likelihood of the augmented data rather than the original data, which proved to be a better approximation if the user chooses to set a higher value for the penalty strength.” This could cause differences in standard error estimates in R vs SAS for Firth logistic regression, and consequently results in differences in the corresponding Wald CI estimates and hypothesis tests results (e.g., p-values).</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Confidence interval (CI) estimation method</td>
<td style="text-align: left;"><code>CLPARM = PL</code> <br> <code>CLODDS = PL</code></td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;">Profile likelihood-based CI</td>
<td style="text-align: left;">For Firth’s bias-reduced logistic regression, it makes more sense to use penalized likelihood-based CI so it is consistent with the parameter estimation method which uses penalized maximum likelihood.</td>
</tr>
<tr class="even">
<td style="text-align: center;">Hypothesis tests for regression coefficients</td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;">pl= FALSE</td>
<td style="text-align: left;">Wald tests, which are based on estimates for the regression coefficients and its corresponding standard error.</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Hypothesis tests for regression coefficients</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Default</td>
<td style="text-align: left;">“Likelihood ratio tests”, which are based on profile penalized log likelihood.</td>
<td style="text-align: left;">In SAS, when the model statement option <code>CLPARM = PL</code> is specified, the CI will be calculated based on profile likelihood. However, the hypothesis testing method is still a Wald method. This could cause results mismatch in the p-value.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="numerical-comparison" class="level2">
<h2 class="anchored" data-anchor-id="numerical-comparison">Numerical Comparison</h2>
<p>Note that while Firth logistic regression is not required for our example dataset nonetheless we use it for demonstration purposes only.</p>
<section id="logistf-in-r" class="level3">
<h3 class="anchored" data-anchor-id="logistf-in-r"><code>logistf</code> in R</h3>
<ul>
<li><p>By default, the <a href="https://cran.r-project.org/web/packages/logistf/logistf.pdf">convergence criteria in <code>logistf</code></a> specifies that three criteria need to be met at the same time, i.e., the change in log likelihood is less than lconv (default is 1E-5), the maximum absolute element of the score vector is less than gconv (default is 1E-5), and the maximum absolute change in beta is less than xconv (default is 1E-5). In SAS, the <a href="https://support.sas.com/documentation/cdl/en/statug/63962/HTML/default/viewer.htm#statug_logistic_sect034.htm">default convergence criteria in <code>PROC LOGISTIC</code></a> specifies relative gradient convergence criterion (GCONV=1E–8); while SAS also support three other convergence criteria but when there are more than one convergence criterion specified, the optimization is terminated as soon as one of the criteria is satisfied. By looking at the R pacakge/SAS documentation, the <code>gconv</code> criteria in <code>logistif</code> function is different from the <code>GCONV</code> in SAS. The <code>lconv</code> criteria is also not exactly the same as the <code>ABSFCONV</code> or <code>FCONV</code> in PROC LOGISTIC in SAS, although the criteria use log likelihood. However, similar convergence criteria might be obtained by using the maximum absolute change in parameter estimates (i.e., <code>xconv</code> in R and SAS). Therefore, for comparison with the SAS output, in <code>logistf</code> function, we use a large convergence criteria value for <code>lconv</code> and <code>gconv</code> to mimic the scenario where only <code>xconv</code> is checked, i.e., specify <code>logistf.control(xconv = 0.00000001, gconv = 1, lconv = 1)</code> for the <code>control</code> argument.</p></li>
<li><p>By default, <code>logistf</code> function in R computes the confidence interval estimates and hypothesis tests (including p-value) for each parameter based on profile likelihood, which is also reported in the output below. However, Wald method (confidence interval and tests) can be specified by specifying the <code>control</code> argument with <a href="https://cran.r-project.org/web/packages/logistf/logistf.pdf"><code>pl = FALSE</code></a>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>firth_mod <span class="ot">&lt;-</span> <span class="fu">logistf</span>(wt_grp <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data=</span>lung2, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">control =</span> <span class="fu">logistf.control</span>(<span class="at">fit =</span><span class="st">"IRLS"</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">xconv =</span> <span class="fl">0.00000001</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">gconv =</span> <span class="dv">1</span>, </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">lconv =</span> <span class="dv">1</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(firth_mod)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>logistf(formula = wt_grp ~ age + sex + ph.ecog + meal.cal, data = lung2, 
    control = logistf.control(fit = "IRLS", xconv = 1e-08, gconv = 1, 
        lconv = 1))

Model fitted by Penalized ML
Coefficients:
                     coef     se(coef)   lower 0.95    upper 0.95     Chisq
(Intercept)  3.1532937589 1.6031659729  0.051844703  6.410119e+00 3.9726447
age         -0.0098111679 0.0202315630 -0.050518148  2.974343e-02 0.2337368
sex         -0.8455619163 0.3632129422 -1.571158740 -1.356810e-01 5.4536777
ph.ecog      0.4018229715 0.2520090355 -0.090278518  9.093255e-01 2.5553004
meal.cal    -0.0008495327 0.0004288525 -0.001722033 -7.098976e-06 3.9058205
                     p method
(Intercept) 0.04624509      2
age         0.62876680      2
sex         0.01952718      2
ph.ecog     0.10992492      2
meal.cal    0.04811912      2

Method: 1-Wald, 2-Profile penalized log-likelihood, 3-None

Likelihood ratio test=10.54964 on 4 df, p=0.03212009, n=170
Wald test = 33.85701 on 4 df, p = 7.972359e-07</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)           age           sex       ph.ecog      meal.cal 
 3.1532937589 -0.0098111679 -0.8455619163  0.4018229715 -0.0008495327 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Code below would give Wald CI and tests results by adding `pl = FALSE`</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># logistf(..., pl = FALSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note, function <code>confint</code> gives the profile-likelihood limits. Given the parameters from Firth’s bias-reduced logistic regression is estimated using penalized maximum likelihood, <code>confint</code> function is used. Conditional odds ratio is calculated by taking the exponential of the model parameters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">est =</span> <span class="fu">coef</span>(firth_mod), </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">confint</span>(firth_mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      est    Lower 95%     Upper 95%
(Intercept)  3.1532937589  0.051844703  6.410119e+00
age         -0.0098111679 -0.050518148  2.974343e-02
sex         -0.8455619163 -1.571158740 -1.356810e-01
ph.ecog      0.4018229715 -0.090278518  9.093255e-01
meal.cal    -0.0008495327 -0.001722033 -7.098976e-06</code></pre>
</div>
</div>
</section>
<section id="proc-logistic-in-sas-with-firth-option" class="level3">
<h3 class="anchored" data-anchor-id="proc-logistic-in-sas-with-firth-option"><code>PROC LOGISTIC</code> in SAS (with firth option)</h3>
<ul>
<li><p>Note, by default, SAS computes confidence interval based on Wald tests. Given the parameters from Firth’s method is estimated using penalized maximum likelihood, below specifies CLODDS = PL CLPARM=PL (based on profile likelihood), which is consistent with the maximization method and the R code above. However, the <a href="https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_logistic_details50.htm">default hypothesis test for the regression coefficients</a> is still a Wald test, and the Chi-square statistics is calculated based on coefficient estimate and its corresponding standard error.</p></li>
<li><p><code>XCONV</code> specifies relative parameter convergence criterion, which should correspond to the <code>xconv</code> in <code>logistf</code> function in R. We specify <code>XCONV = 0.00000001</code> so it should be consistent with the R code above.</p></li>
</ul>
<div class="cell">
<pre class="sas cell-code"><code>PROC LOGISTIC DATA=LUNG2;
    MODEL WT_GRP(EVENT="weight gain") = AGE SEX PH_ECOG MEAL_CAL / firth clodds=PL clparm=PL xconv = 0.00000001;
    ods output ESTIMATEs=estimates;
run;</code></pre>
</div>
<p>Below is screenshot of output tables summarizing coefficient estimates and it’s 95% CI</p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/logistic_regression/sas_logistic_firth_estimates.png" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/logistic_regression/sas_logistic_firth_ci.png" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conclusion for Firth logistic regression
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Exact match cannot be obtained for all estimates using <code>logistf</code> vs <code>PROC LOGISTIC</code> procedure with Firth option. More specifically:<br>
- Coefficient estimate and its 95% CI matched at 0.001 level;<br>
- Standard error are not the same (e.g., 0.02023 for age in R vs 0.02065 in SAS);<br>
- p-value is not the same (0.6288 in R for age vs 0.6348 in SAS);<br>
</p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="g-computation-with-covariate-adjustment-1" class="level1">
<h1>g-computation with covariate adjustment</h1>
<p>We compare two implementions of g-computation in SAS:</p>
<ol type="1">
<li>The “Predictive margins and average marginal effects” <a href="https://support.sas.com/kb/63/038.html#pur">%margins</a> macro. The %margins macro uses “the delta method […] to determine the standard errors for predictive margins and marginal effects”. Note that the %margins macro uses the <code>PROC GENMOD</code> procedure to implement the working logistic regression model and require another macro <a href="https://support.sas.com/kb/58/775.html">%NLEST</a> to calculate contrasts that requires delta methodl such as risk ratio or odds ratio.</li>
<li>The SAS code provided in the appendix of the <a href="https://journals.sagepub.com/doi/10.1177/009286151104500409">Ge et al.&nbsp;(2011)</a> implements the method outlined in the associated paper and simulations. Note: the Ge et al.&nbsp;(2011) macro uses the <code>PROC LOGISTIC</code> procedure to implement the working logistic regression model. <code>PROC IML</code> is used to calculate the delta method to determine the standard errors.</li>
</ol>
<section id="numerical-comparison-1" class="level2">
<h2 class="anchored" data-anchor-id="numerical-comparison-1">Numerical Comparison</h2>
<section id="get_marginal_effect-in-r" class="level3">
<h3 class="anchored" data-anchor-id="get_marginal_effect-in-r"><code>get_marginal_effect</code> in R</h3>
<p>We fit a logistic regression model with covariate adjustment to estimate the marginal treatment effect using the delta method for variance estimation: as outlined in Ge et al (2011).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## fit the model including model based variance estimation with delta method</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(aval <span class="sc">~</span> trtp <span class="sc">+</span> bl_cov, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">data =</span> trial01) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_marginal_effect</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">trt =</span> <span class="st">"trtp"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"Ge"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">contrast =</span> <span class="st">"diff"</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">reference =</span> <span class="st">"0"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">type =</span> <span class="st">"model-based"</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Marginal treatment effect = "</span>, fit1<span class="sc">$</span>marginal_est, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Standard error = "</span>, fit1<span class="sc">$</span>marginal_se, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal treatment effect =  -0.06836399 
 Standard error =  0.06071641 </code></pre>
</div>
</div>
</section>
<section id="margins-macro-in-sas" class="level3">
<h3 class="anchored" data-anchor-id="margins-macro-in-sas"><code>%Margins</code> macro in SAS</h3>
<p>We now use the SAS [<code>%Margins</code>] (https://support.sas.com/kb/63/038.html) macro to perform the Ge et al.&nbsp;(2011) method on <code>trial01</code> to estimate the marginal risk difference and it’s standard error.</p>
<div class="cell">
<pre class="sas cell-code"><code>%Margins(data      = myWork.trial01,
         class     = trtp,
         classgref = first, /*Set reference to first level*/
         response  = avaln,
         roptions  = event='1', /*Ensure event is set to 1 = Yes */
         dist      = binomial,  
         model     = trtp bl_cov,
         margins   = trtp, 
         options   = cl diff reverse, /*Specify risk difference contrast and 
                                      direction of treatment effect is correct*/
         link      = logit);  /*Specify logit link function */
    
** Store output data sets ; 
data myWork.margins_trt_estimates;
  set work._MARGINS;
run;
         
data myWork.margins_trt_diffs;
  set work._DIFFSPM;
run;</code></pre>
</div>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/logistic_regression/sas_logistic_gcomp_margins.png" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
</section>
<section id="lr-macro-in-sas-ge-et-al-2011" class="level3">
<h3 class="anchored" data-anchor-id="lr-macro-in-sas-ge-et-al-2011"><code>%LR</code> macro in SAS (Ge et al, 2011)</h3>
<div class="cell">
<pre class="sas cell-code"><code>%LR(data = myWork.trial01, /* input data set */
    var1 = bl_cov, /* continuous covariates in the logistic regression */
    var2 = trtp, /* categorical covariates in the logistic regression */
    p1 = 1, /* number of continuous covariates in the logistic regression */
    p2 = 1, /* number of categorical covariates in the logistic regression */
    resp = avaln, /* binary response variable in the logistic regression */
    ntrt = 1); /* position of the treatment variable in the categorical covariates */
    
data myWork.ge_macro_trt_diffs;
  set work.geout;
run;</code></pre>
</div>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="../images/logistic_regression/sas_logistic_gcomp_ge.png" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conclusion for g-computation with covariate adjustment
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Exact match at the 0.001 level.</p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="final-remarks" class="level1">
<h1>Final remarks</h1>
<p>In summary, there are a few things to be aware of when comparing logistic regression results in R vs SAS. It is crucial to carefully manage the input parameters for each model to ensure they are configured similarly for logistic regression analyses. As highlighted also in <a href="https://psiaims.github.io/CAMIS/SAS/logistic-regr.html">Logistic Regression in SAS</a>, the variable parameterization is also important for modelling and interpretation, ensuring the types of variable (continuous vs.&nbsp;categorical) and reference values of categorical variable are applied as expected.</p>
<ol type="1">
<li><strong>Likelihood optimization method</strong></li>
</ol>
<ul>
<li><p>The default likelihood optimization method in <code>glm</code> and <code>PROC LOGISTIC</code> is the same (i.e., Fisher’s scoring method or iteratively reweighted least squares (IRLS)).</p></li>
<li><p>However, the default optimization method in <code>logistf</code> is Newton-Raphson, which can be modified into IRLS via <code>control = logistf.control(fit = “IRLS”)</code>. Alternatively, one could specify <code>technique = newton</code> in the model statement in SAS to modify the likelihood optimization method.</p></li>
</ul>
<ol start="2" type="1">
<li><strong>Convergence criteria</strong></li>
</ol>
<ul>
<li><p>Although both SAS and R allows options to modify the convergence criteria, the criteria does not seem to be exactly the same, which could cause results mismatch in some scenarios.</p></li>
<li><p>The <a href="https://support.sas.com/documentation/cdl/en/statug/63962/HTML/default/viewer.htm#statug_logistic_sect034.htm">default convergence criteria in <code>PROC LOGISTIC</code></a> specifies the relative gradient convergence criterion; where the <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/glm.control.html">default convergence criteria in <code>glm</code></a> specifies relative difference between deviance.</p></li>
<li><p>The default setting in logistf have checked more than one convergence criterion in its algorithm (i.e., <a href="https://cran.r-project.org/web/packages/logistf/logistf.pdf">change in log likelihood, derivative of the log likelihood and parameter estimates</a>). One could specify a very large value for two of the criteria in order to mimic the scenario where only one criterion is checked (e.g., <code>control = logistf.control (xconv = 0.00000001, lconv = 1, gconv = 1</code>) in <code>logistf</code> in R should be consistent to the option of <code>xconv = 0.00000001</code> in SAS).</p></li>
</ul>
<ol start="3" type="1">
<li><strong>Confidence interval</strong></li>
</ol>
<ul>
<li><p>The <code>confint()</code> function in R will computes profile likelihood based CI for <code>glm</code> fitted model. However, in SAS, the default confidence interval is Wald CI. To match the default CI calculation in SAS for <code>glm</code> fitted model, use <code>confint.default()</code> function in R.</p></li>
<li><p>Nevertheless, Firth’s biased-reduced logistic regression estimates parameter using penalized maximum likelihood, it makes more sense to use <code>confint()</code> function for <code>logistf</code> fitted model. In the meantime, in SAS, when fitting a Firth’s logistic regression, it is also better to specify the model statement option <code>clparm = pl</code> which will also generate profile penalized likelihood CI.</p></li>
<li><p>We shall note that in the Firth logistic regression numerical example, the estimated standard errors does not match, but the CIs match at 0.001 level. This is because the CI was estimated based on profile penalized likelihood in R and SAS, and please see the next discussion point for potential reasons about differences between the estimated standard error. (I have compared Wald CIs estimated in R vs SAS, which could not match. This make sense as Wald CIs are calculated based on the estimated standard errors.)</p></li>
</ul>
<ol start="4" type="1">
<li><strong>Hypothesis test and p-value</strong></li>
</ol>
<ul>
<li><p>The default hypothesis tests for the regression coefficients are the same in <code>glm</code> and <code>PROC LOGISTIC</code>, which are both Wald tests and calculated based on estimates for the regression coefficients and its corresponding standard error.</p></li>
<li><p>As for <code>logistf</code> function, the default hypothesis testing method is based on profile penalized log likelihood (source code <a href="https://github.com/georgheinze/logistf/blob/master/R/logistf.R">here</a>). And it was noted in the <a href="https://cran.r-project.org/web/packages/logistf/logistf.pdf">R documentation</a> that, <em>“from version 1.24.1 on, the variance-covariance matrix is based on the second derivative of the likelihood of the augmented data rather than the original data, which proved to be a better approximation if the user chooses to set a higher value for the penalty strength.”</em> This could cause difference in the estimate of standard error in R vs SAS for Firth logistic regression, and consequently results in differences in the corresponding Wald CI estimates and hypothesis tests results (e.g., p-values).</p></li>
<li><p>Wald method can be used in a <code>logistf</code> function in R by specifying <code>pl = FALSE</code> in the <code>control</code> argument, which should correspond to the method used in SAS to calculate p-value. However, when specifying <code>pl = FALSE</code>, the CI is also calculated using Wald method.</p></li>
</ul>
</section>
<section id="reference" class="level1">
<h1>Reference</h1>
<ul>
<li>A relevant blog <a href="https://sas-and-r.blogspot.com/2010/11/example-815-firth-logistic-regression.html">here</a> (check comments in the blog).</li>
<li><a href="https://support.sas.com/documentation/cdl/en/statug/63033/HTML/default/viewer.htm#statug_logistic_sect004.htm">PROC LOGISTIC statement documentation in SAS</a>.</li>
<li><a href="https://cran.r-project.org/web/packages/logistf/logistf.pdf">Reference manual for <code>logistf</code> package in R</a>.</li>
<li><a href="https://github.com/georgheinze/logistf">GitHub repository for <code>logistf</code> package in R</a>.</li>
<li><a href="https://github.com/georgheinze/flicflac/tree/master/LogisticRegression">GitHub repository for a SAS procedure about Firth logistic regression authored by the author of <code>logistf</code> R package</a>, which was based on PROC IML instead of PROC LOGISTIC and was probably authored before the availability of Firth option in PROC LOGISTIC statement in SAS.</li>
<li>Ge, Miaomiao, et al.&nbsp;“Covariate-adjusted difference in proportions from clinical trials using logistic regression and weighted risk differences.” Drug information journal: DIJ/Drug Information Association 45 (2011): 481-493.</li>
<li>SAS Institute Inc.&nbsp;<a href="https://support.sas.com/kb/63/038.html">“Predictive margins and average marginal effects.”</a> (Last Published: 13 Dec 2023)</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>