---
title: "Confidence Intervals - proportions for stratified designs"
---

# Introduction

As documented [here](Confidence%20limits%20using%20the%20Miettinen-Nurminen%20stratified%20method%20as%20de...%20-%20SAS%20Support%20Communities), there is requirement to use methods other than the wald method, for CI's for proportions. In certain cases, for example, when you have a baseline imbalance of stratification factors, the stratified Miettinen-Nurminen 1985 method is recommended.

# Packages

There are two identified R packages that can do this:

-   [{ratesci}](petelaud/ratesci:%20Confidence%20intervals%20and%20tests%20for%20comparison%20of%20rates)
-   [{cicalc}](Stratified%20Miettinen-Nurminen%20Confidence%20Interval%20for%20Difference%20in%20Proportions%20—%20ci_prop_diff_mn_strata%20•%20cicalc)

There are two available macros to use in SAS:

-   [scoreci](https://psiaims.github.io/CAMIS/SAS/Score%20confidence%20intervals%20and%20tests%20for%20a%20single%20binomial%20or%20Poisson%20rate,%20or%20for%20comparisons%20of%20independent%20rates,%20with%20or%20without%20stratification.%20%E2%80%94%20scoreci%20%E2%80%A2%20ratesci)

-   [PharmaSUG paper](https://pharmasug.org/proceedings/2025/SA/PharmaSUG-2025-SA-198.pdf)

This page is a placeholder whilst further content is being developed. See the individual R and SAS pages for guidance on using each macro. Note that SAS Proc freq should not be used for stratified Miettinen-Nurminen 1985 method, as it's actually performing an unstratified approach.


Generally, the 4 methods agreed.  The scoreci macro calculates the confidence intervals iteratively using MLE, however, the PharmaSUG paper's method calculates confidence intervals using weighted difference of rates. When the sample size within strata were small this led to small numeric discrepancies.

cicalc in R vs scoreci sas macro reached agreement in the examples tested.

