---
title: "R vs SAS vs StatXact - Wilcoxon signed-rank test"
execute:
  eval: false
---

# Wilcoxon signed-rank test in R, SAS and StatXact

## Introduction

This section compares the implementation of Wilcoxon signed-rank test in R, SAS and StatXact. Poisson regression is used to model count data and contingency tables. It's particularly useful for modeling the number of events occurring within a fixed period of time or space.

## General Comparison Table

The following table provides an overview of the methods support comparability between R, SAS and StatXact for the new analysis point.

+----------------------------------+-----------------------------------+-------------------------------------+-----------------------+-------------------------------------------------+
| Analysis                         | Supported in R                    | Supported in SAS                    | Supported in StatXact | Notes                                           |
+==================================+===================================+=====================================+=======================+=================================================+
| Scenario 1: ccccccccccccc        | Example: [Yes](../R/example_link) | Example: [Yes](../SAS/example_link) | Example 1: Yes        | Specific settings or for exact match            |
|                                  |                                   |                                     |                       |                                                 |
|                                  |                                   |                                     | Example 2: No         |                                                 |
+----------------------------------+-----------------------------------+-------------------------------------+-----------------------+-------------------------------------------------+
| \[Scenario 2: Advanced Feature\] | Example: [Yes](../R/example_link) | Example: [Yes](../SAS/example_link) | Example 3: Partial    | data structure or                               |
+----------------------------------+-----------------------------------+-------------------------------------+-----------------------+-------------------------------------------------+
| \[Scenario 2: Advanced Feature\] | Example: [Yes](../R/example_link) | Example: [Yes](../SAS/example_link) | Example 3: Partial    | Special considerations ftructure or assumptions |
+----------------------------------+-----------------------------------+-------------------------------------+-----------------------+-------------------------------------------------+

## Example Data

Analysis will be conducted on the example of anonymized data from 2-period, cross-over study comparing treatments A and B in patients with asthma and acute airway obstruction induced by repeated mannitol challenges.

For the purpose of the results comparison we will consider a case where the dataset has no ties and N (number of observations) = 240.

Wilcoxon signed rank test was applied to analyse the time to return to baseline FEV1 post-mannitol challenge 2. Median difference, p value and 95% CI were provided using the Hodges-Lehmann estimator.

## Results Comparison

+------------------------------------+----------+------------+----------+---------+---------+
| Statistic                          | R Result | SAS Result | StatXact | Match   | Notes   |
+====================================+==========+============+==========+=========+=========+
| Degrees of Freedom                 | 98       | 98         | Yes      |         |         |
+------------------------------------+----------+------------+----------+---------+---------+
| Coefficient Estimate for Predictor | 0.1      | 0.1        | Yes      |         |         |
+------------------------------------+----------+------------+----------+---------+---------+
| p-value                            | 0.05     | 0.05       | Yes      |         |         |
+------------------------------------+----------+------------+----------+---------+---------+

## Summary and Recommendation

-   xx
-   xx

## Additional References

Details of how to implement the methods in the discussed software are available below:

**R:**

-   Check how to perform this analysis in R [here](../R/wilcoxonsr_hodges_lehman.qmd)

**SAS & StatXact:**

-   Check how to perform this analysis in SAS & StatXact [here](../SAS/wilcoxonsr_HL.qmd)
