---
title: "Confidence Intervals Poisson Exposure Adjusted Incidence Rates (EAIR)"
---

# Introduction

A unified family of methods covering the single rate and all contrasts for independent Poisson rates was described by Laud\^1, with the addition of a bias correction for the OR case\^2.

# Summary

This page is a placeholder whilst further content is being developed.

In many cases, using the {ratesci} R package developed by Pete Laud compared to using the [SAS macro](https://github.com/PeteLaud/ratesci-sas/blob/main/scoreci.sas) also developed by Pete Laud achieved a full match in results.

In one scenario the SAS macro returned an error (whereas R returned valid results), however this was due to the way different computer environments handle floating point rounding. It was fixed by updating rows 449 and 450 of the SAS macro from using 1E-15 (15 decimals) to be 1E-9 (9 decimals).

```         
%else %if "&distrib." = "poi" %then %do;

  D1t = round(tan(pi * max((-1 + 1E-15), min(D1, (1 - 1E-15))) / 2), &converge./100);
  D2t = round(tan(pi * max((-1 + 1E-15), min(D2, (1 - 1E-15))) / 2), &converge./100);
  
%end;
 
```

In a few other scenarios, particularly when results crossed the cut point (eg. 0.000499 vs 0.000500), even using the same rounding method across SAS & R (eg. both using round to even or using round up), led to different results to the third decimal. It is believe this was just due to large decimal rounding eg. above to 9 or 15 decimals or Floating point errors, however more research is needed.

# References

1\) Laud, P. J. [Equal-tailed confidence intervals for comparison of rates](https://doi.org/10.1002/pst.1813).*Pharmaceutical Statistics***16**, 334–348 (2017).

2\) Laud, P. J. [Equal-tailed confidence intervals for comparison of rates](https://doi.org/10.1002/pst.1855).*Pharmaceutical Statistics***17**, 290–293 (2018).
