---
title: "R vs SAS Confidence Intervals for Proportions"
execute:
  eval: false
---

## Introduction

The methods to use for calculating a confidence interval (CI) for a proportion depend on the type of proportion you have.

-   1 sample proportion (1 proportion calculated from 1 group of subjects)

-   2 sample proportions and you want a CI for the difference in the 2 proportions.

    -   If the 2 samples come from 2 independent samples (different subjects in each of the 2 groups)

    -   If the 2 samples are matched (i.e. the same subject has 2 results, one on each group \[paired data\]).

The method selected is also dependent on whether your proportion is close to 0 or 1 (or near to the 0.5 midpoint), and your sample size.

For more technical derivation and reasons why you would use one method above another see the corresponding [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_prop.html).

The tables below provide an overview of findings from R & SAS, for calculation of CIs, for a Single Sample Proportion and for calculation of a difference between 2 matched pair proportions or 2 independent sample proportions.

## General Comparison Table For Single Sample Proportions

See the corresponding [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_prop.html) and [R page](https://psiaims.github.io/CAMIS/R/ci_for_prop.html) for results showing a single set of data run through both SAS and R.

+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Analysis of One Sample Proportion                                  | Supported in R | Supported in SAS | Results Match                          |
+====================================================================+================+==================+========================================+
| Clopper-Pearson Exact                                              | Yes {cardx}    | Yes (default)    | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Normal approximation (Wald Method)                                 | Yes {cardx}    | Yes (default)    | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Normal approximation (Wald Method) with continuity correction      | Yes {cardx}    | Yes              | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Wilson (Score, Altman, Newcombe) method                            | Yes {cardx}    | Yes              | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Wilson (Score, Altman, Newcombe) method with continuity correction | Yes {cardx}    | Yes              | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Agresti Coull                                                      | Yes {cardx}    | Yes              | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Jeffreys Bayesian HPD                                              | Yes {cardx}    | Yes              | Yes                                    |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| midp                                                               | Yes {PropCIs}  | Yes              | results match to the 3rd decimal place |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Blaker                                                             | Yes {PropCIs}  | Yes              | results match to the 5th decimal place |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+
| Wilson Stratified score                                            | Yes {cardx}    | No               | NA                                     |
+--------------------------------------------------------------------+----------------+------------------+----------------------------------------+

## General Comparison Table For Two Matched Samples Proportions

+------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Analysis of Two Matched Sample Proportions           | Supported in R    | Supported in SAS                                                                            | Notes                                                                                                                                                     |
+======================================================+===================+=============================================================================================+===========================================================================================================================================================+
| Exact method                                         | Yes {ExactCIdiff} | No                                                                                          |                                                                                                                                                           |
+------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Normal approximation (Wald Method)                   | No                | No (proc freq does CIs for the risk difference, not the difference between two proportions) | Using the equations provided in the [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_prop.html), You could do this programatically in either package |
+------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Wilson (Score method or the Altman, Newcombe method) | No                | No (proc freq does CIs for the risk difference, not the difference between two proportions) | Using the equations provided in the [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_prop.html), You could do this programatically in either package |
+------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+

Calculating the Normal approximation and Wilson methods by hand and comparing it to the Exact method gave similar results for the 1 example demonstrated indicating as long as the proportion of responders is not close to 0 or 1, then the faster computation of the approximation methods may be easier to implement than the exact method and produce similar results. Hence {ExactCIdiff} is not recommended for most scenarios.

+-------------+----------------------------------------------------------------------------------------------+--------------+--------------+
| Method Name | Calculated Using matched pair example from R & SAS pages                                     | Lower 95% CI | Upper 95% CI |
+=============+==============================================================================================+==============+==============+
| Exact       | R                                                                                            | -0.00339     | 0.38065      |
+-------------+----------------------------------------------------------------------------------------------+--------------+--------------+
| Normal      | by hand using equation from [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_prop.html) | 0.00911      | 0.38289      |
+-------------+----------------------------------------------------------------------------------------------+--------------+--------------+
| Wilson      | by hand using equation from [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_prop.html) | 0.00032      | 0.36739      |
+-------------+----------------------------------------------------------------------------------------------+--------------+--------------+

## General Comparison Table For Two Independent Samples Proportions

+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Analysis of Two Independant Sample Proportions                     | Supported in R                                                     | Supported in SAS | Results Match                                                                                                                                                                                                                                 |
+====================================================================+====================================================================+==================+===============================================================================================================================================================================================================================================+
| Normal approximation (Wald Method)                                 | Yes {DescTools}                                                    | Yes (default)    | Yes and results match by hand calculation                                                                                                                                                                                                     |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("wald"))`                                 |                  | **Warning** The documentation for stats::prop.test which is used in {cardx} says it's using newcombe method. However, the results match the Normal Approximation (wald) method. Hence it is reccomended to use {DescTools} instead of {cardx} |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | Yes {cardx} `ard_stats_prop_test function` uses `stats::prop.test` |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Normal approximation (Wald Method) with continuity correction      | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,method=c("waldcc"))`                               |                  | **Warning** that documentation for stats::prop.test says it's using newcombe method. However, the results match the Normal Approximation (wald) method.                                                                                       |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | Yes {cardx} as per above but with correct=TRUE                     |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Wilson (Score, Altman, Newcombe) method                            | Yes {DescTools}                                                    | Yes              | Yes and results match by hand calculation                                                                                                                                                                                                     |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,`method=c("score"))                                |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Wilson (Score, Altman, Newcombe) method with continuity correction | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,`method=c("scorecc"))                              |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Agresti-Caffo                                                      | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,`method=c("ac"))                                   |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Hauck-Anderson                                                     | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,`method=c("ha"))                                   |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miettinen-Nurminen                                                 | Yes {DescTools}                                                    | Yes              | Yes                                                                                                                                                                                                                                           |
|                                                                    |                                                                    |                  |                                                                                                                                                                                                                                               |
|                                                                    | `BinomDiffCI(..,`method=c("mn"))                                   |                  |                                                                                                                                                                                                                                               |
+--------------------------------------------------------------------+--------------------------------------------------------------------+------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Prerequisites: R Packages

See the [R page](https://psiaims.github.io/CAMIS/R/ci_for_prop.html) for more detail.

```{r}
# Example R packages required
library(cardx) 
```

## 
