---
title: "R vs SAS Confidence Intervals for Independent Proportions"
---

# Introduction

See the [summary page](../method_summary/ci_for_prop_intro.html) for general introductory information on confidence intervals for proportions, including the principles underlying the most common methods.

For more technical derivation of methods for comparing independent proportions, see the corresponding [SAS page](https://psiaims.github.io/CAMIS/SAS/ci_for_2indep_prop.html).

The tables below provide an overview of findings from R & SAS, for calculation of CIs for comparisons of 2 independent proportions.

Note that if the number of responses in both groups is zero, SAS fails to produce confidence intervals for the difference.

# Proportion Difference

+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Analysis of Two Independent Sample Proportions                | Supported in R                        | Supported in SAS               | Results Match                                                                             |
+===============================================================+=======================================+================================+===========================================================================================+
| Normal approximation (Wald Method)                            | Yes {ratesci} `rdci()`                | Yes (default)                  | Yes and results match by hand calculation                                                 |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method = c("wald"))`  |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Agresti-Caffo                                                 | Yes {ratesci} `rdci()`                | Yes                            | Yes                                                                                       |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("ac"))`      |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| MOVER Wilson (Newcombe hybrid score) method                   | Yes {ratesci} `rdci()`                | Yes ('Newcombe')               | Yes and results match by hand calculation.                                                |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                | **Warning**: {DescTools} 'method=score' not to be confused with Asymptotic Score methods. |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("score"))`   |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| MOVER Jeffreys                                                | Yes {ratesci} `rdci()`                | No                             | NA                                                                                        |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Miettinen-Nurminen Asymptotic Score                           | Yes {ratesci} `rdci()`                | Yes                            | Yes                                                                                       |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("mn"))`      |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Mee Asymptotic Score                                          | Yes {ratesci} `rdci()`                | Yes ('Miettinen-Nurminen-Mee') | Yes                                                                                       |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("mn"))`      |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Skewness-corrected Asymptotic Score                           | Yes {ratesci} `rdci()`                | No                             | NA                                                                                        |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {ratesci}                         |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `scasci(..,contrast="RD")`            |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
|                                                               |                                       |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Normal approximation (Wald Method) with continuity correction | Yes {ratesci} `rdci(..., cc=TRUE)`    | Yes                            | Yes                                                                                       |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("waldcc"))`  |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Hauck-Anderson continuity adjusted                            | Yes {ratesci} `rdci(..., cc=TRUE)`    | Yes                            | Yes                                                                                       |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("ha"))`      |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| MOVER Wilson (Newcombe) method with continuity adjustment     | Yes {ratesci} `rdci(..., cc=TRUE)`    | Yes ('Newcombe (Corrected)')   | Yes                                                                                       |
|                                                               |                                       |                                |                                                                                           |
|                                                               | Yes {DescTools}                       |                                |                                                                                           |
|                                                               |                                       |                                |                                                                                           |
|                                                               | `BinomDiffCI(..,method=c("scorecc"))` |                                |                                                                                           |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| MOVER Jeffreys with continuity adjustment                     | Yes {ratesci} `rdci(..., cc=TRUE)`    | No                             | NA                                                                                        |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| Asymptotic Score methods with continuity adjustment           | Yes {ratesci} `rdci(..., cc=TRUE)`    | No                             | NA                                                                                        |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+
| 'Exact' methods                                               | No                                    | Yes                            | NA                                                                                        |
+---------------------------------------------------------------+---------------------------------------+--------------------------------+-------------------------------------------------------------------------------------------+

# Relative Risk

(Continuity-adjusted methods omitted for brevity)

+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| Analysis of Two Independent Sample Proportions | Supported in R                          | Supported in SAS         | Results Match |
+================================================+=========================================+==========================+===============+
| Normal approximation (Wald/Katz log Method)    | Yes {ratesci} `rrci()`                  | Yes (default)            | Yes           |
|                                                |                                         |                          |               |
|                                                | Yes {DescTools}                         |                          |               |
|                                                |                                         |                          |               |
|                                                | `BinomRatioCI(..,method=c("katz.log"))` |                          |               |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| Likelihood ratio                               | No                                      | Yes                      | NA            |
|                                                |                                         |                          |               |
|                                                |                                         | `CL=LR`                  |               |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| MOVER-R Wilson                                 | Yes {ratesci} `rrci()`                  | No                       | NA            |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| MOVER-R Jeffreys                               | Yes {ratesci} `rrci()`                  | No                       | NA            |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| Miettinen-Nurminen Asymptotic Score            | Yes {ratesci} `rrci()`                  | Yes ('Score')            | Yes           |
|                                                |                                         |                          |               |
|                                                | Yes {DescTools}                         | `CL=score`               |               |
|                                                |                                         |                          |               |
|                                                | `BinomRatioCI(..,method=c("mn"))`       |                          |               |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| Koopman Asymptotic Score                       | Yes {ratesci} `rrci()`                  | Yes                      | Yes           |
|                                                |                                         |                          |               |
|                                                | Yes {DescTools}                         | `CL=(score(correct=no))` |               |
|                                                |                                         |                          |               |
|                                                | `BinomDiffCI(..,method=c("mn"))`        |                          |               |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| Skewness-corrected Asymptotic Score            | Yes {ratesci} `rrci()`                  | No                       | NA            |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+
| Continuity adjusted methods                    | Yes {ratesci} `rrci(..., cc=TRUE)`      | No                       | NA            |
+------------------------------------------------+-----------------------------------------+--------------------------+---------------+

# Odds Ratio

(Continuity-adjusted methods omitted for brevity)

+------------------------------------------------+---------------------------+--------------------------+---------------+
| Analysis of Two Independent Sample Proportions | Supported in R            | Supported in SAS         | Results Match |
+================================================+===========================+==========================+===============+
| Normal approximation (Wald/Woolf logit Method) | Yes {ratesci} `orci()`    | Yes (default)            | Yes           |
|                                                |                           |                          |               |
|                                                | Yes {contingencytables}   |                          |               |
|                                                |                           |                          |               |
|                                                | `Woolf_logit_CI_2x2()`    |                          |               |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| Likelihood ratio                               | No                        | Yes                      | NA            |
|                                                |                           |                          |               |
|                                                |                           | `CL=LR`                  |               |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| Mid-P                                          | Yes {contingencytables}   | Yes                      | Yes           |
|                                                |                           |                          |               |
|                                                | `Cornfield_midP_CI_2x2()` |                          |               |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| MOVER-R Wilson                                 | Yes {ratesci} `orci()`    | No                       | NA            |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| MOVER-R Jeffreys                               | Yes {ratesci} `orci()`    | No                       | NA            |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| Miettinen-Nurminen Asymptotic Score            | Yes {ratesci} `orci()`    | Yes ('Score')            | Yes           |
|                                                |                           |                          |               |
|                                                |                           | `CL=score`               |               |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| Uncorrected Asymptotic Score                   | Yes {ratesci} `orci()`    | Yes                      | Yes           |
|                                                |                           |                          |               |
|                                                |                           | `CL=(score(correct=no))` |               |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| Skewness-corrected Asymptotic Score            | Yes {ratesci} `orci()`    | No                       | NA            |
+------------------------------------------------+---------------------------+--------------------------+---------------+
| Continuity adjusted methods                    | Yes {ratesci}             | No                       | NA            |
|                                                |                           |                          |               |
|                                                | `orci(..., cc=TRUE)`      |                          |               |
+------------------------------------------------+---------------------------+--------------------------+---------------+

## Prerequisites: R Packages

See the [R page](https://psiaims.github.io/CAMIS/R/ci_for_prop.html) for more detail.

```{r}
# Example R packages required
library(ratesci)
```
