{
  "hash": "626461c7f6995a39bffa1593a377abd0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"SAS Recurrent Events\"\n---\n\n\n\n\n\n\n\n# Recurrent event models\n\n## Modelling recurrent events\n\n### Methodology introduction\n\nTraditionally, survival analysis focuses on the time to a *single* first event. While there are many applications for such time-to-event analysis in clinical trials, this approach falls short when events of interest can occur multiple times within the same subject. Recurrent event models extend the traditional Cox proportional hazards framework to account for *multiple* events per subject ([Ozga et al. 2018](https://pubmed.ncbi.nlm.nih.gov/29301487/), [Amorim et al. 2015](https://pubmed.ncbi.nlm.nih.gov/25501468/)).\n\nIn this tutorial, we will demonstrate how to implement different recurrent event models in SAS, specifically the Andersen-Gill, proportional means/rates (Lin-Wei-Yang-Ying,) Prentice-Williams-Peterson, and Wei-Lin-Weissfeld models. The SAS code follows the layout of [Amor 2023](https://www.lexjansen.com/phuse/2023/as/PAP_AS05.pdf), with additional insights taken from [Lu et al. 2018](https://www.lexjansen.com/pharmasug/2018/EP/PharmaSUG-2018-EP02.pdf).\n\nRecurrent event models can roughly be divided in three categories: counting process models, conditional models and marginal models. In the section below, we will explore the difference between each of these approaches. In addition, important aspects of data structure will be discussed by means of two fictional subjects, one with 4 events and 0 censored observations (events at time 6, 9, 56 and 88), and another with 2 events and 1 censored observation (events at time 42, 57, and censored at time 91).\n\nDefine the following:\n\n::: callout-note\n$$*$$\n\n$\\lambda_i(t)$: hazard function for the $i$th subject at time $t$\n\n$\\lambda_{ij}(t)$: hazard function for the $j$th event of the $i$th subject at time $t$\n\n$\\lambda_0(t)$: common baseline hazard for all events\n\n$\\lambda_{0j}(t)$: event-specific baseline hazard for the $j$th event at time $t$\n\n$\\beta$: common parameter vector\n\n$\\beta_j$: event-specific parameter vector for the $j$th event\n\n$X_{ij}$: covariate vector for the $j$th event of the $i$th subject\n:::\n\n### Counting process models\n\n#### Andersen-Gill model ([Andersen & Gill 1982](https://projecteuclid.org/journals/annals-of-statistics/volume-10/issue-4/Coxs-Regression-Model-for-Counting-Processes--A-Large-Sample/10.1214/aos/1176345976.full))\n\n$$\n\\lambda_i(t) = \\lambda_0(t) \\exp \\left( \\beta X_{ij}(t) \\right) \\ *\n$$\n\n-   Counting process approach: treats each subject as a multiple events counting process\n\n-   Common baseline hazard $\\lambda_0(t)$\n\n-   Common regression coefficients $\\beta$\n\n-   Unrestricted risk set: a subject contributes to the risk set for an event as long as the subject is under observation, i.e. it can be at risk for a subsequent event even though the previous event did not yet occur\n\n-   Order of events is not important\n\nAn essential assumption of the Andersen-Gill model is that of **independent events** within subjects. This, however, is often not realistic in clinical trial data. For example, let's say that we are modelling myocardial infarction (MI). If a patient has already experienced one MI, their risk of subsequent events may increase due to underlying cardiovascular damage or presence of other risk factors. Thus, the more events a patient has, the more likely they are to experience future events, indicating dependence rather than independence. To accurately model this within-subject correlation, extensions like time-varying covariates, a robust sandwich covariance estimator or frailty terms may be needed. In this tutorial, we will discuss the sandwich correction.\n\n**Lin-Wei-Yang-Ying (LWYY) model or proportional means/rates model ([Lei, Wei, Yang & Ying 2000](https://www.jstor.org/stable/2680616))**\n\nLin, Wei, Yang & Ying introduced an improved version of the Andersen-Gill model in 2000 (often referred to as proportional means/rates model), featuring a robust sandwich estimator that explicitly accounts for individual subject clusters. These robust standard errors yield wider confidence intervals and provide asymptotically valid inference even when the independence assumption does not hold ([Lee et al. 2025](https://pubmed.ncbi.nlm.nih.gov/40490702/)). The original and improved Andersen-Gill model often appear interchangeable in the literature, and while they produce identical estimates, their robust standard errors can differ substantially, which may impact the conclusions drawn from statistical inference.\n\nFor both versions of the Andersen-Gill model, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (6, 9\\]       | 1     | 1       |\n| 1       | (9, 56\\]      | 1     | 1       |\n| 1       | (56, 88\\]     | 1     | 1       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (42, 87\\]     | 1     | 1       |\n| 2       | (87, 91\\]     | 0     | 1       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/AG_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nIn both versions of the Andersen-Gill model, each new time interval starts where the previous one ends.\n\n### Conditional models\n\n#### Prentice-Williams-Peterson model ([Prentice, Williams & Peterson 1981](https://academic.oup.com/biomet/article-abstract/68/2/373/260402?redirectedFrom=fulltext))\n\n-   Conditional approach: incorporates conditional strata to account for ordering/dependence of events\n\n-   Stratified baseline hazard $\\lambda_{0j}(t)$\n\n-   Stratified regression coefficients $\\beta_j$: can be pooled ($\\beta$) or kept as event-specific ($\\beta_j$) in the output\n\n-   Restricted risk set: contributions to the risk set for a subsequent event are restricted to only consider subjects that already experienced the previous event\n\n-   Order of events is important\n\nThe Prentice-Williams-Peterson model can incorporate both overall and event-specific effects $\\beta_j$ for each covariate. An often made assumption is to set $\\beta_1 = \\beta_2 = ... = \\beta_k = \\beta$ to estimate a common parameter $\\beta$.\n\nDepending on the outcome of interest, Prentice, Williams and Peterson suggested two distinct models:\n\n1.  **Total time model**\n\n$$\n\\lambda_{ij}(t) = \\lambda_{0j}(t) \\exp \\left( \\beta_j X_{ij}(t) \\right) \\ *\n$$\n\nThe total time variant of the Prentice-Williams-Peterson model uses the same time intervals as the counting process approach (Andersen-Gill model), which is useful for modelling the full time course ($t$) of the recurrent event process, i.e. the hazard of *any* recurrence.\n\nFor the total time model, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (6, 9\\]       | 1     | 2       |\n| 1       | (9, 56\\]      | 1     | 3       |\n| 1       | (56, 88\\]     | 1     | 4       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (42, 87\\]     | 1     | 2       |\n| 2       | (87, 91\\]     | 0     | 3       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/PWPtt_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nAgain, in the total time model, each new time intervals starts where the previous one ends.\n\n2.  **Gap time model**\n\n$$\n\\lambda_{ij}(t) = \\lambda_{0j}(t - t_{j-1}) \\exp \\left( \\beta_j X_{ij}(t) \\right) \\ *\n$$\n\nThe gap time variant of the Prentice-Williams-Peterson model uses time intervals that start at zero and end at the length of time until the next event, which is useful for modelling the time between each of the recurring events ($t - t_{j-1}$), i.e. the hazard of recurrence *after the previous event*.\n\nFor the gap time model, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (0, 3\\]       | 1     | 2       |\n| 1       | (0, 47\\]      | 1     | 3       |\n| 1       | (0, 32\\]      | 1     | 4       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (0, 45\\]      | 1     | 2       |\n| 2       | (0, 3\\]       | 0     | 3       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/PWPgt_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nIn the gap time model, each time interval starts at zero and has a length equal to the gap time between two neighboring events.\n\n### Marginal models\n\n#### Wei-Lin-Weissfeld model ([Wei, Lin & Weissfeld 1989](https://www.jstor.org/stable/2290084))\n\n$$\n\\lambda_{ij}(t) = \\lambda_{0j}(t) \\exp \\left( \\beta_j X_{ij}(t) \\right) \\ * \n$$\n\n-   Marginal approach: treats each (recurrent) event as having a separate, marginal process\n-   Stratified baseline hazard $\\lambda_{0j}(t)$\n-   Semi-restricted risk set: all subjects contribute follow-up times to all *potential* events, i.e. each subject is at risk for all *potential* events, regardless of how many events that subject actually experiences\n-   Order of events is not important\n\nAlthough the Wei-Lin-Weissfeld model has it roots in competing risks analysis, it conveniently lends itself to model recurrent events as well. Like the Andersen-Gill model, the Wei-Lin-Weissfeld model also assumes **independence** of events, which is often not feasible in practice. In addition, it is assumed there is no specific order among the events or that the events are different types of events, and not necessarily *recurrent* events.\n\nLike the Prentice-Williams-Peterson models, the Wei-Lin-Weissfeld model can incorporate both overall and event-specific effects $\\beta_j$ for each covariate. An often made assumption is to set $\\beta_1 = \\beta_2 = ... = \\beta_k = \\beta$ to estimate a common parameter $\\beta$. Another approach is to combine event-specific effects $\\beta_j$ to get an estimator of the average treatment effect, as described in [Wei, Lin & Weissfeld 1989](https://www.jstor.org/stable/2290084) (this is not discussed further here).\n\nFor Wei-Lin-Weissfeld models, the data must be structured as follows:\n\n| Subject | Time interval | Event | Stratum |\n|---------|---------------|-------|---------|\n| 1       | (0, 6\\]       | 1     | 1       |\n| 1       | (0, 9\\]       | 1     | 2       |\n| 1       | (0, 56\\]      | 1     | 3       |\n| 1       | (0, 88\\]      | 1     | 4       |\n| 2       | (0, 42\\]      | 1     | 1       |\n| 2       | (0, 87\\]      | 1     | 2       |\n| 2       | (0, 91\\]      | 0     | 3       |\n| 2       | (0, 91\\]      | 0     | 4       |\n\nThis can be visually represented:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/WLW_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nIn the Wei-Lin-Weissfeld model, each time intervals starts at zero and ends at its respective event time.\n\n### Overview of all models\n\nIn summary, the selection of the model to use would depend on the type of events, the importance of the order of the events and the time intervals to be analyzed. We made an effort to summarize the similarities and differences between the models in the table below.\n\n|   | **AG** | **PWPtt** | **PWPgt** | **WLW** |\n|---------------|---------------|---------------|---------------|---------------|\n| **Approach** | counting process | conditional | conditional | marginal |\n| **Baseline hazard** | common | stratified | stratified | stratified |\n| **Regression coefficients** | common | stratified possible | stratified possible | stratified possible |\n| **Risk set** | unrestricted | restricted | restricted | semi-restricted |\n| **Time interval** | total time | total time | gap time | total time |\n| **Order of events** | not important | important | important | not important |\n| **Hazard ratio (HR)** | risk of any recurrence | risk of any recurrence | risk of recurrence after previous event | risk of event of any type, not necessarily recurrent event |\n\nNote that, because the ordering of events is not important in the Andersen-Gill and Wei-Lin-Weissfeld model, these models come with the assumption of **independence** of events. In contrast, the Prentice-Williams-Peterson models overcome the need for this assumption by capturing the dependence structure between recurrent events in conditional strata. Consequently, events are assumed to be *conditionally* independent in the Prentice-Williams-Peterson models.\n\nA nice visual representation of the stratification and time interval structure of each model is given below. The correct data structure is pivotal when modelling recurrent events and depends on the methodology you want to use, as illustrated in the figure.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/combined_lineplot.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Modelling recurrent events using the `survival` package\n\n### Data\n\nFor this tutorial we will use the [`bladder` data](https://rdrr.io/cran/survival/man/bladder.html) from the [`survival` R package](https://cran.r-project.org/web/packages/survival/survival.pdf), which captures recurrences of bladder cancer from a clinical trial for an oncolytic called thiotepa. The `bladder` data is regularly used by many statisticians to demonstrate methodology for recurrent event modelling. Somewhat confusingly, there are three versions of this data available:\n\n-   `bladder1`: original data from the study on all subjects (294 records)\n\n-   `bladder2`: data in Andersen-Gill format on subset of subjects with nonzero follow-up time (178 records)\n\n-   `bladder`: data in Wei-Lin-Weissfeld format on subset of subjects with nonzero follow-up time (340 records)\n\nFor this tutorial, we will use `bladder2` to illustrate Andersen-Gill and Prentice-Williams-Peterson models, and `bladder` to illustrate the Wei-Lin-Weissfeld model.\n\nThe variables included in both datasets are:\n\n-   **id**: patient id\n\n-   **rx**: treatment group (1 = placebo, 2 = thiotepa)\n\n-   **number**: initial number of tumors (8 = 8 or more)\n\n-   **size**: size in cm of largest initial tumor\n\n-   **start**: start of time interval; this variable is **not** present in `bladder`\n\n-   **stop**: (recurrent) event or censoring time\n\n-   **event**: event indicator (1 = event, 0 = censored)\n\n-   **enum**: order of recurrence\n\nImportantly, both datasets collect the data in a **counting process** structure. This means that there is one record for each subject and time interval, where a time interval is defined as the time to its respective event (**event** = 1), or the time to follow-up if the event did not occur (**event** = 0).\n\nLet's look more closely at the `bladder2` and `bladder` data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder2 <- survival::bladder2\ngt(head(bladder2, 6))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gmzuylbprc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gmzuylbprc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gmzuylbprc thead, #gmzuylbprc tbody, #gmzuylbprc tfoot, #gmzuylbprc tr, #gmzuylbprc td, #gmzuylbprc th {\n  border-style: none;\n}\n\n#gmzuylbprc p {\n  margin: 0;\n  padding: 0;\n}\n\n#gmzuylbprc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gmzuylbprc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gmzuylbprc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gmzuylbprc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gmzuylbprc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gmzuylbprc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gmzuylbprc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gmzuylbprc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gmzuylbprc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gmzuylbprc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gmzuylbprc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gmzuylbprc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gmzuylbprc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gmzuylbprc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gmzuylbprc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gmzuylbprc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gmzuylbprc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gmzuylbprc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gmzuylbprc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gmzuylbprc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gmzuylbprc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gmzuylbprc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gmzuylbprc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gmzuylbprc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gmzuylbprc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gmzuylbprc .gt_left {\n  text-align: left;\n}\n\n#gmzuylbprc .gt_center {\n  text-align: center;\n}\n\n#gmzuylbprc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gmzuylbprc .gt_font_normal {\n  font-weight: normal;\n}\n\n#gmzuylbprc .gt_font_bold {\n  font-weight: bold;\n}\n\n#gmzuylbprc .gt_font_italic {\n  font-style: italic;\n}\n\n#gmzuylbprc .gt_super {\n  font-size: 65%;\n}\n\n#gmzuylbprc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gmzuylbprc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gmzuylbprc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gmzuylbprc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gmzuylbprc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gmzuylbprc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gmzuylbprc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gmzuylbprc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gmzuylbprc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rx\">rx</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number\">number</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"size\">size</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"start\">start</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stop\">stop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"event\">event</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">0</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">6</td>\n<td headers=\"event\" class=\"gt_row gt_right\">1</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"start\" class=\"gt_row gt_right\">6</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder2 %>%\n  group_by(enum) %>% summarise(n = n()) %>% gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mltbhidqvd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mltbhidqvd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mltbhidqvd thead, #mltbhidqvd tbody, #mltbhidqvd tfoot, #mltbhidqvd tr, #mltbhidqvd td, #mltbhidqvd th {\n  border-style: none;\n}\n\n#mltbhidqvd p {\n  margin: 0;\n  padding: 0;\n}\n\n#mltbhidqvd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mltbhidqvd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mltbhidqvd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mltbhidqvd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mltbhidqvd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mltbhidqvd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mltbhidqvd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mltbhidqvd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mltbhidqvd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mltbhidqvd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mltbhidqvd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mltbhidqvd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mltbhidqvd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mltbhidqvd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mltbhidqvd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mltbhidqvd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mltbhidqvd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mltbhidqvd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mltbhidqvd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mltbhidqvd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mltbhidqvd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mltbhidqvd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mltbhidqvd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mltbhidqvd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mltbhidqvd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mltbhidqvd .gt_left {\n  text-align: left;\n}\n\n#mltbhidqvd .gt_center {\n  text-align: center;\n}\n\n#mltbhidqvd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mltbhidqvd .gt_font_normal {\n  font-weight: normal;\n}\n\n#mltbhidqvd .gt_font_bold {\n  font-weight: bold;\n}\n\n#mltbhidqvd .gt_font_italic {\n  font-style: italic;\n}\n\n#mltbhidqvd .gt_super {\n  font-size: 65%;\n}\n\n#mltbhidqvd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mltbhidqvd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mltbhidqvd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mltbhidqvd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mltbhidqvd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mltbhidqvd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mltbhidqvd .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mltbhidqvd .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mltbhidqvd div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">2</td>\n<td headers=\"n\" class=\"gt_row gt_right\">46</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">3</td>\n<td headers=\"n\" class=\"gt_row gt_right\">27</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">4</td>\n<td headers=\"n\" class=\"gt_row gt_right\">20</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nIn `bladder2`, in the Andersen-Gill format, each subject has a variable amount of records, depending on the amount of events that subject experienced.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder <- survival::bladder\ngt(head(bladder, 20))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"muwwcgjtno\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#muwwcgjtno table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#muwwcgjtno thead, #muwwcgjtno tbody, #muwwcgjtno tfoot, #muwwcgjtno tr, #muwwcgjtno td, #muwwcgjtno th {\n  border-style: none;\n}\n\n#muwwcgjtno p {\n  margin: 0;\n  padding: 0;\n}\n\n#muwwcgjtno .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#muwwcgjtno .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#muwwcgjtno .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#muwwcgjtno .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#muwwcgjtno .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#muwwcgjtno .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#muwwcgjtno .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#muwwcgjtno .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#muwwcgjtno .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#muwwcgjtno .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#muwwcgjtno .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#muwwcgjtno .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#muwwcgjtno .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#muwwcgjtno .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#muwwcgjtno .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#muwwcgjtno .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#muwwcgjtno .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#muwwcgjtno .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#muwwcgjtno .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#muwwcgjtno .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#muwwcgjtno .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#muwwcgjtno .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#muwwcgjtno .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#muwwcgjtno .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#muwwcgjtno .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#muwwcgjtno .gt_left {\n  text-align: left;\n}\n\n#muwwcgjtno .gt_center {\n  text-align: center;\n}\n\n#muwwcgjtno .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#muwwcgjtno .gt_font_normal {\n  font-weight: normal;\n}\n\n#muwwcgjtno .gt_font_bold {\n  font-weight: bold;\n}\n\n#muwwcgjtno .gt_font_italic {\n  font-style: italic;\n}\n\n#muwwcgjtno .gt_super {\n  font-size: 65%;\n}\n\n#muwwcgjtno .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#muwwcgjtno .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#muwwcgjtno .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#muwwcgjtno .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#muwwcgjtno .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#muwwcgjtno .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#muwwcgjtno .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#muwwcgjtno .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#muwwcgjtno div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"id\">id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rx\">rx</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"number\">number</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"size\">size</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stop\">stop</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"event\">event</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">1</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">3</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">1</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">2</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">2</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">4</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">3</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">1</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">7</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">4</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">5</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">6</td>\n<td headers=\"event\" class=\"gt_row gt_right\">1</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"id\" class=\"gt_row gt_right\">5</td>\n<td headers=\"rx\" class=\"gt_row gt_right\">1</td>\n<td headers=\"number\" class=\"gt_row gt_right\">4</td>\n<td headers=\"size\" class=\"gt_row gt_right\">1</td>\n<td headers=\"stop\" class=\"gt_row gt_right\">10</td>\n<td headers=\"event\" class=\"gt_row gt_right\">0</td>\n<td headers=\"enum\" class=\"gt_row gt_right\">4</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbladder %>%\n  group_by(enum) %>% summarise(n = n()) %>% gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"opaaquqqbm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#opaaquqqbm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#opaaquqqbm thead, #opaaquqqbm tbody, #opaaquqqbm tfoot, #opaaquqqbm tr, #opaaquqqbm td, #opaaquqqbm th {\n  border-style: none;\n}\n\n#opaaquqqbm p {\n  margin: 0;\n  padding: 0;\n}\n\n#opaaquqqbm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#opaaquqqbm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#opaaquqqbm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#opaaquqqbm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#opaaquqqbm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#opaaquqqbm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#opaaquqqbm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#opaaquqqbm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#opaaquqqbm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#opaaquqqbm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#opaaquqqbm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#opaaquqqbm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#opaaquqqbm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#opaaquqqbm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#opaaquqqbm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opaaquqqbm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#opaaquqqbm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#opaaquqqbm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#opaaquqqbm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opaaquqqbm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#opaaquqqbm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opaaquqqbm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#opaaquqqbm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opaaquqqbm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#opaaquqqbm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#opaaquqqbm .gt_left {\n  text-align: left;\n}\n\n#opaaquqqbm .gt_center {\n  text-align: center;\n}\n\n#opaaquqqbm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#opaaquqqbm .gt_font_normal {\n  font-weight: normal;\n}\n\n#opaaquqqbm .gt_font_bold {\n  font-weight: bold;\n}\n\n#opaaquqqbm .gt_font_italic {\n  font-style: italic;\n}\n\n#opaaquqqbm .gt_super {\n  font-size: 65%;\n}\n\n#opaaquqqbm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#opaaquqqbm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#opaaquqqbm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#opaaquqqbm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#opaaquqqbm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#opaaquqqbm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#opaaquqqbm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#opaaquqqbm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#opaaquqqbm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"enum\">enum</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">1</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">2</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">3</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n    <tr><td headers=\"enum\" class=\"gt_row gt_right\">4</td>\n<td headers=\"n\" class=\"gt_row gt_right\">85</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nIn `bladder`, in the Wei-Lin-Weissfeld format, each subject has four records, regardless of how many events that subject actually experienced. In addition, there is no `start` variable, as all time intervals start at zero.\n\n[**Note:**]{.underline} The variables **id**, **start** and **stop** were renamed to **subjid**, **tstart** and **tstop** to avoid using SAS key words as variable names.\n\n### Analysis\n\nIn SAS, any survival analysis based on the Cox proportional hazard model can be conducted using the `phreg` procedure. Hence, conveniently, when modelling time-to-event data with recurrent events, the same procedure can be used. The caveat here is that an adequate data structure is required, which must be in correspondence with the model you want to use.\n\nIn this section of the tutorial, we will explain how the arguments of the `phreg` procedure and data structure must be defined to fit every type of recurrent event model correctly.\n\n#### Andersen-Gill model\n\n1.  **Improved Andersen-Gill model (LWYY model or proportional means/rates model)**\n\nFor the improved version of the Andersen-Gill model you must include:\n\n-   `proc phreg data=bladder2 covs(aggregate)`\n-   `model (tstart, tstop) * event(0) = 'predictors';`\n-   `id subjid;`\n\nAnd the data structure must be:\n\n| Subjid | Time interval | Tstart | Tstop | Event |\n|--------|---------------|--------|-------|-------|\n| 1      | (0, 1\\]       | 0      | 1     | 0     |\n| 2      | (0, 4\\]       | 0      | 4     | 0     |\n| 3      | (0, 7\\]       | 0      | 7     | 0     |\n| 4      | (0, 10\\]      | 0      | 10    | 0     |\n| 5      | (0, 6\\]       | 0      | 6     | 1     |\n| 5      | (6, 10\\]      | 6      | 10    | 0     |\n\nWe will use the `bladder2` data for this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder2 covs(aggregate);\n\tclass rx (ref='1');\n\tmodel (tstart, tstop) * event(0) = rx size number /rl;\n\tid subjid;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_AG.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nBy including the `covs(aggregate)` option and setting `id subjid;`, SAS will compute a robust sandwich covariance and display robust standard error estimates in the output. Under the hood, the robust standard errors will consider all **subjid** clusters separately and ultimately sum up the score residuals for each distinct cluster.\n\n2.  **Original Andersen-Gill model**\n\nThe original Andersen-Gill model of 1989 can be fitted by changing `covs(aggregate)` to `covs` in the procedure, while excluding `id subjid;`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder2 covs;\n\tclass rx (ref='1');\n\tmodel (tstart, tstop) * event(0) = rx size number /rl;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_AG_original.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nAlthough the original Andersen-Gill model does not consider separate **subjid** clusters, it still computes robust standard errors using the sandwich estimator. The resulting robust standard errors (`robust se`) differ from those provided for the improved Andersen-Gill model, while the estimated coefficients (`coef`) remain perfectly unchanged.\n\n#### Prentice-Williams-Peterson model\n\n**Total time model**\n\nFor the Prentice-Williams-Peterson total time model you must include:\n\n-   `proc phreg data=bladder2 covs(aggregate);`\n-   `model (tstart, tstop) * event(0) = 'predictors';`\n-   `id subjid;`\n-   `strata enum;`\n\nAnd the data structure must be:\n\n| Subjid | Time interval | Tstart | Tstop | Event | Enum |\n|--------|---------------|--------|-------|-------|------|\n| 1      | (0, 1\\]       | 0      | 1     | 0     | 1    |\n| 2      | (0, 4\\]       | 0      | 4     | 0     | 1    |\n| 3      | (0, 7\\]       | 0      | 7     | 0     | 1    |\n| 4      | (0, 10\\]      | 0      | 10    | 0     | 1    |\n| 5      | (0, 6\\]       | 0      | 6     | 1     | 1    |\n| 5      | (6, 10\\]      | 6      | 10    | 0     | 2    |\n\nWe will use the `bladder2` data for this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder2 covs(aggregate);\n\tclass rx (ref='1');\n\tmodel (tstart, tstop) * event(0) = rx size number /rl; \n\tid subjid;\n\tstrata enum;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_PWPtt.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nThe conditional strata of the Prentice-Williams-Peterson model are set by `strata enum;` in the formula, where `enum` captures the ordering of recurrent events.\n\n**Gap time model**\n\nFor the Prentice-Williams-Peterson gap time model you must include:\n\n-   `proc phreg data=bladder2 covs(aggregate);`\n-   `model gtime * event(0) = 'predictors';`\n-   `id subjid;`\n-   `strata enum;`\n\nAnd the data structure must be:\n\n| Subjid | Time interval | Tstart | Tstop | Event | Enum |\n|--------|---------------|--------|-------|-------|------|\n| 1      | (0, 1\\]       | 0      | 1     | 0     | 1    |\n| 2      | (0, 4\\]       | 0      | 4     | 0     | 1    |\n| 3      | (0, 7\\]       | 0      | 7     | 0     | 1    |\n| 4      | (0, 10\\]      | 0      | 10    | 0     | 1    |\n| 5      | (0, 6\\]       | 0      | 6     | 1     | 1    |\n| 5      | (0, 4\\]       | 0      | 4     | 0     | 2    |\n\nThis data structure can be achieved in `bladder2` by adding a `gtime` variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata bladder2;\n\tset bladder2;\n\tgtime = tstop - tstart;\nrun;\n```\n:::\n\n\n\nWe artificially set start = 0 for each gap time interval by including `gtime` instead of `(start, stop)` in the `model` statement.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder2 covs(aggregate);\n\tclass rx (ref='1');\n\tmodel gtime * event(0) = rx size number/rl; \n\tid subjid;\n\tstrata enum;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_PWPgt.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n#### Wei-Lin-Weissfeld model\n\nFor the Wei-Lin-Weissfeld model you must include:\n\n-   `proc phreg data=bladder covs(aggregate);`\n-   `model tstop * event(0) = 'predictors';`\n-   `id subjid;`\n-   `strata enum;`\n\nAnd the data structure must be:\n\n| Subjid | Time interval | Tstart | Tstop | Event | Enum |\n|--------|---------------|--------|-------|-------|------|\n| 1      | (0, 1\\]       | 0      | 1     | 0     | 1    |\n| 1      | (0, 1\\]       | 0      | 1     | 0     | 2    |\n| 1      | (0, 1\\]       | 0      | 1     | 0     | 3    |\n| 1      | (0, 1\\]       | 0      | 1     | 0     | 4    |\n| 2      | (0, 4\\]       | 0      | 4     | 0     | 1    |\n| 2      | (0, 4\\]       | 0      | 4     | 0     | 2    |\n| 2      | (0, 4\\]       | 0      | 4     | 0     | 3    |\n| 2      | (0, 4\\]       | 0      | 4     | 0     | 4    |\n| 3      | (0, 7\\]       | 0      | 7     | 0     | 1    |\n| 3      | (0, 7\\]       | 0      | 7     | 0     | 2    |\n| 3      | (0, 7\\]       | 0      | 7     | 0     | 3    |\n| 3      | (0, 7\\]       | 0      | 7     | 0     | 4    |\n| 4      | (0, 10\\]      | 0      | 10    | 0     | 1    |\n| 4      | (0, 10\\]      | 0      | 10    | 0     | 2    |\n| 4      | (0, 10\\]      | 0      | 10    | 0     | 3    |\n| 4      | (0, 10\\]      | 0      | 10    | 0     | 4    |\n| 5      | (0, 6\\]       | 0      | 6     | 1     | 1    |\n| 5      | (0, 10\\]      | 0      | 10    | 0     | 2    |\n| 5      | (0, 10\\]      | 0      | 10    | 0     | 3    |\n| 5      | (0, 10\\]      | 0      | 10    | 0     | 4    |\n\nWe will use the `bladder` data for this.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder covs(aggregate);\n\tclass rx (ref='1');\n\tmodel tstop * event(0) = rx size number /rl;\n\tid subjid;\n  strata enum;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_WLW.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\nImportantly, the strata of the Wei-Lin-Weissfeld model as set by `strata enum;` are substantially different from the conditional strata of the Prentice-Williams-Peterson model. The `enum` variable is now no longer assumed to be an ordinal variable.\n\n#### Notes\n\n[**Note:**]{.underline} The `rl` option ensures the 95% confidence interval for the hazard ratio is displayed.\n\n[**Note:**]{.underline} If you want to display non-robust, model-based standard errors (like the ones given by default in R), you can do this by adding `covm` to the procedure statement.\n\n[**Note:**]{.underline} It may be useful to look at the **Summary of the Number of Event and Censored Values** to check whether the data stratification was rightly specified for your model. Examples for the Prentice-Williams-Peterson and Wei-Lin-Weissfeld models are given below.\n\nSummary for Prentice-Williams-Peterson models:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_PWP_structure.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\nSummary for Wei-Lin-Weissfeld model:\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_WLW_structure.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n[**Note:**]{.underline} R uses `ties = \"efron\"` by default, while SAS uses `ties = breslow` by default. If this argument remains unchanged in both software, it can cause differences in outcome. For more information, be sure to check the [CAMIS webpage](https://psiaims.github.io/CAMIS/Comp/r-sas_survival.html) on the comparison of Cox proportional hazards models in R and SAS.\n\n### Interpretation\n\nIn terms of interpretation, hazard ratios ($\\exp(\\beta_j)$) are often used when making inferences based on Cox proportional hazards models. Now, as you may remember from the overview presented earlier, it is important to recognize that each of the recurrent event models comes with a slightly different interpretation of the hazard ratio, as defined by the assumptions around the model.\n\n|   | **AG** | **PWPtt** | **PWPgt** | **WLW** |\n|---------------|---------------|---------------|---------------|---------------|\n| **Hazard ratio (HR)** | risk of any recurrence | risk of any recurrence | risk of recurrence after previous event | risk of event of any type, not necessarily recurrent event |\n\nThis means that, for the `bladder` data, we can draw slightly different conclusions on the hazard ratio of the group treated with thiotepa (**rx** = 2) versus the placebo group (**rx** = 1).\n\n| Model       | HR: rx2 vs rx1 | 95% CI         | P-value |\n|-------------|----------------|----------------|---------|\n| AG          | 0.631          | 0.381 to 1.047 | 0.0747  |\n| Original AG | 0.631          | 0.403 to 0.989 | 0.0447  |\n| PWPtt       | 0.716          | 0.486 to 1.053 | 0.0898  |\n| PWPgt       | 0.764          | 0.508 to 1.148 | 0.1952  |\n| WLW         | 0.560          | 0.309 to 1.015 | 0.0560  |\n\nThese conclusions are:\n\n-   **Andersen-Gill**: the risk of having *any new tumor recurrence* in the treatment group is 0.631 (0.381 - 1.047) times that of the placebo group\n\n-   **Prentice-Williams-Peterson: total time**: the risk of having *any new tumor recurrence* in the treatment group is 0.716 (0.486 - 1.053) times that of the placebo group\n\n-   **Prentice-Williams-Peterson: gap time**: the risk of having *a new tumor recurrence after a previous event* in the treatment group is 0.764 (0.508 - 1.148) times that of the placebo group\n\n-   **Wei-Lin-Weissfeld**: the risk of having *any type of event* in the treatment group is 0.560 (0.309 - 1.015) times that of the placebo group\n\n[**Note:**]{.underline} The improved Andersen-Gill model (LWYY model or proportional means/rates model) is preferred over the original Andersen-Gill model.\n\n### Event-specific estimates\n\nFor the Prentice-Williams-Peterson and Wei-Lin-Weissfeld models we can incorporate both overall ($\\beta$) and event-specific ($\\beta_j$) effects for each covariate. To arrive at pooled model parameters these models assume that $\\beta_1 = \\beta_2 = ... = \\beta_k = \\beta$. Until now, we have only considered pooled model parameters, but given the underlying stratification of these two models in particular, it may be valuable to look into the event-specific estimates as well ([Amorim & Cai 2015](https://pubmed.ncbi.nlm.nih.gov/25501468/)).\n\nTo get event-specific estimates for the treatment effect (**rx**), we first need to introduce four new **rx** variables to the `bladder2` and `bladder` datasets, one for each stratum.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata bladder2;\n\tset bladder2;\n\trx_enum1 = rx*(enum=1);\n\trx_enum2 = rx*(enum=2);\n\trx_enum3 = rx*(enum=3);\n\trx_enum4 = rx*(enum=4);\nrun;\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata bladder;\n\tset bladder;\n\trx_enum1 = rx*(enum=1);\n\trx_enum2 = rx*(enum=2);\n\trx_enum3 = rx*(enum=3);\n\trx_enum4 = rx*(enum=4);\nrun;\n```\n:::\n\n\n\nWith these four interaction variables, we specify `rx_enum1-rx_enum4` in the formula and set `class enum / param=glm;` to output the event-specific estimates.\n\n#### Prentice-Williams-Peterson model\n\n**Total time model**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder2 covs(aggregate);\n\tclass enum / param=glm;\n\tmodel (tstart, tstop) * event(0) = rx_enum1-rx_enum4 size number /rl; \n\tid subjid;\n\tstrata enum;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_PWPtt_stratified.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n**Gap time model**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder2 covs(aggregate);\n\tclass enum / param=glm;\n\tmodel gtime * event(0) = rx_enum1-rx_enum4 size number/rl; \n\tid subjid;\n\tstrata enum;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_PWPgt_stratified.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n#### Wei-Lin-Weissfeld model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproc phreg data=bladder covs(aggregate);\n\tclass enum / param=glm;\n\tmodel tstop * event(0) = rx_enum1-rx_enum4 size number /rl;\n\tid subjid;\n  strata enum;\nrun;\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../images/recurrent_events/SAS_WLW_stratified.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## References\n\n[Amor 2023](https://www.lexjansen.com/phuse/2023/as/PAP_AS05.pdf). Eat, Sleep, R, Repeat.\n\n[Amorim & Cai 2015](https://pubmed.ncbi.nlm.nih.gov/25501468/). Modelling recurrent events: a tutorial for analysis in epidemiology. *International Journal of Epidemiology*. 2015 Feb;44(1):324-33.\n\n[Andersen & Gill 1982](https://www.jstor.org/stable/2240714). Cox’s Regression Model for Counting Processes: A Large Sample Study. *The Annals of Statistics*. 10(4):1100–1120.\n\n[bladder data](https://rdrr.io/cran/survival/man/bladder.html)\n\n[Lu & Shen 2018](https://www.lexjansen.com/pharmasug/2018/EP/PharmaSUG-2018-EP02.pdf). Application of Survival Analysis in Multiple Events Using SAS. *PharmaSUG 2018*.\n\n[Ozga et al. 2018](https://pubmed.ncbi.nlm.nih.gov/29301487/). A systematic comparison of recurrent event models for application to composite endpoints. *BMC Medical Research Methodoly*. 2018 Jan 4;18(1):2.\n\n[Prentice, Williams & Peterson 1981](https://www.jstor.org/stable/2335582). On the Regression Analysis of Multivariate Failure Time Data. *Biometrika*. 68(2):373–379.\n\n[survival package](https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf)\n\n[Wei, Lin & Weissfeld 1989](https://www.jstor.org/stable/2290084). Regression Analysis of Multivariate Incomplete Failure Time Data by Modeling Marginal Distributions. *Journal of the American Statistical Association*. 84(408):1065–1073.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}