{
  "hash": "0c96fee623e8a0e77d199a3057968490",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Kruskal Wallis R\"\n---\n\n\n\n## Introduction\n\nThe Kruskal-Wallis test is a non-parametric equivalent to the one-way ANOVA. For this example, the data used is a subset of datasets::iris, testing for difference in sepal width between species of flower.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n      Species Sepal_Width\n1      setosa         3.4\n2      setosa         3.0\n3      setosa         3.4\n4      setosa         3.2\n5      setosa         3.5\n6      setosa         3.1\n7  versicolor         2.7\n8  versicolor         2.9\n9  versicolor         2.7\n10 versicolor         2.6\n11 versicolor         2.5\n12 versicolor         2.5\n13  virginica         3.0\n14  virginica         3.0\n15  virginica         3.1\n16  virginica         3.8\n17  virginica         2.7\n18  virginica         3.3\n```\n\n\n:::\n:::\n\n\n\n## Implementing Kruskal-Wallis in R\n\nThe Kruskal-Wallis test can be implemented in R using stats::kruskal.test. Below, the test is defined using R's formula interface (dependent \\~ independent variable) and specifying the data set. The null hypothesis is that the samples are from identical populations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(Sepal_Width~Species, data=iris_sub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  Sepal_Width by Species\nKruskal-Wallis chi-squared = 10.922, df = 2, p-value = 0.004249\n```\n\n\n:::\n:::\n\n\n\n## Results\n\nAs seen above, R outputs the Kruskal-Wallis rank sum statistic (10.922), the degrees of freedom (2), and the p-value of the test (0.004249). Therefore, the difference in population medians is statistically significant at the 5% level.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}