------------------------------------------------------------------------

title: "<SAS/R/SAS vs R> <method name>"

------------------------------------------------------------------------

**Note:** Your choice to use part or all to fit your topic

## R package versions

R 4.3.1\
mmrm 0.2.2

**Note:** If there is only one available package this can be deleted. Otherwise please make a short list, paragraph or table. If there is a reason to use one package vs another please include it. Please make sure to include what version of the packages you are using

## Data used

```{eval = FALSE}
data ExData; 
    input Var1 $ Var2 ...; 
    datalines; 
[Data Lines]; 
run; 
```

```{r}
exData <- tibble::tribble( 
  ~Var1, ~Var2, 
  "val1", 1, 
  "val2", 2) 
```

**Note:** a sentence or two about the data. Consider using a package like {skimr} to help illustrate the data.

## Example Code using {package name}

**Note:** Describe more details about the method.\
If needed, add link to other web page/paper/SAS help methodology page, and list them in reference section.\
Print key results as needed.\
Add explanations about code and results as needed.

## Example Code using {another package name}

**Note:** Add if there is more than one package

## Comparison

**Note:** If you are comparing more than one package or between different languages, consider adding in a table to illustrate some of the differences. When comparing between languages it can be nice to have a table with links to the pages with deeper dive of each language for a given method method like this table from the ANCOVA page:

| Analysis                                      | Supported in R          | Supported in SAS          | Results Match | Notes                                                                                    |
|---------------|---------------|---------------|---------------|---------------|
| ANCOVA using general linear model and lsmeans | [Yes](../R/ancova.html) | [Yes](../SAS/ancova.html) | [Yes](#comp)  | `GLM()` function from **sasLM** with `EMEANS=TRUE` is the easiest to use and matches SAS |

**Note:** But, even if you are just comparing the difference in same language it can be helpful to have a table with values of interest across different packages. Using dynamic content you can add the values to a table without manually putting in each value.\
SAS result is very reliable in many cases.

## Conclusion

**Note:** add a conclusion about which language(s) or package(s) are more recommended.\
This section could have a feature like paper abstract, e.g. about the selection of package or SAS PROC.

## Reference

**Note:** Cite all sources and references used in the analysis.
