---
title: "ANOVA"
---

## Introduction

Analysis of VAriance *(ANOVA)* is a statistical test to measure the difference between means of more than two groups.It is best suited when the data is normally distributed. By partitioning total variance into components, ANOVA unravels relationship between variables and identifies the true source of variation. It can handle multiple factors and their interactions, providing a robust way to better understand intricate relationships.

## Anova Test in Python

To perform a one-way ANOVA test in Python we can use the **f_oneway()** function from SciPy library.
Similarly, to perform two-way ANOVA test **anova_lm()** function from the statsmodel library is frequently used.

For this test, we’ll create a data frame called df_disease taken from the SAS documentation. The corresponding data can be found [here](https://github.com/PSIAIMS/CAMIS/blob/main/data/sas_disease.csv). In this experiment, we are trying to find the impact of   different drug and disease group on the `stem-length`  

```{python}
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Read the sample data
df = pd.read_csv("../data/sas_disease.csv")


#perform two-way ANOVA
model = ols('y ~ C(drug) + C(disease) + C(drug):C(disease)', data=df).fit()
sm.stats.anova_lm(model, typ=2)

```

