---
title: "Get Started with CAMIS"
---

## How to get involved

CAMIS is a community effort. Although this project does have a core team, the endeavor of tracking all these comparisons will fail without community contributions. We appreciate all contributions, big or small!

You can get involved in the following ways:

-   join our monthly online meetings by completing the [new members form](https://forms.office.com/Pages/ResponsePage.aspx?id=xeEJLj1cykuXxFc6VpX1UKYKFE6i0SdEjGxMC4fPoj9UQUJTQUpZVFlHOUxYUUVFWllUTlJUS0RUOS4u)
-   **report a difference** or request a new method by [filing an issue](https://github.com/PSIAIMS/CAMIS/issues/)
-   contribute to our documentation

## First-time contributors

Welcome to CAMIS! Please read this article: [Get started](get_started.qmd), which contains some useful information to help you navigate your first PR submission.

## How to contribute to the documentation

Please contribute by **submitting a pull request** (PR) and our team will review it.

### Adding a new page

If you are adding a new page, please follow our template guidelines:

-   [Single Language Template](../templates/single_language_template.qmd)

-   [Comparing Languages Template](../templates/multi_language_template.qmd)

Good documentation on data, methods are very much appreciated!

### Asking for help

If you need any assistance with setting up your workspace, do not hesitate to contact [\@DrLynTaylor](https://github.com/DrLynTaylor), [\@statasaurus](https://github.com/statasaurus), [\@chizapoth](https://github.com/chizapoth) or  [\@yannickvandendijck](https://github.com/yannickvandendijck)! For more information about how to choose an R package read this [short guidance](package_review.qmd)

## Dissertation projects

Are you:

-   a **student** looking for a dissertation project?
-   an **academic** looking for projects for your students?
-   a researcher who wants to partner with a university and student to help progress your research?

If so, check out [this page](https://psiaims.github.io/CAMIS/publication/dissertation.html), and contact [\@DrLynTaylor](https://github.com/DrLynTaylor) for more information.
