---
title: "Dissertation projects"
---

CAMIS have a number of dissertation projects which are likely to be suitable for MSc or BSc dissertation projects that are part of a Statistical degree.

This content will be useful for you, if you are:

-   a **student** looking for a dissertation project?
-   an **academic** looking for projects for your students?
-   a **researcher** (academic or industry) who wants to partner with a university and student to help progress your research?

### Available proposals

If you are interested in working on one of these projects, please reach out for more information.

Available dissertation projects proposals (further information pending)

-   Max-Combo
-   Multivariate methods

### Ongoing and Previously Completed projects

[MMRM - Ongoing](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content/dissertations/202406_MMRM.qmd)

Conversion of MSc Statistics Course notes from R to SAS to be used for English Medical Statistician Apprenticeship scheme - Completed 2022

### New proposals

If you have an idea for a future proposal, please feel free to tell us what you are interested in!

#### Contact

Lyn @DrLynTaylor
