---
title: "Publications"
---

# Whitepaper

**Key Considerations When Understanding Differences in Statistical Methodology Implementations Across Programming Languages - An Introduction to the CAMIS Project**

Read the whitepaper [here](https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Data+Visualisation+%26+Open+Source+Technology/WP077.pdf)

# Conference presentations

### 2024 Conference Schedule

List of seminars and conferences that the CAMIS team will be attending in 2024.

If you are a volunteer on the CAMIS project and plan to present at a seminar or conference, please add details of the conference below. For help with slides or content go to [HERE](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content/conferences).

To cite the CAMIS project work in online content or presentations please use: "Content reproduced with the permission of [PHUSE CAMIS](https://advance.phuse.global/pages/viewpage.action?pageId=327874) - A DVOST Working Group".

| Conference name         | Date (2024) | Location                    | Name Attending                                      | Details                                                                                                                                                                                                                                            | Website                                                                                                                                                          |
|------------|:-----------|:-----------|:-----------|:-----------|:-----------|
| RSS Local Group Seminar | 28 Feb      | Sheffield, England          | Lyn Taylor                                          | [Slides](../non_website_content/conferences/2024/RSS_Local_Group_28Feb2024_FINAL.pptx)                                                                                                                                                             | [RSS](https://rss.org.uk/training-events/events/events-2024/local-groups/medical-statistician-apprenticeships-and-integrati/)                                    |
| phuse US Connect        | 25-28 Feb   | Bethesa, Maryland, USA      | Soma Sekhar Sriadibhatla, Vikash Jain, Brian Varney | [Poster](../non_website_content/conferences/2024/PHUSE%20US%20Connect%20PP26%20SomaSekhar%20Sriadibhatla%20Feb%202024.pdf)                                                                                                                         | [Connect](https://www.cdisc.org/events/education/external-events/2024/02/phuse-us-connect-2024)                                                                  |
| phuse chapter connect   | 03 APR      | Bangalore                   | Harshal Khanolkar                                   |                                                                                                                                                                                                                                                    |                                                                                                                                                                  |
| phuse/FDA CSS           | 3-5 June    | Silver Spring Maryland, USA | Mike Stackhouse                                     | CAMIS Discussion                                                                                                                                                                                                                                   | [CSS](https://advance.phuse.global/pages/viewpage.action?pageId=80806741)                                                                                        |
| R/Medicine              | 10-14 June  | Online                      | Agnieszka Tomczyk, Lyn Taylor                       | [Part1](../non_website_content/conferences/2024/R_medicine_2024_CAMIS_Part1.mp4) and [Part2](../non_website_content/conferences/2024/R_medicine_2024_CAMIS_Part2.mp4) and [slides](../non_website_content/conferences/2024/R_medicine_2024_Final.pptx) | [R/Medicine 2024](https://rconsortium.github.io/RMedicine_website/)                                                                                              |
| UseR!                   | 8-11 July   | Salzburg, Austria           | Chi Zhang                                           | Presentation                                                                                                                                                                                                                                       | [useR! 2024](https://events.linuxfoundation.org/user/)                                                                                                           |
| phuse EU                | 11-13 Nov   | Strasbourg, France          | Agnieszka Tomczyk, Christina Fillmore               | Presentation                                                                                                                                                                                                                                       | [PHUSE EU Connect](https://www.phuse-events.org/attend/frontend/reg/thome.csp?pageID=28735&eventID=45&CSPCHD=000001000000HvvZvjPfObTmLBcfyVmqir0yUlNgKAUCOlcgKn) |

### Yearly Conference Planner

To help to plan our attendance throughout the year, here is a list of conferences we are looking to send representation to. If you plan to attend one of these conferences and are interested in representing us, then please get in touch.

| Conference name                                                         | Usual Abstract Deadline | Usual Conference Date  | Region        | Links                                                                                                                                                            |
|---------------|:--------------|:--------------|:--------------|:--------------|
| Joint Statistical Meetings (JSM) American Statistical Association (ASA) | 1st February            | 1st week of August     | USA           | [JSM-ASA](https://www.amstat.org/meetings/joint-statistical-meetings)                                                                                            |
| ASA Biopharmaceutical Section Regulatory-Industry Statistics workshop   | End March               | Last week of September | USA           | [BIOP](https://www.amstat.org/meetings/asa-biopharmaceutical-section-regulatory-industry-statistics-workshop)                                                    |
| Phuse US Connect                                                        | November                | Last week of Feb       | USA           | [CDISC](https://www.cdisc.org/events)                                                                                                                            |
| Phuse/FDA Computational Science Symposium(CSS)                          | December                | 1st week of June       | USA           | [CSS](https://advance.phuse.global/display/WEL/Working+Group+Events)                                                                                             |
| IASCT (ConSPIC)                                                         | Mid March               | Early May              | India         | [IASCT](https://www.iasct.net/)                                                                                                                                  |
| Society of Clinical Trials (SCT)                                        | January                 | Mid May                | USA           | [SCT](https://sctweb.org/)                                                                                                                                       |
| PharmaSUG                                                               | Mid Jan                 | Mid May                | USA           | [PharmaSUG](https://www.pharmasug.org/)                                                                                                                          |
| useR                                                                    | Early March             | Early July             | Europe/Online | [useR](https://user2024.r-project.org/)                                                                                                                          |
| PSI                                                                     | Nov-oral, Feb-Poster    | Mid June               | Europe        | [PSI](https://psiweb.org/)                                                                                                                                       |
| DIA Global                                                              | End Feb-poster          | Mid June               | USA           | [DIA-USA](https://www.diaglobal.org/en/conference-listing/annual-meetings)                                                                                       |
| DIA Europe                                                              | Nov                     | Mid March              | Europe        | [DIA-Europe](https://www.diaglobal.org/en/conference-listing/annual-meetings)                                                                                    |
| DIA China                                                               | Jan                     | Mid May                | China         | [DIA-China](https://www.diaglobal.org/en/conference-listing/annual-meetings)                                                                                     |
| International Society for Clinical Biostatistics (ISCB)                 | Mid Feb                 | Mid July               | Europe        | [ISCB](https://iscb.international/)                                                                                                                              |
| Royal Statistical Society (RSS)                                         | Early April             | Early September        | England       | [RSS](https://rss.org.uk/)                                                                                                                                       |
| SouthEast SAS User Group (SESUG)                                        | End Feb                 | End Sept               | Maryland, USA | [SESUG](https://www.sesug.org/)                                                                                                                                  |
| PHUSE EU Connect                                                        | Mid March               | Mid Nov                | Europe        | [PHUSE EU Connect](https://www.phuse-events.org/attend/frontend/reg/thome.csp?pageID=28735&eventID=45&CSPCHD=000001000000HvvZvjPfObTmLBcfyVmqir0yUlNgKAUCOlcgKn) |
| R/Pharma                                                                | April                   | Mid October            | Virtual       | [R/pharma](https://rinpharma.com/)                                                                                                                               |
| POSIT conf.                                                             | Invite only             | September              | USA           | [POSIT conf](https://posit.co/conference/)                                                                                                                       |
