{
  "hash": "f42ab9d5d864f2bc9cfc895f05d9f674",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"<R> <Tobit Regression>\"\n---\n\n\n\n# Tobit regression\n\n## Libraries\n\n### General\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(gt)\nlibrary(broom)\n```\n:::\n\n\n\n### Methodology specific\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\nlibrary(censReg)\nlibrary(survival)\nlibrary(VGAM)\n```\n:::\n\n\n\n\n## Tobit model\n\nCensoring occurs when data on the dependent variable is only partially known. For example, in virology, sample results could be below the lower limit of detection (eg, 100 copies/mL) and in such a case we only know that the sample result is <100 copies/mL, but we don't know the exact value.\n\nLet $y^{*}$ be the the true underlying latent variable, and $y$ the observed variable. We discuss here censoring on the left:\n\n$$\ny =\n\\begin{cases}\n y^{*}, & y^{*} > \\tau  \\\\\n \\tau, & y^{*} \\leq \\tau\n \\end{cases}       \n$$\nWe consider tobit regression with a censored normal distribution. The model equation is\n$$\ny_{i}^{*} = X_{i}\\beta + \\epsilon_{i} \n$$\nwith $\\epsilon_{i} \\sim N(0,\\sigma^2)$. But we only observe $y = max(\\tau, y^{*})$.\nThe tobit model uses maximum likelihood estimation (for details see for example Breen, 1996). It is important to note that $\\beta$ estimates the effect of $x$ on the latent variable $y^{*}$, and not on the observed value $y$.\n\n\n## Data used\n\nWe assume two equally sized groups (n=10 in each group). The data is censored on the left at a value of $\\tau=8.0$.\nIn group A 4/10 records are censored, and 1/10 in group B.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_used = tribble(\n  ~ID, ~ARM, ~Y, ~CENS,\n  \"001\", \"A\", 8.0, 1, \n  \"002\", \"A\", 8.0, 1,\n  \"003\", \"A\", 8.0, 1,\n  \"004\", \"A\", 8.0, 1,\n  \"005\", \"A\", 8.9, 0,\n  \"006\", \"A\", 9.5, 0,\n  \"007\", \"A\", 9.9, 0,\n  \"008\", \"A\", 10.3, 0,\n  \"009\", \"A\", 11.0, 0,\n  \"010\", \"A\", 11.2, 0,\n  \"011\", \"B\", 8.0, 1, \n  \"012\", \"B\", 9.2, 0,\n  \"013\", \"B\", 9.9, 0,\n  \"014\", \"B\", 10.0, 0,\n  \"015\", \"B\", 10.6, 0,\n  \"016\", \"B\", 10.6, 0,\n  \"017\", \"B\", 11.3, 0,\n  \"018\", \"B\", 11.8, 0,\n  \"019\", \"B\", 12.9, 0,\n  \"020\", \"B\", 13.0, 0,\n)\n\ngt(dat_used)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zzouvalyhm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zzouvalyhm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zzouvalyhm thead, #zzouvalyhm tbody, #zzouvalyhm tfoot, #zzouvalyhm tr, #zzouvalyhm td, #zzouvalyhm th {\n  border-style: none;\n}\n\n#zzouvalyhm p {\n  margin: 0;\n  padding: 0;\n}\n\n#zzouvalyhm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zzouvalyhm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zzouvalyhm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zzouvalyhm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zzouvalyhm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zzouvalyhm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zzouvalyhm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zzouvalyhm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zzouvalyhm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zzouvalyhm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zzouvalyhm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zzouvalyhm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zzouvalyhm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zzouvalyhm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zzouvalyhm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzouvalyhm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zzouvalyhm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zzouvalyhm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zzouvalyhm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzouvalyhm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zzouvalyhm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzouvalyhm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zzouvalyhm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzouvalyhm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zzouvalyhm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zzouvalyhm .gt_left {\n  text-align: left;\n}\n\n#zzouvalyhm .gt_center {\n  text-align: center;\n}\n\n#zzouvalyhm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zzouvalyhm .gt_font_normal {\n  font-weight: normal;\n}\n\n#zzouvalyhm .gt_font_bold {\n  font-weight: bold;\n}\n\n#zzouvalyhm .gt_font_italic {\n  font-style: italic;\n}\n\n#zzouvalyhm .gt_super {\n  font-size: 65%;\n}\n\n#zzouvalyhm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zzouvalyhm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zzouvalyhm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zzouvalyhm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zzouvalyhm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zzouvalyhm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zzouvalyhm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zzouvalyhm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zzouvalyhm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ID\">ID</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ARM\">ARM</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Y\">Y</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CENS\">CENS</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">001</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">8.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">002</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">8.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">003</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">8.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">004</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">8.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">005</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">8.9</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">006</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">9.5</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">007</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">9.9</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">008</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">10.3</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">009</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">11.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">010</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">A</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">11.2</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">011</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">8.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">012</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">9.2</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">013</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">9.9</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">014</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">10.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">015</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">10.6</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">016</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">10.6</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">017</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">11.3</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">018</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">11.8</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">019</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">12.9</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"ID\" class=\"gt_row gt_right\">020</td>\n<td headers=\"ARM\" class=\"gt_row gt_left\">B</td>\n<td headers=\"Y\" class=\"gt_row gt_right\">13.0</td>\n<td headers=\"CENS\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n## Example Code using R\n\nThe analysis will be based on a Tobit analysis of variance with $Y$, rounded to 1 decimal places, as dependent variable and study group as a fixed covariate. A normally distributed error term will be used. Values will be left censored at the value 8.0.\n\nSeveral R functions and packages are presented.\n\n### censReg\nThe `censReg` function from the `censReg` package performs tobit models for left and right censored. The model is estimated by Maximum Likelihood (ML) assuming a Gaussian (normal) distribution of the error term. The maximization of the likelihood function is done by function `maxLik` of the `maxLik` package. The optimization method can be changed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_censreg = censReg(Y ~ ARM, \n                      left = 8.0, \n                      data = dat_used)\nsummary(res_censreg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ncensReg(formula = Y ~ ARM, left = 8, data = dat_used)\n\nObservations:\n         Total  Left-censored     Uncensored Right-censored \n            20              5             15              0 \n\nCoefficients:\n            Estimate Std. error t value Pr(> t)    \n(Intercept)   8.8323     0.5918  14.925 < 2e-16 ***\nARMB          1.8225     0.8061   2.261 0.02376 *  \nlogSigma      0.5491     0.1947   2.819 0.00481 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nNewton-Raphson maximisation, 4 iterations\nReturn code 1: gradient close to zero (gradtol)\nLog-likelihood: -34.3154 on 3 Df\n```\n\n\n:::\n\n```{.r .cell-code}\n# Difference between groups (Wald CIs)\nround(res_censreg$estimate[2], 3) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ARMB \n1.823 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(stats::confint(res_censreg, level = 0.95)[2,], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n 0.243  3.402 \n```\n\n\n:::\n:::\n\n\nThe output provides an estimate of difference between groups A and B (B-A), namely 1.8225 (se=0.8061). The presented p-value is a two-sided p-value based on the Z-test. The output also provides an estimate for $log(\\sigma) = 0.5491$. Wald based confidence intervals can be obtained by the `stats::confint` function.\n\n\n\n### survreg\nUsing the `survreg` function from the `survival` package a tobit model can be fit. For more information, refer to the [survival package](https://cran.r-project.org/web/packages/survival/index.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_survreg = survreg(Surv(Y, 1-CENS, type=\"left\") ~ ARM,\n                      dist = \"gaussian\",\n                      data = dat_used)\nsummary(res_survreg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nsurvreg(formula = Surv(Y, 1 - CENS, type = \"left\") ~ ARM, data = dat_used, \n    dist = \"gaussian\")\n            Value Std. Error     z      p\n(Intercept) 8.832      0.592 14.92 <2e-16\nARMB        1.823      0.806  2.26 0.0238\nLog(scale)  0.549      0.195  2.82 0.0048\n\nScale= 1.73 \n\nGaussian distribution\nLoglik(model)= -34.3   Loglik(intercept only)= -36.7\n\tChisq= 4.72 on 1 degrees of freedom, p= 0.03 \nNumber of Newton-Raphson Iterations: 4 \nn= 20 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Least square means by group\nlsm = emmeans(res_survreg, specs = trt.vs.ctrl ~ ARM)\nlsm$emmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ARM emmean    SE df lower.CL upper.CL\n A     8.83 0.592 17     7.58     10.1\n B    10.65 0.552 17     9.49     11.8\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Difference between groups\nlsm_contrast = broom::tidy(lsm$contrasts, conf.int=TRUE, conf.level=0.95)\ngt(lsm_contrast) %>%\n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rwvfrehsqq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rwvfrehsqq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rwvfrehsqq thead, #rwvfrehsqq tbody, #rwvfrehsqq tfoot, #rwvfrehsqq tr, #rwvfrehsqq td, #rwvfrehsqq th {\n  border-style: none;\n}\n\n#rwvfrehsqq p {\n  margin: 0;\n  padding: 0;\n}\n\n#rwvfrehsqq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rwvfrehsqq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rwvfrehsqq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rwvfrehsqq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rwvfrehsqq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rwvfrehsqq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rwvfrehsqq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rwvfrehsqq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rwvfrehsqq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rwvfrehsqq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rwvfrehsqq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rwvfrehsqq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rwvfrehsqq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rwvfrehsqq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rwvfrehsqq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwvfrehsqq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rwvfrehsqq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rwvfrehsqq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rwvfrehsqq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwvfrehsqq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rwvfrehsqq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwvfrehsqq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rwvfrehsqq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwvfrehsqq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rwvfrehsqq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwvfrehsqq .gt_left {\n  text-align: left;\n}\n\n#rwvfrehsqq .gt_center {\n  text-align: center;\n}\n\n#rwvfrehsqq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rwvfrehsqq .gt_font_normal {\n  font-weight: normal;\n}\n\n#rwvfrehsqq .gt_font_bold {\n  font-weight: bold;\n}\n\n#rwvfrehsqq .gt_font_italic {\n  font-style: italic;\n}\n\n#rwvfrehsqq .gt_super {\n  font-size: 65%;\n}\n\n#rwvfrehsqq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rwvfrehsqq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rwvfrehsqq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rwvfrehsqq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rwvfrehsqq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rwvfrehsqq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rwvfrehsqq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rwvfrehsqq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rwvfrehsqq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"contrast\">contrast</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"null.value\">null.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">ARM</td>\n<td headers=\"contrast\" class=\"gt_row gt_left\">B - A</td>\n<td headers=\"null.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.823</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.806</td>\n<td headers=\"df\" class=\"gt_row gt_right\">17.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.122</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">3.523</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.261</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.037</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# Wald-based CIs\nround(stats::confint(res_survreg, level = 0.95)[2,], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n 0.243  3.402 \n```\n\n\n:::\n:::\n\n\n\nThe output provides an estimate of difference between groups A and B (B-A), namely 1.823 (se=0.806). The presented p-value is a two-sided p-value based on the Z-test. The output also provides an estimate for $log(\\sigma) = 0.549$. Using the `emmeans` package/function least square means and contrast can be easily obtained. The confidence intervals and p-value is based on the t-test using `emmeans`. Wald based confidence intervals can be obtained by the `stats::confint` function.\n\n\n### vglm\nThe `VGAM` package provides functions for fitting vector generalized linear and additive models (VGLMs and VGAMs). This package centers on the iteratively reweighted least squares (IRLS) algorithm. The `vglm` function offers the possibility to fit a tobit model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_vglm = vglm(Y ~ ARM,\n                tobit(Lower = 8.0),\n                data = dat_used)\nsummary(res_vglm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nvglm(formula = Y ~ ARM, family = tobit(Lower = 8), data = dat_used)\n\nCoefficients: \n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept):1   8.8323     0.5727  15.422  < 2e-16 ***\n(Intercept):2   0.5491     0.1807   3.039  0.00238 ** \nARMB            1.8226     0.7942   2.295  0.02173 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nNames of linear predictors: mu, loglink(sd)\n\nLog-likelihood: -34.3154 on 37 degrees of freedom\n\nNumber of Fisher scoring iterations: 7 \n\nNo Hauck-Donner effect found in any of the estimates\n```\n\n\n:::\n\n```{.r .cell-code}\n# Difference between groups\nround(res_vglm@coefficients[3], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ARMB \n1.823 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(confintvglm(res_vglm, level = 0.95)[3,], 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 2.5 % 97.5 % \n 0.266  3.379 \n```\n\n\n:::\n:::\n\n\n\nThe output provides an estimate of difference between groups A and B (B-A), namely 1.823 (se=0.794). The presented p-value is a two-sided p-value based on the Z-test. Note that point estimate for the difference (and associated SE) are slightly different from the results obtained by `censReg` and `tobit` due to the difference in estimation procedure used. Wald based confidence intervals can be obtained by the `confintvglm` function. The $(Intercept):2$ in the model output is an estimate for $log(\\sigma)$.\n\n## Discussion\nThe results from the `censReg::censReg` and `survival::survreg` are similar. The `survival::survreg` allows for easy incorporation with the `emmeans` package (note: be aware that the standard approach with emmeans is based on the t-test and not the Z-test).\n\nThe `VGAM::vglm` approach provides slightly different results. This difference comes from the fact that a iteratively reweighted least squares (IRLS) algorithm is used for estimation.\n\n\n## Reference\n\nBreen, R. (1996). Regression models. SAGE Publications, Inc., https://doi.org/10.4135/9781412985611\n\nTobin, James (1958). \"Estimation of Relationships for Limited Dependent Variables\". Econometrica. 26 (1): 24-36. doi:10.2307/1907382\n\n\n\n\n::: {.callout-note collapse=\"true\" title=\"Session Info\"}\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.4.2 (2024-10-31 ucrt)\n os       Windows 11 x64 (build 26100)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  English_United States.utf8\n ctype    English_United States.utf8\n tz       America/Chicago\n date     2025-08-18\n pandoc   3.4 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)\n\n─ Packages ───────────────────────────────────────────────────────────────────\n ! package      * version date (UTC) lib source\n P backports      1.5.0   2024-05-23 [?] RSPM (R 4.4.0)\n P bdsmatrix      1.3-7   2024-03-02 [?] RSPM (R 4.4.0)\n P broom        * 1.0.7   2024-09-26 [?] RSPM (R 4.4.0)\n P censReg      * 0.5-38  2024-05-20 [?] RSPM (R 4.4.0)\n P cli            3.6.3   2024-06-21 [?] RSPM (R 4.4.0)\n   codetools      0.2-20  2024-03-31 [2] CRAN (R 4.4.2)\n P collapse       2.0.18  2024-11-23 [?] RSPM (R 4.4.0)\n P digest         0.6.37  2024-08-19 [?] RSPM (R 4.4.0)\n P dplyr        * 1.1.4   2023-11-17 [?] RSPM (R 4.4.0)\n P emmeans      * 1.10.4  2024-08-21 [?] RSPM (R 4.4.0)\n P estimability   1.5.1   2024-05-12 [?] RSPM (R 4.4.0)\n P evaluate       1.0.0   2024-09-17 [?] RSPM (R 4.4.0)\n P fansi          1.0.6   2023-12-08 [?] RSPM (R 4.4.0)\n P fastmap        1.2.0   2024-05-15 [?] RSPM (R 4.4.0)\n P Formula        1.2-5   2023-02-24 [?] RSPM (R 4.4.0)\n P generics       0.1.3   2022-07-05 [?] RSPM (R 4.4.0)\n P glmmML         1.1.7   2024-09-20 [?] RSPM (R 4.4.0)\n   glue           1.8.0   2024-09-30 [2] CRAN (R 4.4.3)\n P gt           * 0.11.1  2024-10-04 [?] RSPM (R 4.4.0)\n P htmltools      0.5.8.1 2024-04-04 [?] RSPM (R 4.4.0)\n P htmlwidgets    1.6.4   2023-12-06 [?] RSPM (R 4.4.0)\n P jsonlite       1.8.9   2024-09-20 [?] RSPM (R 4.4.0)\n P knitr          1.50    2025-03-16 [?] RSPM (R 4.4.0)\n   lattice        0.22-6  2024-03-20 [2] CRAN (R 4.4.2)\n   lifecycle      1.0.4   2023-11-07 [2] CRAN (R 4.4.3)\n P lmtest         0.9-40  2022-03-21 [?] RSPM (R 4.4.0)\n   magrittr       2.0.3   2022-03-30 [2] CRAN (R 4.4.3)\n   MASS           7.3-61  2024-06-13 [2] CRAN (R 4.4.2)\n   Matrix         1.7-1   2024-10-18 [2] CRAN (R 4.4.2)\n P maxLik       * 1.5-2.1 2024-03-24 [?] RSPM (R 4.4.0)\n P miscTools    * 0.6-28  2023-05-03 [?] RSPM (R 4.4.0)\n P multcomp       1.4-26  2024-07-18 [?] RSPM (R 4.4.0)\n P mvtnorm        1.3-1   2024-09-03 [?] RSPM (R 4.4.0)\n   nlme           3.1-166 2024-08-14 [2] CRAN (R 4.4.2)\n P pillar         1.9.0   2023-03-22 [?] RSPM (R 4.4.0)\n P pkgconfig      2.0.3   2019-09-22 [?] RSPM (R 4.4.0)\n P plm            2.6-4   2024-04-01 [?] RSPM (R 4.4.0)\n P purrr          1.0.2   2023-08-10 [?] RSPM (R 4.4.0)\n P R6             2.5.1   2021-08-19 [?] RSPM (R 4.4.0)\n P rbibutils      2.3     2024-10-04 [?] RSPM (R 4.4.0)\n P Rcpp           1.0.13  2024-07-17 [?] RSPM (R 4.4.0)\n P Rdpack         2.6.1   2024-08-06 [?] RSPM (R 4.4.0)\n   renv           1.0.10  2024-10-05 [1] RSPM (R 4.4.2)\n P rlang          1.1.4   2024-06-04 [?] RSPM (R 4.4.0)\n P rmarkdown      2.28    2024-08-17 [?] RSPM (R 4.4.0)\n P rstudioapi     0.16.0  2024-03-24 [?] RSPM (R 4.4.0)\n P sandwich       3.1-1   2024-09-15 [?] RSPM (R 4.4.0)\n P sass           0.4.9   2024-03-15 [?] RSPM (R 4.4.0)\n P sessioninfo    1.2.2   2021-12-06 [?] RSPM (R 4.4.0)\n   survival     * 3.7-0   2024-06-05 [2] CRAN (R 4.4.2)\n P TH.data        1.1-2   2023-04-17 [?] RSPM (R 4.4.0)\n P tibble         3.2.1   2023-03-20 [?] RSPM (R 4.4.0)\n P tidyr          1.3.1   2024-01-24 [?] RSPM (R 4.4.0)\n P tidyselect     1.2.1   2024-03-11 [?] RSPM (R 4.4.0)\n P utf8           1.2.4   2023-10-22 [?] RSPM (R 4.4.0)\n   vctrs          0.6.5   2023-12-01 [2] CRAN (R 4.4.3)\n P VGAM         * 1.1-12  2024-09-18 [?] RSPM (R 4.4.0)\n P withr          3.0.1   2024-07-31 [?] RSPM (R 4.4.0)\n P xfun           0.52    2025-04-02 [?] RSPM (R 4.4.0)\n P xml2           1.3.6   2023-12-04 [?] RSPM (R 4.4.0)\n P xtable         1.8-4   2019-04-21 [?] RSPM (R 4.4.0)\n   yaml           2.3.10  2024-07-26 [2] CRAN (R 4.4.3)\n P zoo            1.8-12  2023-04-13 [?] RSPM (R 4.4.0)\n\n [1] C:/Users/ljohn71/Desktop/CAMIS/renv/library/windows/R-4.4/x86_64-w64-mingw32\n [2] C:/Users/ljohn71/AppData/Local/Programs/R/R-4.4.2/library\n\n P ── Loaded and on-disk path mismatch.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}