{
  "hash": "7601e56dd8f23d1b383d357dcdb47ffe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Regression\"\noutput: html_document\n---\n\n\n\n## Introduction\n\nSimple linear regression is a statistical method used to model the relationship between a continuous dependent variable and continuous independent variable by fitting a linear equation to the observed data. It estimates how changes in the independent variable affect the dependent variable, allowing for predictions and insights about the underlying relationship. The primary goal is to minimize the difference between the observed values and the values predicted by the model.\n\n**The following assumptions must hold when building a linear regression model.**\n\n1.  The dependent variable must be continuous.\n\n2.  The data you are modeling meets the \"iid\" criterion. That means the error terms, ε, are:\n\n    a.  independent from one another and\n    b.  identically distributed.\n\n3.  The error term is normally distributed with a mean of zero.\n\nTo demonstrate the use of linear regression we examine a dataset that illustrates the relationship between Height and Weight in a group of 237 teen-aged boys and girls. The dataset is available [here](https://github.com/PSIAIMS/CAMIS/blob/3dca6398dca4f242eb0f0c316d7499eaba8adb13/data/htwt.csvhttps://github.com/PSIAIMS/CAMIS/blob/3dca6398dca4f242eb0f0c316d7499eaba8adb13/data/htwt.csv) and is imported to the workspace.\n\n### Descriptive Statistics\n\nThe first step is to obtain the simple descriptive statistics for the numeric variables of htwt data, and one-way frequencies for categorical variables. This is accomplished by employing summary function. There are 237 participants who are from 13.9 to 25 years old. It is a cross-sectional study, with each participant having one observation. We can use this data set to examine the relationship of participants' height to their age and sex.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE)\nhtwt<-read.csv(\"../data/htwt.csv\")\nsummary(htwt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ROW          SEX                 AGE            HEIGHT     \n Min.   :  1   Length:237         Min.   :13.90   Min.   :50.50  \n 1st Qu.: 60   Class :character   1st Qu.:14.80   1st Qu.:58.80  \n Median :119   Mode  :character   Median :16.30   Median :61.50  \n Mean   :119                      Mean   :16.44   Mean   :61.36  \n 3rd Qu.:178                      3rd Qu.:17.80   3rd Qu.:64.30  \n Max.   :237                      Max.   :25.00   Max.   :72.00  \n     WEIGHT     \n Min.   : 50.5  \n 1st Qu.: 85.0  \n Median :101.0  \n Mean   :101.3  \n 3rd Qu.:112.0  \n Max.   :171.5  \n```\n\n\n:::\n:::\n\n\n\nIn order to create a regression model to demonstrate the relationship between age and height for females, we first need to create a flag variable identifying females and an interaction variable between age and female gender flag.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhtwt$female <- ifelse(htwt$SEX=='f',1,0)\nhtwt$fem_age <- htwt$AGE * htwt$female\nhead(htwt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ROW SEX  AGE HEIGHT WEIGHT female fem_age\n1   1   f 14.3   56.3   85.0      1    14.3\n2   2   f 15.5   62.3  105.0      1    15.5\n3   3   f 15.3   63.3  108.0      1    15.3\n4   4   f 16.1   59.0   92.0      1    16.1\n5   5   f 19.1   62.5  112.5      1    19.1\n6   6   f 17.1   62.5  112.0      1    17.1\n```\n\n\n:::\n:::\n\n\n\n### Regression Analysis\n\nNext, we fit a regression model, representing the relationships between gender, age, height and the interaction variable created in the datastep above. We again use a where statement to restrict the analysis to those who are less than or equal to 19 years old. We use the clb option to get a 95% confidence interval for each of the parameters in the model. The model that we are fitting is $height = b_0 + b_1\\times female + b_2\\times age + b_3\\times fem\\_age + e$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression<-lm(HEIGHT~female+AGE+fem_age, data=htwt, AGE<=19)\nsummary(regression)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = HEIGHT ~ female + AGE + fem_age, data = htwt, subset = AGE <= \n    19)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.2429 -1.7351  0.0383  1.6518  7.9289 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  28.8828     2.8734  10.052  < 2e-16 ***\nfemale       13.6123     4.0192   3.387 0.000841 ***\nAGE           2.0313     0.1776  11.435  < 2e-16 ***\nfem_age      -0.9294     0.2478  -3.750 0.000227 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.799 on 215 degrees of freedom\nMultiple R-squared:  0.4595,\tAdjusted R-squared:  0.452 \nF-statistic: 60.93 on 3 and 215 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nb0=round(regression$coefficients[1],4)\nb1=round(regression$coefficients[2],4)\nb2=round(regression$coefficients[3],4)\nb3=round(regression$coefficients[4],4)\n```\n:::\n\n\n\nFrom the coefficients table b0,b1,b2,b3 are estimated as b0=28.8828 b1=13.6123 b2=2.0313 b3=-0.9294\n\n\nThe resulting regression model for height, age and gender based on the available data is $height= 28.8828 + 13.6123\\times female + 2.0313\\times age -0.9294\\times fem\\_age$\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}