---
title: "Confidence Intervals for Proportions"
---

A confidence interval for binomial proportion is an interval estimate for the probability of success calculated from the outcome of a series of Bernoulli trials.

There are several ways to calculate a binomial confidence interval. Normal approximation is one of the most commonly used methods. 

## Normal approximation

In large random samples from independent trials, the sampling distribution of proportions approximately follows the normal distribution. The expectation of a sample proportion is the corresponding population proportion. Therefore, based on a sample of size $n$, a $(1-\alpha)\%$ confidence interval for population proportion can be calculated using normal approximation as follows:

$p\approx \hat p \pm z_\alpha \sqrt{\hat p(1-\hat p)}/{n}$,
where $\hat p$ is the sample proportion, $z_\alpha$ is the $1-\alpha/2$ quantile of a standard normal distribution corresponding to level $\alpha$, and $\sqrt{\hat p(1-\hat p)}/{n}$ is the standard error.

## Example code
The following code calculates a confidence interval for a binomial proportion usinng normal approximation.
```{r}
set.seed(666)
# generate a random sample of size 100 from independent Bernoulli trials
n = 100
mysamp = sample(c(0,1),n,replace = T)
# sample proportion
p_hat = mean(mysamp)
# standard error
se = sqrt(p_hat*(1-p_hat)/n)
# 95% CI of population proportion
c(p_hat-qnorm(1-0.05/2)*se, p_hat+qnorm(1-0.05/2)*se)
```

