<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Logistic Regression in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-635a35c16803d16fd9db22f392043487.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/logo.png" alt="" class="navbar-logo light-content">
    <img src="../images/logo.png" alt="" class="navbar-logo dark-content">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-publications-and-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Publications and Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-publications-and-projects">    
        <li>
    <a class="dropdown-item" href="../publication/white_paper.html"><i class="bi bi-file-earmark-word-fill" role="img">
</i> 
 <span class="dropdown-text">White Paper</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../publication/conference.html"><i class="bi bi-easel3-fill" role="img">
</i> 
 <span class="dropdown-text">Conferences</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../publication/dissertation.html"><i class="bi bi-mortarboard-fill" role="img">
</i> 
 <span class="dropdown-text">Academic Projects</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../minutes/index.html"> 
<span class="menu-text">Meeting Minutes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blogs/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-help" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Help</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-help">    
        <li>
    <a class="dropdown-item" href="https://github.com/PSIAIMS/CAMIS/issues"><i class="bi bi-bug-fill" role="img">
</i> 
 <span class="dropdown-text">Report a Bug</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../contribution/get_started.html"><i class="bi bi-git" role="img">
</i> 
 <span class="dropdown-text">Get Started with Your Environment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../contribution/contribution.html"><i class="bi bi-person-raised-hand" role="img">
</i> 
 <span class="dropdown-text">Get Started with CAMIS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../contribution/package_review.html"><i class="bi bi-box-fill" role="img">
</i> 
 <span class="dropdown-text">Get Started with a New R Package</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/PSIAIMS/CAMIS/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#example-lung-cancer-data" id="toc-example-lung-cancer-data" class="nav-link active" data-scroll-target="#example-lung-cancer-data">Example: Lung Cancer Data</a></li>
  <li><a href="#model-fit" id="toc-model-fit" class="nav-link" data-scroll-target="#model-fit">Model Fit</a>
  <ul class="collapse">
  <li><a href="#modelling-factors-correctly-and-interpretation-of-the-intercept" id="toc-modelling-factors-correctly-and-interpretation-of-the-intercept" class="nav-link" data-scroll-target="#modelling-factors-correctly-and-interpretation-of-the-intercept">Modelling factors correctly and Interpretation of the Intercept</a></li>
  </ul></li>
  <li><a href="#model-parameter-estimates" id="toc-model-parameter-estimates" class="nav-link" data-scroll-target="#model-parameter-estimates">Model parameter estimates</a>
  <ul class="collapse">
  <li><a href="#how-r-parameterizes-your-variables-in-the-model" id="toc-how-r-parameterizes-your-variables-in-the-model" class="nav-link" data-scroll-target="#how-r-parameterizes-your-variables-in-the-model">How R parameterizes your variables in the model</a></li>
  <li><a href="#calculation-of-confidence-intervals" id="toc-calculation-of-confidence-intervals" class="nav-link" data-scroll-target="#calculation-of-confidence-intervals">Calculation of confidence intervals</a></li>
  </ul></li>
  <li><a href="#comparing-2-models" id="toc-comparing-2-models" class="nav-link" data-scroll-target="#comparing-2-models">Comparing 2 models</a></li>
  <li><a href="#predicting-likelihood-of-response-for-new-patients" id="toc-predicting-likelihood-of-response-for-new-patients" class="nav-link" data-scroll-target="#predicting-likelihood-of-response-for-new-patients">Predicting likelihood of response for new patients</a></li>
  <li><a href="#creating-treatment-contrasts-for-2-treatments" id="toc-creating-treatment-contrasts-for-2-treatments" class="nav-link" data-scroll-target="#creating-treatment-contrasts-for-2-treatments">Creating Treatment Contrasts for 2 treatments</a>
  <ul class="collapse">
  <li><a href="#emmeans" id="toc-emmeans" class="nav-link" data-scroll-target="#emmeans">{emmeans}</a></li>
  </ul></li>
  <li><a href="#creating-treatment-contrasts-for-2-or-more-treatments" id="toc-creating-treatment-contrasts-for-2-or-more-treatments" class="nav-link" data-scroll-target="#creating-treatment-contrasts-for-2-or-more-treatments">Creating Treatment Contrasts for 2 or more treatments</a>
  <ul class="collapse">
  <li><a href="#gmodels" id="toc-gmodels" class="nav-link" data-scroll-target="#gmodels">{gmodels}</a></li>
  </ul></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Logistic Regression in R</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In binary logistic regression, there is a single binary dependent variable, coded by an indicator variable. For example, if we represent a response as 1 and non-response as 0, then the corresponding probability of response, can be between 0 (certainly not a response) and 1 (certainly a response) - hence the labeling !</p>
<p>The logistic model models the log-odds of an event as a linear combination of one or more independent variables (explanatory variables). If we observed <span class="math inline">\((y_i, x_i),\)</span> where <span class="math inline">\(y_i\)</span> is a Bernoulli variable and <span class="math inline">\(x_i\)</span> a vector of explanatory variables, the model for <span class="math inline">\(\pi_i = P(y_i=1)\)</span> is</p>
<p><span class="math display">\[
\text{logit}(\pi_i)= \log\left\{ \frac{\pi_i}{1-\pi_i}\right\} = \beta_0 + \beta x_i, i = 1,\ldots,n
\]</span></p>
<p>The model is especially useful in case-control studies and leads to the effect of risk factors by odds ratios.</p>
<section id="example-lung-cancer-data" class="level1">
<h1>Example: Lung Cancer Data</h1>
<p><em>Data source: Loprinzi CL. Laurie JA. Wieand HS. Krook JE. Novotny PJ. Kugler JW. Bartel J. Law M. Bateman M. Klatt NE. et al.&nbsp;Prospective evaluation of prognostic variables from patient-completed questionnaires. North Central Cancer Treatment Group. Journal of Clinical Oncology. 12(3):601-7, 1994.</em></p>
<p>wgt_catn consists of: 1= patients a weight loss of zero or less, 0= patients with a weight loss of more than zero</p>
<p>trt01pn consists of 1= active treatment, 0 = placebo</p>
</section>
<section id="model-fit" class="level1">
<h1>Model Fit</h1>
<p>We analyze the event of weight gain (or staying the same weight) in lung cancer patients in dependency of treatment (active or placebo), age, sex, ECOG performance score and calories consumed at meals. One of the most important things to remember is to ensure you tell R what your event is and what treatment comparison you are doing Active / Placebo or Placebo/Active! The easiest way to do this is to have event (or non-reference treatment) as 1, and non-event (reference treatment) as 0.</p>
<p>Below we are using wt_catn (0,1) and trt01pn (1,2) and sex (1,2). Let’s see what happens !</p>
<p>head(lung)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>lung <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/lung_cancer.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lung)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss trt01p
1    3  306      2  74   1       1       90       100     1175      NA Active
2    3  455      2  68   1       0       90        90     1225      15 Active
3    3 1010      1  56   1       0       90        90       NA      15 Active
4    5  210      2  57   1       1       90        60     1150      11 Active
5    1  883      2  60   1       0      100        90       NA       0 Active
6   12 1022      1  74   1       1       50        80      513       0 Active
  trt01pn dose_mg dose_id wt_cat wt_catn cnsr
1       1      10       1   &lt;NA&gt;      NA    0
2       1      10       1   loss       0    0
3       1      10       1   loss       0    1
4       1      10       1   loss       0    0
5       1      10       1   gain       1    0
6       1      10       1   gain       1    1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> trt01pn <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = wt_catn ~ trt01pn + age + sex + ph.ecog + meal.cal, 
    family = binomial(link = "logit"), data = lung)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -3.8623998  1.7675776  -2.185   0.0289 *
trt01pn      0.3887667  0.3781566   1.028   0.3039  
age          0.0122549  0.0211553   0.579   0.5624  
sex          0.8321005  0.3743793   2.223   0.0262 *
ph.ecog     -0.3763592  0.2638322  -1.427   0.1537  
meal.cal     0.0008500  0.0004486   1.895   0.0581 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 202.36  on 169  degrees of freedom
Residual deviance: 190.46  on 164  degrees of freedom
  (58 observations deleted due to missingness)
AIC: 202.46

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>R by default sets the first category as the baseline category, hence trt01pn =1 and sex =1 are the baseline level, and other levels of the variable are contrasted to this level. This is using <code>contr.treatment</code> option (more information on this later!). The estimate for those variables (0.3887 and 0.8321) are the increase in the log-odds of being of receiving treatment 2 vs 1, and of being of sex=2 vs 1. The exponential of the estimate is the odds ratio. For example, exp(0.3887)=1.475, hence Treatment 2 is 1.475 times as likely to have weight gain compared to Treatment 1.</p>
<p>The intercept represents the baseline log odds of the outcome when all predictor variables are set to zero. In the above model, we have variables treatment and sex, each coded as 1 and 2. Currently R is not treating these as binary factors, instead R thinks they are a continuous variable, and hence the intercept is where treatment=0 and sex=0. In the context of our model, this doesn’t make sense as you can’t have a zero gender and zero treatment (but it may not matter as we rarely look at the intercept term anyway!)</p>
<p>However, if you want to have an interpretable intercept term (and if you want to match SAS output for intercept!), then it’s important to ensure any factors in your model as fitted as such in R. You can do this using: <code>lung$trt01pn&lt;-as.factor(lung$trt01pn)</code> or by changing the variable to a 0 and 1. Note if you are using the same <code>contr.treatment</code> option, then this only affects the intercept estimate not the variable estimates.</p>
<section id="modelling-factors-correctly-and-interpretation-of-the-intercept" class="level2">
<h2 class="anchored" data-anchor-id="modelling-factors-correctly-and-interpretation-of-the-intercept">Modelling factors correctly and Interpretation of the Intercept</h2>
<p>So far we’ve learnt that it is good practice to always have binary and categorical variables set as factors, and that we should specify what method we want R to use for doing any contrasts (e.g.&nbsp;<code>contr.treatment</code>). You can specify different contrast methods for each variable by including them in a list in the model. It can sometimes be hard to see what contrast method R is using, so best to always specify this in your model (e.g.&nbsp;<code>contrasts = list(trt01pn = "contr.treatment", sex="contr.sum")</code>. It is helpful to view what the contrasts look like before you select which to use.</p>
<p>A factor with 2 levels (2 treatments) using <code>contr.treatment</code> would set the first level to be the reference (0) and contrast the second level to the baseline.</p>
<p>A factor with 4 levels (4 treatments) using <code>contr.treatment</code> would set the first level to be the reference (0), you would see 3 parameters in the model with 3 estimates corresponding to the increase in log-odds attributable to contrasting the second, third or fourth level to the baseline.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contr.treatment</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2
1 0
2 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contr.treatment</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2 3 4
1 0 0 0
2 1 0 0
3 0 1 0
4 0 0 1</code></pre>
</div>
</div>
<p>Below we apply <code>contr.treatment</code> to our trt01pn and sex variables. Note: how the variables trt01pn2 and sex2 are now shown in the output, this is indicating that these rows relates to treatment=2 and sex=2. See the next section for how to interpret the estimates and change this <code>contr.</code> option.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Good practice to have binary variables (eg. treatment) identified as a factor</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># And to specify what contrast option you are using ! more on this below</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>lung<span class="sc">$</span>trt01pn <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(lung<span class="sc">$</span>trt01pn)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>lung<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(lung<span class="sc">$</span>sex)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> trt01pn <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">trt01pn =</span> <span class="st">"contr.treatment"</span>, <span class="at">sex =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = wt_catn ~ trt01pn + age + sex + ph.ecog + 
    meal.cal, family = binomial(link = "logit"), data = lung, 
    contrasts = list(trt01pn = "contr.treatment", sex = "contr.treatment"))

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -2.6415326  1.5140191  -1.745   0.0810 .
trt01pn2     0.3887667  0.3781566   1.028   0.3039  
age          0.0122549  0.0211553   0.579   0.5624  
sex2         0.8321005  0.3743793   2.223   0.0262 *
ph.ecog     -0.3763592  0.2638322  -1.427   0.1537  
meal.cal     0.0008500  0.0004486   1.895   0.0581 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 202.36  on 169  degrees of freedom
Residual deviance: 190.46  on 164  degrees of freedom
  (58 observations deleted due to missingness)
AIC: 202.46

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
</section>
<section id="model-parameter-estimates" class="level1">
<h1>Model parameter estimates</h1>
<p>The model summary contains the parameter estimates <span class="math inline">\(\beta_j\)</span> for each explanatory variable <span class="math inline">\(x_j\)</span>, corresponding to the log-odds for the response variable to take the value <span class="math inline">\(1\)</span>, conditional on all other explanatory variables remaining constant. For better interpretation, we can exponentiate these estimates, to obtain estimates for the odds instead and provide 95% confidence intervals.</p>
<section id="how-r-parameterizes-your-variables-in-the-model" class="level2">
<h2 class="anchored" data-anchor-id="how-r-parameterizes-your-variables-in-the-model">How R parameterizes your variables in the model</h2>
<ul>
<li><p>contr.treatment - [default] sets the first level to be the reference and contrasts each other level with the baseline. For example, based on the model shown below. Log-odds for Treatment 2 = -2.64153 + 0.38876 =-2.25277 , Log-odds for Treatment 1=-2.64153</p></li>
<li><p>contr.sum - sets the last level to be the reference and compares the mean of the dependent variable for a given level to the overall mean of the dependent variable. For treatment 1, the intercept + trt01pn1 estimate. For Treatment 2, the intercept - trt01pn1 estimate.<br>
Log-odds for Treatment 2 = -2.44715 - - 0.19438 = -2.25277, Log-odds for Treatment 1=-2.44715 - 0.19438 = -2.64153<br>
use <code>contr.sum(2)</code> to show the contrast you are using and hence how to interpret your estimates.</p></li>
<li><p>exponential (ratio log-odds) = odds ratio. eg. -2.25277/ -2.64153 = 0.85283 Treatment 2 is 0.85 times as likely (eg. 15% less likely) to have weight gain compared to Treatment 1.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ma <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> trt01pn <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">trt01pn =</span> <span class="st">"contr.treatment"</span>, <span class="at">sex =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = wt_catn ~ trt01pn + age + sex + ph.ecog + 
    meal.cal, family = binomial(link = "logit"), data = lung, 
    contrasts = list(trt01pn = "contr.treatment", sex = "contr.treatment"))

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -2.6415326  1.5140191  -1.745   0.0810 .
trt01pn2     0.3887667  0.3781566   1.028   0.3039  
age          0.0122549  0.0211553   0.579   0.5624  
sex2         0.8321005  0.3743793   2.223   0.0262 *
ph.ecog     -0.3763592  0.2638322  -1.427   0.1537  
meal.cal     0.0008500  0.0004486   1.895   0.0581 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 202.36  on 169  degrees of freedom
Residual deviance: 190.46  on 164  degrees of freedom
  (58 observations deleted due to missingness)
AIC: 202.46

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contr.treatment</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2
1 0
2 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mb <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> trt01pn <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">trt01pn =</span> <span class="st">"contr.sum"</span>, <span class="at">sex =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = wt_catn ~ trt01pn + age + sex + ph.ecog + 
    meal.cal, family = binomial(link = "logit"), data = lung, 
    contrasts = list(trt01pn = "contr.sum", sex = "contr.treatment"))

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -2.4471493  1.4929863  -1.639   0.1012  
trt01pn1    -0.1943833  0.1890783  -1.028   0.3039  
age          0.0122549  0.0211553   0.579   0.5624  
sex2         0.8321005  0.3743793   2.223   0.0262 *
ph.ecog     -0.3763592  0.2638322  -1.427   0.1537  
meal.cal     0.0008500  0.0004486   1.895   0.0581 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 202.36  on 169  degrees of freedom
Residual deviance: 190.46  on 164  degrees of freedom
  (58 observations deleted due to missingness)
AIC: 202.46

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contr.sum</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [,1]
1    1
2   -1</code></pre>
</div>
</div>
</section>
<section id="calculation-of-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="calculation-of-confidence-intervals">Calculation of confidence intervals</h2>
<p>Using the above model, you can output the estimates and confidence intervals using coef() and confint() and exponential back transforming using exp(). NOTE: that there are two types of confidence intervals that you can calculate. Function <code>confint.default</code> gives the Wald confidence limits, which is the default option in SAS <code>PROC LOGISTIC</code> procedure; whereas <code>confint</code> gives the profile-likelihood limits.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model coefficients summary</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate   Std. Error    z value   Pr(&gt;|z|)
(Intercept) -2.6415326252 1.5140190574 -1.7447156 0.08103439
trt01pn2     0.3887666677 0.3781565596  1.0280574 0.30392281
age          0.0122549015 0.0211552875  0.5792831 0.56239813
sex2         0.8321005169 0.3743792762  2.2226137 0.02624186
ph.ecog     -0.3763592487 0.2638321918 -1.4265100 0.15372119
meal.cal     0.0008499918 0.0004486401  1.8945961 0.05814593</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Wald confidence limits</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">est =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(m1)), <span class="fu">exp</span>(<span class="fu">confint.default</span>(m1)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   est       2.5 %   97.5 %
(Intercept) 0.07125198 0.003664896 1.385263
trt01pn2    1.47516031 0.702994248 3.095470
age         1.01233030 0.971213751 1.055188
sex2        2.29814096 1.103327506 4.786840
ph.ecog     0.68635572 0.409236994 1.151128
meal.cal    1.00085035 0.999970674 1.001731</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># profile-likelihood limits</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">est =</span> <span class="fu">exp</span>(<span class="fu">coef</span>(m1)), <span class="fu">exp</span>(<span class="fu">confint</span>(m1)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                   est       2.5 %   97.5 %
(Intercept) 0.07125198 0.003312288 1.302587
trt01pn2    1.47516031 0.696210092 3.085089
age         1.01233030 0.971670916 1.056194
sex2        2.29814096 1.107651762 4.836770
ph.ecog     0.68635572 0.405659156 1.147452
meal.cal    1.00085035 0.999978126 1.001761</code></pre>
</div>
</div>
</section>
</section>
<section id="comparing-2-models" class="level1">
<h1>Comparing 2 models</h1>
<p>To compare two logistic models, the <code>residual deviances</code> (-2 * log likelihoods) are compared against a <span class="math inline">\(\chi^2\)</span>-distribution with degrees of freedom calculated using the difference in the two models’ parameters. Below, the only difference is the inclusion/exclusion of age in the model, hence we test using <span class="math inline">\(\chi^2\)</span> with 1 df. Here testing at the 5% level.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> trt01pn <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">trt01pn =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = wt_catn ~ trt01pn + sex + ph.ecog + meal.cal, 
    family = binomial(link = "logit"), data = lung, contrasts = list(trt01pn = "contr.treatment"))

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -1.8350766  0.5810727  -3.158  0.00159 **
trt01pn2     0.3681563  0.3761976   0.979  0.32777   
sex2         0.7919227  0.3674936   2.155  0.03117 * 
ph.ecog     -0.3312031  0.2527586  -1.310  0.19008   
meal.cal     0.0007896  0.0004378   1.803  0.07131 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 202.36  on 169  degrees of freedom
Residual deviance: 190.80  on 165  degrees of freedom
  (58 observations deleted due to missingness)
AIC: 200.8

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1, m2, <span class="at">test =</span> <span class="st">"LRT"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: wt_catn ~ trt01pn + age + sex + ph.ecog + meal.cal
Model 2: wt_catn ~ trt01pn + sex + ph.ecog + meal.cal
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1       164     190.46                     
2       165     190.80 -1 -0.33867   0.5606</code></pre>
</div>
</div>
<p>Stackexchange <a href="https://stats.stackexchange.com/questions/59879/logistic-regression-anova-chi-square-test-vs-significance-of-coefficients-ano">here</a> has a good article describing this method and the difference between comparing 2 models using the likelihood ratio tests versus using wald tests and Pr&gt;chisq (from the maximum likelihood estimate). Note: <code>anova(m1, m2, test = "Chisq")</code> and using <code>test="LRT"</code> as above are synonymous in this context.</p>
</section>
<section id="predicting-likelihood-of-response-for-new-patients" class="level1">
<h1>Predicting likelihood of response for new patients</h1>
<p>Predictions from the model for the log-odds of a patient with new data to experience a weight loss are derived using <code>predict()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># new female, symptomatic but completely ambulatory patient consuming 2500 calories</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>new_pt <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">trt01pn =</span> <span class="dv">1</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="dv">48</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="dv">2</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ph.ecog =</span> <span class="dv">1</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">meal.cal =</span> <span class="dv">2500</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>new_pt<span class="sc">$</span>trt01pn <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(new_pt<span class="sc">$</span>trt01pn)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>new_pt<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(new_pt<span class="sc">$</span>sex)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m1, new_pt, <span class="at">type =</span> <span class="st">"response"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
0.628882 </code></pre>
</div>
</div>
</section>
<section id="creating-treatment-contrasts-for-2-treatments" class="level1">
<h1>Creating Treatment Contrasts for 2 treatments</h1>
<section id="emmeans" class="level2">
<h2 class="anchored" data-anchor-id="emmeans">{emmeans}</h2>
<p>Here we will use {emmeans} to output the log-odds of weight gain for treatment 1 and treatment 2.</p>
<p>NOTE as per the output, these are on the logit scale, you need to exponentiate to get the odds (or use the type=“response” option).</p>
<p>The treatment comparison can also be output on the log-odds or back transformed scale as shown below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> trt01pn <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">trt01pn =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::glm(formula = wt_catn ~ trt01pn + age + sex + ph.ecog + 
    meal.cal, family = binomial(link = "logit"), data = lung, 
    contrasts = list(trt01pn = "contr.treatment"))

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -2.6415326  1.5140191  -1.745   0.0810 .
trt01pn2     0.3887667  0.3781566   1.028   0.3039  
age          0.0122549  0.0211553   0.579   0.5624  
sex2         0.8321005  0.3743793   2.223   0.0262 *
ph.ecog     -0.3763592  0.2638322  -1.427   0.1537  
meal.cal     0.0008500  0.0004486   1.895   0.0581 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 202.36  on 169  degrees of freedom
Residual deviance: 190.46  on 164  degrees of freedom
  (58 observations deleted due to missingness)
AIC: 202.46

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contr.treatment</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2
1 0
2 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log-odds for each treatment</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>lsm <span class="ot">&lt;-</span> emmeans<span class="sc">::</span><span class="fu">emmeans</span>(m3, <span class="st">"trt01pn"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>lsm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> trt01pn emmean    SE  df asymp.LCL asymp.UCL
 1       -1.034 0.225 Inf     -1.47   -0.5935
 2       -0.645 0.302 Inf     -1.24   -0.0529

Results are averaged over the levels of: sex 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log-odds ratios (treatment comparison): This does all pairwise comparisons</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># However as seen below, this is TRT 1 - TRT 2</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(lsm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast            estimate    SE  df z.ratio p.value
 trt01pn1 - trt01pn2   -0.389 0.378 Inf  -1.028  0.3039

Results are averaged over the levels of: sex 
Results are given on the log odds ratio (not the response) scale. </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the below creates tests and CI's prior to back transformation (ratios of geometric means)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(lsm, <span class="at">type =</span> <span class="st">"response"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast            odds.ratio    SE  df null z.ratio p.value
 trt01pn1 / trt01pn2      0.678 0.256 Inf    1  -1.028  0.3039

Results are averaged over the levels of: sex 
Tests are performed on the log odds ratio scale </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see coefficients of the linear functions</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">pairs</span>(lsm))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         trt01pn c.1
trt01pn1       1   1
trt01pn2       2  -1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Output treatment contrasts 2 vs 1 and 95% CIs, the type="response" option back transforms the results</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>trtdiff <span class="ot">&lt;-</span> <span class="fu">contrast</span>(lsm, <span class="st">"poly"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>trtdiff</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate    SE  df z.ratio p.value
 linear      0.389 0.378 Inf   1.028  0.3039

Results are averaged over the levels of: sex 
Results are given on the log odds ratio (not the response) scale. </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(trtdiff, <span class="at">type =</span> <span class="st">"response"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast odds.ratio    SE  df asymp.LCL asymp.UCL
 linear         1.48 0.558 Inf     0.703       3.1

Results are averaged over the levels of: sex 
Confidence level used: 0.95 
Intervals are back-transformed from the log odds ratio scale </code></pre>
</div>
</div>
<p>In Summary: Treatment 2 is on average 1.48 times as likely to have weight gain compared to treatment 1, however this is not statistically significant (95% Confidence interval = 0.703-3.100, p-value= 0.3039).</p>
</section>
</section>
<section id="creating-treatment-contrasts-for-2-or-more-treatments" class="level1">
<h1>Creating Treatment Contrasts for 2 or more treatments</h1>
<p>{emmeans} can also be used to do specific contrasts, instead of investigating treatment (active vs placebo), suppose we now want to look at 2 dose groups vs placebo.</p>
<p>We have a 3 level treatment variable (dose_id), where 1=10mg, 2=20mg doses for active treatment and 3= placebo which is 0mg. We want to test the null hypothesis that 0.5*<em>dose10mg + 0.5</em>*dose20mg - placebo = 0. That there is not difference between the doses.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>lung2 <span class="ot">&lt;-</span> lung <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dose_id2 =</span> <span class="fu">as.factor</span>(lung<span class="sc">$</span>dose_id))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> dose_id2 <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung2,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">dose_id2 =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="co"># log-odds for each treatment</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>lsm3 <span class="ot">&lt;-</span> emmeans<span class="sc">::</span><span class="fu">emmeans</span>(m3, <span class="st">"dose_id2"</span>)</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>lsm3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> dose_id2 emmean    SE  df asymp.LCL asymp.UCL
 1        -0.903 0.296 Inf     -1.48   -0.3228
 2        -1.201 0.348 Inf     -1.88   -0.5201
 3        -0.643 0.302 Inf     -1.23   -0.0518

Results are averaged over the levels of: sex 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(lsm3, <span class="fu">list</span>(<span class="at">AveDose_vs_pbo =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="dv">1</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast       estimate   SE  df z.ratio p.value
 AveDose_vs_pbo    -0.41 0.38 Inf  -1.078  0.2813

Results are averaged over the levels of: sex 
Results are given on the log odds ratio (not the response) scale. </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">contrast</span>(lsm3, <span class="fu">list</span>(<span class="at">AveDose_vs_pbo =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="dv">1</span>))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast       estimate   SE  df asymp.LCL asymp.UCL
 AveDose_vs_pbo    -0.41 0.38 Inf     -1.15     0.335

Results are averaged over the levels of: sex 
Results are given on the log odds ratio (not the response) scale. 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Here we found that on average there is -0.41 times the risk of weight gain on active vs placebo but that this is not statisticallly significantly different (95% CI -1.15 to 0.335, p-value = 0.2813).</p>
<p>See the emmeans vignette on creating bespoke contrasts <a href="Comparisons and contrasts in emmeans">here</a>.</p>
<section id="gmodels" class="level2">
<h2 class="anchored" data-anchor-id="gmodels">{gmodels}</h2>
<p>{gmodels} is an alternative package to create contrasts instead of &lt;emmeans&gt;, you can use the <code>fit.contrast()</code> function from the <code>gmodels</code> package. The same result is obtained as &lt;emmeans&gt;.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>lung2 <span class="ot">&lt;-</span> lung <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dose_id2 =</span> <span class="fu">as.factor</span>(lung<span class="sc">$</span>dose_id))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">glm</span>(</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  wt_catn <span class="sc">~</span> dose_id2 <span class="sc">+</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog <span class="sc">+</span> meal.cal,</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> lung2,</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">dose_id2 =</span> <span class="st">"contr.treatment"</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>gmodels<span class="sc">::</span><span class="fu">fit.contrast</span>(m3, <span class="st">'dose_id2'</span>, <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="sc">-</span><span class="dv">1</span>), <span class="at">conf.int =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            Estimate Std. Error   z value  Pr(&gt;|z|)  lower CI
dose_id2 c=( 0.5 0.5 -1 ) -0.4096323  0.3801683 -1.077502 0.2812558 -1.160322
                           upper CI
dose_id2 c=( 0.5 0.5 -1 ) 0.3410574</code></pre>
</div>
</div>
</section>
</section>
<section id="reference" class="level1">
<h1>Reference</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.2 (2024-10-31)
 os       macOS Sequoia 15.6.1
 system   aarch64, darwin20
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/London
 date     2025-08-29
 pandoc   3.4 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)

─ Packages ───────────────────────────────────────────────────────────────────
 ! package      * version    date (UTC) lib source
 P cli            3.6.3      2024-06-21 [?] CRAN (R 4.4.0)
 P dplyr        * 1.1.4      2023-11-17 [?] CRAN (R 4.4.0)
 P emmeans      * 1.10.4     2024-08-21 [?] CRAN (R 4.4.1)
 P estimability   1.5.1      2024-05-12 [?] CRAN (R 4.4.0)
 P fansi          1.0.6      2023-12-08 [?] CRAN (R 4.4.0)
 P gdata          3.0.1      2024-10-22 [?] RSPM
 P generics       0.1.3      2022-07-05 [?] CRAN (R 4.4.0)
 P glue           1.8.0      2024-09-30 [?] CRAN (R 4.4.1)
 P gmodels      * 2.19.1     2024-03-06 [?] RSPM
 P gtools         3.9.5      2023-11-20 [?] RSPM
 P lifecycle      1.0.4      2023-11-07 [?] CRAN (R 4.4.0)
 P magrittr       2.0.3      2022-03-30 [?] CRAN (R 4.4.0)
   MASS           7.3-61     2024-06-13 [2] CRAN (R 4.4.2)
 P mvtnorm        1.3-1      2024-09-03 [?] CRAN (R 4.4.1)
   numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 4.4.0)
 P pillar         1.9.0      2023-03-22 [?] CRAN (R 4.4.0)
 P pkgconfig      2.0.3      2019-09-22 [?] CRAN (R 4.4.0)
 P R6             2.5.1      2021-08-19 [?] CRAN (R 4.4.0)
 P rlang          1.1.4      2024-06-04 [?] CRAN (R 4.4.0)
 P tibble         3.2.1      2023-03-20 [?] CRAN (R 4.4.0)
 P tidyselect     1.2.1      2024-03-11 [?] CRAN (R 4.4.0)
 P utf8           1.2.4      2023-10-22 [?] CRAN (R 4.4.0)
 P vctrs          0.6.5      2023-12-01 [?] CRAN (R 4.4.0)
   withr          3.0.1      2024-07-31 [1] CRAN (R 4.4.0)

 [1] /Users/christinafillmore/Documents/GitHub/CAMIS/renv/library/macos/R-4.4/aarch64-apple-darwin20
 [2] /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library

 P ── Loaded and on-disk path mismatch.

──────────────────────────────────────────────────────────────────────────────</code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/psiaims\.github\.io\/CAMIS\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>