---
title: "Generalized Linear Mixed Models	 R"
---

As outlined previously in the Random Effects section: longitudinal data are frequently collected as part of clinical trials giving multiple visit records per subject in a study with a serial trace of some outcome of interest. The Mixed Model for Repeated Measures (MMRM) model is ubiquitous in this context and has a very standard implementation in SAS using `proc mixed`. It is often the primary analysis model in GSK trials. Below we note a few features of this model:

* Errors are assumed to be Normally distributed
* It extends the ANCOVA for repeated assessments by treating time as categorical variable and thus assumes no specific functional form (e.g., quadratic) for the time-outcome relationship.
* It assumes that any missing values are missing at random (MAR)
* The standard implementation actually does not include a random effect, instead handling correlation within subjects over repeated visits via specification of the  variance-covariance structure that characterises the pattern for visits
* Different structures can be used, the most common is the unstructured variance-covariance which makes the least assumptions, but necessarily requires more parameters and so can sometimes invoke undesirable convergence issues

In this section we focus on the MMRM fit with an unstructured variance-covariance pattern. This estimates all on-diagonal and off diagonal effects, so is heterogeneous for both variances and co-variances. It is appropriate for fixed visit structures.

#### Using the `nlme::gls` function

Fitting an MMRM in R is achieved using the `nlme::gls()` function. This is a Generalized Least Squares fitting procedure which allows for bespoke specification of the correlation structure used.

```{r}
#| eval: false
#| echo: true
gls(model = CHG ~ TRTP + AVISITN + TRTP:AVISITN + AVISITN + BASE,
    data = data,
    correlation = corSymm(form = ~1|SUBJID),
    weights = varIdent(form = ~1|AVISITN),
    control = glsControl(opt = "optim"),
    method = "REML",
    na.action = "na.omit")
```

an swap out `corSymm` for `corCompSymm` to give the compound symmetry structure or `corCAR1` for autoregressive of first order (AR(1)).

The specification of the unstructured variance-covariance and the repeated structure for visits comes through via our direct calls to the `correlation = corSymm(form = ~1|SUBJID)` and the `weights = varIdent(form = ~1|AVISITN)`
