---
title: "CAMIS Objectives 2025"
date: "13 Jan 2025"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2025.csv")
knitr::kable(
       list(attend_list[c(1,2)]), "html")
```

# Agenda & Minutes

**2025 Objectives**

***Communication***

```         
    -   Expanding awareness within companies

    -   More Through PSI (statistician in the pharmaceutical industry) contacts

        -   Volunteers required for: 2025: 3 x series of CAMIS workshops

        -   Introduction to CAMIS project /how to use it contribute
        
        -   Key findings of CAMIS project
        
        -   How do you do comparisons in software.


    -   Other organizations, ASA /OpenStatsWare, EFSPI will be covered through PSI, RinPharma (hosting services YouTube), ISBC -Aug Basel Yannick offered to submit abstract & present on our behalf.
        ACTION: Lyn to send latest version of slides: & load to website.

    -   Expand awareness to university contacts. Michael Kane can provide introductions through R medicine. Will raise at next meeting to see if we can find an interested professor. There is a desire for students to want projects in pharma topics (master students) -- especially regulatory. We are happy to offer presentations/ workshops to anything they want. (Stephen Waugh could present his experience?)
```

***Conferences***

If anyone can attend to represent us let us know, we can help with abstracts / slides.

```         
    -   posit::conf(2025)** Get the full details on [the blog post](https://urldefense.com/v3/__https:/info.posit.co/NzA5LU5YTi03MDYAAAGX8BSQdqgtSXVvlxo3uOEKf6cyZbztuQua15w8xXZxe1apl5i8EF9CsQLDaXVdqYXWvjSHzLo=__;!!GfteaDio!aUG_6o_VjPNuaS8HtZgYUS61J7SQrYdKV_-mpyMEkGutGnBN9WATMv9lIk5MflS0BofTiViRryNVUD4_9A$). Closes 3^rd^ Feb. Talks are 20 minutes long \'pharma stream\' and will be delivered in person in Atlanta on September 17 or 18 **Volunteers..**

    -   PHUSE -- SDEs / Conferences..... Volunteers..

        -   **PHUSE US connect:** [PHUSE US Connect 2025 \| CDISC](https://www.cdisc.org/events/education/external-events/2025/03/phuse-us-connect-2025)  16^th^-19^th^ March.. Lyn to send content to Mike????

    -   ISBC Feb 14^th^, Yannick will submit abstract

    -   PharmaSUg conference **Volunteers..**

    -   R medicine Volunteers. (Michael kane will be going). Vitual (Chi?)

    -   R in Pharma Volunteers.

    -   PSI Conference -- we have 2 talks.
```

***Improving social media frequency***

Blogs to summarise What are the latest repo updates, how do we showcase this on the website? Or by blogs (but how do people get made aware of them)!!!.

ACTION: Lyn to speak Harshil. Focused Role just to write Monthly blogs. -- Bring in extra person to help if needed.

***Improving Technical back end***

When lyn tested new posit workbench method. Can do demo & give access to frequent contributors who struggle with package control using renv / rendering.

-   Christina & Michael Walsh will update us at a later meeting. (Eg. PRs with dummy website views)
-   Strategy for how to make Comparison pages more stable with respect to R version changes
-   Possibility to include checks which run the code & check for change

***Key Topics to update*** MMRM (Stephen Waugh), CMH (lyn), Sample size (Agnieszka & Andisheh & Molly), re-organize logistic regression (Lyn/Chi), reference based multiple imputation (Yannick), Miriam (Generalized MMRM)\*\*

***Highlights of key content that has been updated & Summary of findings.***

Coin package: Martin PPD to edit Wilcoxon signed rank Lyn let agnieska know. Stephen McCawille -- propensity scores restriction on SAS so used R: to talk to christina.
