---
title: "General meeting updates"
date: "10 Feb 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2025.csv")
knitr::kable(
       list(attend_list[c(1,3)]), "html")
```

# Agenda & Minutes

-   **Volunteers needed for**

    -   Missing data subgroup to look at multiple imputation methods?

    -   CI for props section (See r page).

        -   any R packages that can do CI for matched 2 proportions using wilson or normal approximation methods.

        -   any R packages that can do CI for unmatched 2 proportions using newcombe (or wilson method)

-   **CAMIS- 3 x workshops:**

    -   Introduction to CAMIS project / how to contribute

    -   Key findings of CAMIS project

    -   How do you do comparisons in software\

-    **Conference planning** See latest Conference Tab on website

    -   posit::conf(2025) deadline 3rd Feb in person atlanta

    -   PHUSE US connect/ CSS 16th-19th march. lyn to send content to Hamming Tu

    -   ISBC 14th Feb. Yannick submitting abstract

-   **Communication team update (Vikash & Molly)**

    -   Blog ideas

        -   latest repo updates (CI for Props)

-   **Content updates**\
    Anyone with any questions about what they are working on or how to assign themselves?

    -   

    -   

-   **Objective to get more regulatory input**\
    Work with PSI AIMS as they plan a EMA regulatory panel discussion on R Any other ideas?\
    FDA/ Other regulators input/discussion.

-   **University contacts**

    -   **Michael Kane : R medicine\
        **
