---
title: "Repo Content Growth, Conferences 2024 & Advertising, CAMIS-ONCO & Dissertation project kick off"
date: "10 June 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,7)]), "html")
```

# Agenda & Minutes


## Monthly Contributions update -Christina


Thank you to everyone whose contributed this month, Special shout outs to Seemani, Lukas, David & Agnieska and anyone else we've missed who completed pull requests this month.

NOTE that if your work requires a package not yet in the renv.lock file, then you need to install the package and do renv::update() to update the lock file. When you do the pull request, check 2 files change (i.e. the renv.lock file & your file you are submitting).\

Christina plans to update the renv control method soon which will hopefully avoid some of the package / renv issues going forward. Remember if you do have problems with the install.packages() & update to renv lock file just let Christina know. **ACTION: Christina**: To add to the contributions guidance once new method agreed.

It was noted by Seemani, that her MANOVA Python content was loaded to the folder, but not visible on the website. **ACTION: Christina**: to update the TOC to point to the material.

Please can people when picking up new pieces to work on update the table of assignments saved in the following [readme](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content) Or ask Lyn/ Christina to update it for you. This ensures we dont have multiple people working at the same time duplicating effort, when they could be working together.


## Conferences update - Lyn


Reminder that if you are attending a conference to represent CAMIS to add the detail [here](https://psiaims.github.io/CAMIS/publication/conference.html).

We have updated the page linking to much of the content presented in 2024 and showing we are currently presenting at 7 seminars/ SDEs/ conferences in 2024.

Christina also presented at the Merck R users group last month. **ACTION: Christina**: to add to the conferences list to show we did this. If anyone else wants a presentation to their companies please let her know.

Stephen McCawille is also attending PHUSE EU as well as Christine & Agnieska, so the 3 of them can meet up in person.

Andras Kasa - informed us that there is a PHUSE SDE at UCB in Brussels in september. Details can be found [here](https://www.phuse-events.org/attend/frontend/reg/thome.csp?pageID=41350&eventID=65&CSPCHD=001001000000PhrBQ2idz0rcRJRn8sp7vIfIEqWC1RCufjt3kK). Contact UCB biosciences team: Christophe.Praet\@ucb.com and marc.derycke\@ucb.com if we have someone who could present at this meeting.

Unfortunately Soma and Vikash were unable to present the workshop at PHUSE CSS last week, however Mike Stackhouse kindly stood in for us, and led a round table discussion about the project. Huge Thank you to Mike for his support and last minute help so we could continue with a session.

**ACTION: Volunteer please!!** to attend and present at this SDE in person as it would be really good for CAMIS to be presented at this event.

Keevan asked if we had a single slide to advertise CAMIS. **ACTION: Lyn** to load single slide to non-website content and add a link to it on conferences tab. Can be found [here](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content/conferences/2024/PHUSE%20CSS%20CAMIS%20Single%20slide%202024.pptx).

**ACTION:** Christina : Move Phuse-EU2023 pptx into 2023 folder.


## Pharma - SUG linkedin Post - Chi


Chi highlighted the incredible post from Phil Bowsher advertising the CAMIS project. This has been seen by over 400 people with 38 reposts to date ! It has also been commented on by renowned statisticians all enthusiastic about CAMIS, so it's great to have the awareness of the project growing.

<https://www.linkedin.com/posts/philip-bowsher-67151015_rinpharma-rstats-pharmaverse-activity-7202038957512036352-k1AU?utm_source=share&utm_medium=member_desktop>

**ACTION: Harshil** to repost/share in a couple of weeks to maximize the reach of the post.


##Update from Survival team - Christina


Soma has officially stepped down as CAMIS-ONCO lead, so Christina will act as this for the time being.

Kick off meeting has occurred last month & the team are now meeting monthly. The first objective is for people to bring together information on the non-proportional hazards models.

In future, would be great to have someone take on the lead / co-lead if they feel strongly about leading this, but needs someone dedication to making progress !

##Dissertation scheme kick off -  Chi / Lyn/Christina##

We have launched a new page [here](https://psiaims.github.io/CAMIS/publication/dissertation.html) which will provide ideas for students wanting to look at dissertation projects involved in comparing analysis method differences across software.   If you have an idea for a project that you want to research but dont have time to investigate the project yourself, then you could write an abstract and save it to this page, where students looking for projects (or academics looking on behalf of students), could find ideas for projects.  Expectation is that most would be MSc level (summer 3 month project), however longer PhD style project could also be offered.   Please reach out to us if you are interested in contributing to this area. 


## 2024 Goals Reminder!

-   Increase to 45 closed by the end of the year - Currently at 37 closed.
-   In addition, we'd like to improve some of the incomplete content such as MMRM - Stephen Waugh dissertation project launched, if accepted would run sept 24-july25.
-   Create a webpage for listings dissertation projects - Ongoing

## AOB

Our Blog page dosn't appear in date order or aligned! If anyone can fix let us know ! Saved under News [here](https://psiaims.github.io/CAMIS/blogs/)
