---
title: "GDPR for PHUSE WGs & Latest repo updates"
date: "10 Mar 2025"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2025")
knitr::kable(
       list(attend_list[c(1,4)]), "html")
```

# Agenda & Minutes

-   Blog Update (Molly / Vikash)

    -   Yannick's Tobit regression blog was sent to PSI enews, PHUSE & will be on the CAMIS blog page shortly.

-   Content updates in the last month ! (Christina / Lyn / Yannick)

    -   Cox- PH update for Ties=Exact & Convergence (Nan Xiao & Abi terry)

        -   V 3.2-1.3 of package changed in R, how ties can be handled in `survival::coxph` function. Now instead of options for Breslow, Efron & discrete, now R can do Exact method & this matches SAS. Also, page had added a description of convergence methods to explain differences caused by convergence.

    -   CIs for Props (Lyn)

        -   Now has a section using `desktools:BinomDiffCI` for 2 independent samples i

    -   Logistic regression (Lyn)

        -   Now complete. (NOTE discussion the call regarding how package authors can write their own\
            S3 class R objects which overwrite defaults.... however, something like confint.default() can still be used to revert to the default wald method, incase of the confint() profile likelihood method.

            This is why it's dangerous to call variables function.variable as you may overwrite a special class of objects in R.

    -   Reference based Multiple imputation joint modelling continuous data (Yannick)

        -   Leads the reader through R, SAS & the comparison. Full description of the LSHTM 5 SAS macros for this, vs R and found to agree!\
            NOTE: that for Rbmi, Daniel Sabnane Bove, will be updating the package to include MMRM (at the moment it only does ANOVA).

    -   Sample size for Bioequivalence (Andrey Ogurtsov) - TOST sample size added.

-   RE: the Table of contents, feel free to suggest changes for the required categories vs content.

-   NOTE: that we still have some pages, which could be classed as quick wins which are simple to create like SAS page for poisson/negative binomial. If you want to volunteer for anything add and issue or check for existing [issues](https://github.com/PSIAIMS/CAMIS/issues) and assign yourself (or add comment that you are working on it.)

-   Repo Tech

    -   Some complex methods may slow repo creation down.. Ok for now.\
        Could update the running so only re-runs if code changes or only re-run if any of the packages change that the code uses. (if that's possible).

    -   Is it useful, to use Riskmetric to assess quality of package? Possibly not, because riskmetric doesn't handle stats packages very well. something like survival can appear 'risky' but it's just because it was developed so long ago & hasn't been updated because it doesn't need to be updated ! Maybe add page on CAMIS talking about risk assessment of stats packages - how to assess trustworthyness.

-   GDPR for PHUSE WGs - **FORM IS BY CLICKING ON WORD FORM IN THE EMAIL.**

    The PHUSE Office has been reviewing our GDPR requirements and the information we hold on Working Group Members. As a result of this review, we have created a Working Group member form to capture the information we need to run effective and impactful Working Groups and project teams. As part of this we need to capture your consent to both hold basic information (name, email & company) and to use this in the context of PHUSE Working Groups.

    Consequently, it is now a mandatory requirement that all members of PHUSE Working Groups complete this [\*form\*](https://forms.office.com/Pages/ResponsePage.aspx?id=xeEJLj1cykuXxFc6VpX1UKYKFE6i0SdEjGxMC4fPoj9UOUVUWkRQN1JXRE9BVU5UVTZIUUFHTEszMS4u) to enable your continued participation in project teams and Working Groups. Unfortunately, this means that those who do not respond, will need to be removed from the Working Groups. The deadline for completion of the form is **20 March 2025.** Please select all Data Visualisation & Open Source Technology projects from the list that you participate in.

    Additionally, as part of the form there is an opportunity to provide feedback on your experiences in PHUSE Working Groups. Whilst this is not mandatory, we would appreciate any feedback, particularly around any barriers/challenges you face that limits your participation, or any general feedback, both good and bad.

    If you have any questions or feedback on the form, please contact the office at [workinggroups\@phuse.global](mailto:workinggroups@phuse.global "mailto:workinggroups@phuse.global"). Thank you for your attention to this matter and we very much look forward to your continued support in the future.

-   AOB
