---
title: "Gen AI for SAS-->R code, Achievements + 2025 objectives"
date: "14 Oct 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,11)]), "html")
```

# Agenda & Minutes

## Gen AI to convert SAS code to R code (Brian)

AI (such as chatgpt) can be used to convert SAS code to R or vice-versa. You can even upload a zip file containing multiple programs and it will unzip & convert. It even lists the packages it thinks it needs & can convert SAS macros into an R function (for example).

It's not 100% reliable, and it does need work once translated but huge help if starting from scratch.

Some caveats:

-   All code written is in lower case so you'd have to check that if your variable names are in mixed or upper case (as R case sensitive).

-   chatgpt would also store your data, so don't load anything up that is company sensitive!

## Visibility of our blogs /Future blogs (Harshal)

Discussed who sees the blogs, only 2 / 17 on the call saw it. Somehow we need to find a way to get more visibility! Any ideas let us know, but plan to do more blogs in future and will help if all share them.

## Conferences update (Lyn/All)

-   PHUSE EU connect meet up ! (Christina to arrange meeting face to face)\
    Michael Walshe, Anwesha Roy, Stephen Mccawille, Kate Booth, Agnieska Tomczyk are going
-   PHUSE US connect (Cuifeng? ): Lyn to follow up if anyone going.\
    Objective 2025: expand our team members that we have in the USA.
-   PHUSE FDA CSS will have a event in Utrecht, the netherlands running side by side with the Silver Springs, Maryland
-   PSI 2025 deadlines are as follows:
    -   Oral abstract submission -22nd November 2024
    -   Notification - no later than 16th December 2024
    -   Poster abstract submissions -25th February 2025

## Content updates (Chrstina / All)

Diversity alliance hackathon will be addressing/reviewing open issues (especially 'good first issue' ones) To help with this event, please raise any Issues - preferably small changes that re needed for the Diversity alliance hackathon to use as example issues to open pull requests to resolve --

Open pull request = NONE ! Great work Christina!\
Huge Achievement for 2024: 200 closed pull requests

Survival (Christina) Meetings ongoing, if you want to join contact Christina. Objective 2025: Focus is on Accelerated failure time models.

MMRM (Lyn) Objective 2025: to get updated such that the R, SAS & Comp are consistently written

If anyone else is assigned an area to research and needs help or can no longer commit to completing content just let us know and we can get someone to assist you or work to re-assign it.

## Previous Actions Items Update

-   Add page on how to run/conduct a hackathon: Perhaps drop this action unless someone thinks it's useful? Please let us know if you want us to add this else we'll not maintain the page & wind it down

-   Add a hackathon page: Question to ALL -- do people want to do hackathons in their company to encourage open source? If we could write the guidance, then could link to it from linkedin. To a webinar or guidance. But if wont be used, wont put this highest on our list of To Do!

-   Finding documentation for 'old' versions of the base R "stats" package (sarah/ christina) Hard to find this documentation. For this reason, need to use Eval: TRUE, so it runs using latest version and the output will be the latest output. However, in our comparison -- often these are typed in, especially as you can't get live output run from SAS. So if Table is not current... we wont know!

Objective 2025-2026!: Rethink this in 2025. Can we add 'testthat' expect equals. So we are notified if something changes? Would have write/save SAS number in dataset to compare electronically with R. For tables with no numbers (listing defaults), we could check default as well. Could also not reproduce entire repo each time... but then run risk of things breaking (only running at snapshots of different versions). Printing of the Versions are now visible on the templates so please use the template so the versions appear In the run content

## Goals

45 issues closed by end of year (surpassed already as 70 closed now!) NOTE: a lot are open because we opened as examples for the diversity alliance hackathon- will be closed in next few weeks after that event. Would like 1 page by end 2024. 200 pull requests closed out!!

MMRM content: Stephen Waugh assigned to work on this until June 2025 as his dissertation project

Webpage for listing dissertation projects? TBC if this is needed or doing OK assigning through volunteers.

## New 2025 Goals (and some carried forward!)

-   expand our influence (particular through representation in USA)

-   Advance our MMRM pages

-   Advance our survival pages

-   Reconsider our infrastructure with respect to

    -   renv

    -   live running of repo and knowing when a version changes our content

    -   making it easier for people to contribute
