---
title: "How to select packages, Content & Conferences"
date: "11 Mar 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,4)]), "html")
```

# Agenda & Minutes

-   Thank you to all those who submitted content this month, especially Chi, David and Filip who all helped to complete new sections. The top section is now almost complete and the first python content will be loaded in the next few weeks which is a great milestone for the project. Watch out for the new column appearing in the repository Table of contents!\
    Please remember even if you dont want to contribute to a section on your own, you can still review current content and propose improvements.

-   Conference planning. Reminder that if you are attending a conference to represent CAMIS to add the detail [here](https://psiaims.github.io/CAMIS/Conferences.html). We need to ensure we continue to advertise the project to encourage people to use the repo and add content. So far in 2024, only 3 conferences being attended, so if you are interested in attending a conference just reach out to Lyn & Christina who can help you with an abstract if needed.\
    \
    Vikash fed back about the PHUSE US Connect conference. CAMIS was mentioned by Michael Rimler in the keynote speech and Soma/Vikash presented a poster so we received great publicity. Brian also attended meeting Soma & Vikash face to face. Thank you to all of you. The abstract for PHUSE FDA CSS has been written by Soma and submitted so all on track.

-   Reminder to complete CAMIS membership form\
    <https://docs.google.com/forms/d/e/1FAIpQLSdDX79P5ByStVS_3n4tK1mAWidazIiF6DMEtDMK8KqmJywjqA/viewform?vc=0&c=0&w=1&flr=0&usp=mail_form_link>

    NOTE:  We will only collect: team members name, email address, organization, software used, interested in oncology, key interests and affiliations to stats organizations.  The email address is solely for the CAMIS leadership team, to make sure you are included in CAMIS emails.\
    We ask on the form: "Are you happy for your Name and company and interests to be visible on the CAMIS website. Note that email addresses will not be visible". 

    If you do not give permission then your name will not appear on the CAMIS repo as a CAMIS team member. If you do give permission, your name and company and interests will appear but your email addresses will be hidden from public view. At any time you can ask to be removed from the website team list by emailing me.

-   Selection of packages: As we continue to grow the number of packages stored in the repository is growing. We realized that this may lead to conflicts and issues for the repo running. We also dont really want packages installed that are no longer used, known to have issues. Therefore if you are writing up an analysis and there are two packages doing similar things, we would like to request that you select the one that is the most commonly used and best quality (i.e. lowest risk). Risk can be assessed using the {riskmetric} package and {riskassessment} application, using the default scoring, but packages risk should also be considered in context of the individual components such as being actively maintained, bug fixes, code coverage, with references, with a github repo or website, by a trusted author and with results being correct vs stats method.

    It can be very useful to test multiple packages if they are able to do slightly different analysis (i.e. with different options), in these cases it's useful to include a Table at the top of the comparison summary qmd, to show which package does which analysis, see [Comparison of 1 sample t-test](https://psiaims.github.io/CAMIS/Comp/r-sas_ttest_Paired.html) as an example.

    Packages that are inferior to others, should not be loaded to the repo, but instead you can add a textual summary of your findings. For example, "Package X also gives the same results" or "Package X can be used but doesn't have options to do X and Y" or "We do not recommend Package X as during testing, the results are not in line with the statistical methodology".\
    NOTE that we agreed not to have a library of packages "approved" for CAMIS, RENV stores the lock file of the packages in our repo and we do not want to be seen to giving recommendations for/against packages, other than factual evidence based on the analysis they produce.

    It was noted that when you load the RENV.lock file, it may give a "error downloading" bioconductor warning, this can be ignored, and should not cause issue if you aren't using these packages. In the future, these packages will be removed as dependancies from mmrm and the issue will resolve.

-   AOB

    -   We had a discussion surrounding communication methods currently used on the project. RE: using teams vs emails, feedback was mixed, Argument for Teams was that it keeps all discussion in one place, and doesn't fill you in box, but arguments against were that as you often have to log out of your company teams, to log into the PHUSE one, messages are often missed / ignored.

        We agreed to perhaps send 2 emails a month, the agenda, but also any other important updates that occurr during the month & minutes. This will be supported by also posting on social media. Although small sample, we assessed how many people observed the recent post RE: Soma's poster (only Lyn & Christina of those on the call saw the post), however when asked re: Other PHUSE posts 7 were getting them. Leadership team to discuss and see if we need to post using PHUSE admin?
