---
title: "Novartis Hackathon & Content growth"
date: "12 Aug 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,9)]), "html")
```

# Agenda & Minutes

**Welcome**

Welcome to our new team members on the call.  We have an agenda which is sent prior to the meeting, but please do please ask if you have questions or need clarification regarding what we are talking about.

### Repository Content

**Novartis Hackathon**

The Hackathon was a great success, with CAMIS receiving it's largest amount of pull requests in any one month to date ! Christina fed back that it was not as much work as you might think, as although they had 'office hours' to help people and discuss things, actually not many people used them. Instead, they gave a brief introduction to everyone attending, explaining git / github / pull requests etc, then assigned everyone a topic / mini projects to investigate and let them do the research in their own time.

Orla & team reviewed each others pull requests prior to submission to CAMIS repo. Christina worked alongside the team approving the content to go live.

As it went so well, Christina is planning another hackathon style event in October, but it will be on wider concept, focused on people who haven't done pull requests to get more involved with open source projects. We can submit CAMIS topics for them to complete.

If you or your company interested in hackathon ask christina.

**Survival**

Will continue to meet and discuss survival needs, some Accelerated failure time content going in as part of hackathon.

**Assignment table / Raising issues**

**ACTION:** Lyn to remove and we will use issues instead, If you have been on a issue for \>6 months and have not provided us with any feedback on your progress, then you will be unassigned. Obviously if you need more time and are still working on it, just let Christina or another one of the project leads know.

If you want to research a topic, please add an issue or issue comment to tell us what you are working on.

**Ensuring content quality & cross page cohesiveness**

To date, focus was on population of the pages we were missing, however as we move towards having content available, we will need people to review that content to ensure it is of high quality and makes sense. Ideally, the same dataset would be run through R and SAS showing options, then the comparison would discuss the discrepancies in the results obtained and perhaps the differences in default options / available options.

We now have a template for the SAS, and R pages.. and a different one for the comparison pages. This may help us with consistency. Please use the templates if you are starting the work now, it's Ok to do a PR for anything you are already working on, even if the template wasn't used.

### **Conferences**

-   PHUSE EU Brussels 23rd Sept - Qian Wang (Merck) will attend.

-   R/Pharma APAC track -- Samrit has submitted an abstract so hopefully will be able to represent us.

-   SouthEast SAS User Group (SESUG) -- Bethesda: Brian will give us a mention.

-   PHUSE EU -- Stephen Mccawille, Anwesha Roy, Agniekska Tomczyk & Christina Fillmore are all attending PHUSE EU -- if you are attending let Christina know and she will arrange for CAMIS team to meet up for a cuppa & chat at the conference.

-   Phuse US Connect November: Maryland. Cuifeng Yin may be able to attend. Lyn asked for volunteers to represent us a US connect and maybe CSS? **ACTION :** ask PHUSE re: getting a workshop or seminar for CAMIS if we can find volunteers, TBC if at (US CONNECT / or CSS? Or both? )

-   Chi provided feedback from UseR! We may consider using a better title for abstracts, not just CAMIS. The talk was put into a community stream instead of a multilingual programming stream, so may have got better attendance, but still it was well received. 1 person attended requested that they would like to write an article on CAMIS, so Chi will work with them on that.
