---
title: "Website structure update, Team list, Conferences"
date: "12 Feb 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,3)]), "html")
```

# Agenda & Minutes

-   Updated website demo -- Chi & Christina

-   CAMIS membership form / data collection -- Lyn\
    <https://docs.google.com/forms/d/e/1FAIpQLSdDX79P5ByStVS_3n4tK1mAWidazIiF6DMEtDMK8KqmJywjqA/viewform?vc=0&c=0&w=1&flr=0&usp=mail_form_link>

    NOTE:  We will only collect: team members name, email address, organization, software used, interested in oncology, key interests and affiliations to stats organizations.  The email address is solely for the CAMIS leadership team, to make sure you are included in CAMIS emails.\
    We ask on the form: "Are you happy for your Name and company and interests to be visible on the CAMIS website. Note that email addresses will not be visible". 

    If you do not give permission then your name will not appear on the CAMIS repo as a CAMIS team member. If you do give permission, your name and company and interests will appear but your email addresses will be hidden from
    public view. At any time you can ask to be removed from the website team list by emailing me.

-   Phuse css workshop for 2024 / CAMIS ONCO-- Soma/Vikash/Harshil

    -   Filip, Lyn & Chrstina met re: Python content

    -   Next steps for workshop & white paper

-   Other conferences

    -   Keaven - attending JSM & ISBN - and will mention CAMIS.

    -   Chi attending use R conference, Lyn/Christina/All: please review abstract if you wish.

    -   Regulator stats workshop: Leon Shih (poster)

-   Volunteers requested for:

    -   Openstatsware Bayesian MMRM  {brms.mmrm} package input :  Christine/Orla

    -   MMRM - Volunteer please to look at Proc Mixed vs Proc GLIMMIX for the SAS/mmrm.qmd file (Stephen McCawille & Leon Shi may be able to look at this in future ).

-   AOB

    -   Christina: Create a 1 slide - This is CAMIS.

    -   Lyn: Load up Dec2023 blog post

    -   Chi: Add links to blogs & add blog tab when we have content
