---
title: "Blogs, New content, Conferences (2)"
date: "12 May 2025"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2025")
knitr::kable(
       list(attend_list[c(1,6)]), "html")
```

# Agenda & Minutes

Blogs:

-   Vikash blog on PHUSE US

-   Molly/Lyn : Meeting with PHUSE admin team tomorrow re: size & frequency of blogs

Conferences:

-   PSI 8th June. Stickers now printed & will be handed out including QR code to repo

-   R in medicine: 11th June. Only \$40 or so to attend so if anyone at your companies want to learn more it's a good one to attend.

-   PharmaSUG -- Brian attending Yannick also applying to attend

-   PHUSE EU. R/Pharma Nov 3-7th info TBC. call for abstracts not yet open.

-   R in HTA workshop - conference. Stephen attending in June.

-   Jaskaran is presenting in PHUSE CSS: Synthetic data.

-   PSI event in Cambridge England re: moving to R: 3rd July. Yannick attending & can mention CAMIS.

New content:

-   Binomial test in SAS -- noted comp page missing, so Jaskaran volunteered to do comparison page & Cochran mantel haenzel test in python.

-   Sample size Cochran Armitage test for trend in R and SAS/StatXact

-   Added to the Friedman Test

-   Sample size Equivalence R & SAS.

-   Working group on confidence intervals & new package development (GSK Pfizer & roche doing CI's for proportions). Cardx ones will move into citools (and come out of cardx as that should be manipulation only), and will add other methods such as CI stratified MN. DescTools is a wide ranging package so harder to validate for a GxP validated environment, so taking the CI's from this package into a separate citools package. One stop place for all CIs for proportions and will have some odds ratios too.

-   Poisson / negative binomial regression still needed - Lyn to do in July if poss
