---
title: "White Paper, Website, ONCO, Volunteers, Conferences"
date: "13mar2023"
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false
attend_list <- readr::read_csv("../CAMIS team members.csv")
knitr::kable(
       list(attend_list[c(1,5)]), "html")
```

# Agenda

-   White paper - Lyn
-   Website progress - Christina
-   CAMIS-ONCO - Soma Sekhar
-   Volunteers Roles
-   Conference Reps
-   AOB/ PHUSE feedback

# Meeting minutes

**White Paper Update: Lyn** Min-Hua is sending the white paper to the PHUSE group lead for review soon just a bit more tidying to do following comments.

**Website progress: Christina\
**The home page now has the list of stats methods we are looking to collect data on.

**ACTION :**Christina to put actions for each stats method which we need help to complete into github. We will assign those already selected to the people below. This will enable people that want to help to be able to see which are available for people to select.

**CAMIS- ONCO: Soma Sekhar**

-   plan to launch later this week.

-   possibly white paper/ conference presentation.

**Review of volunteer roles**

-   General Co-ordination -Lyn

-   Website Co-ordination / Home page table - Christina

-   CAMIS-ONCO - Soma Sekhar

-   Copying CSRMLW material to CAMIS

    -   CMH: Aiming Yang

    -   Linear Models: Brian Varney (ACTION: Set up call with Dani, Lyn, Vikash, christina, + anyone else whose interested in helping to please volunteer)

    -   MMRM: Ben Arancibia

    -   Survival: Min-Hua Jen, Mia Qi

ACTION: Christina to also add "actions" for people to pick up the following duties.

-   Co-ordinator for conference material - share standard slides/ content /abstracts

-   Volunteer to design a CAMIS Logo

-   Social media rep - to co-ordinate posts (linkedIn/Twitter)

-   Conference reps/ attendees needed

We will also add a page which lists the conferences so we can collate and coordinate whose going with the hope of advertising the project more widely once we have content on the website. Include a column for timelines/ abstract deadlines.

+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| Conference                                                                       | Location                         | Date               | Main Contact        | Volunteers to attend | Details                            |
+==================================================================================+==================================+====================+=====================+======================+====================================+
| PHUSE US Connect                                                                 | Orlando, Florida                 | 5-8 March 2023     | Soma Sekhar         |                      | Presentation                       |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| DISS (Duke industry statistics symposium)                                        | Virtual                          | 29-31st March 2023 | Lyn Taylor          | Molly MacDiarmid     | Poster                             |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| PSDM(Pharmaceutical statistics and data management)                              | Netherlands                      | 19 Apr 2023        |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| IASCT (ConSPIC - conference for statistics and programming in clinical research) | Bengaluru, India                 | 4-6 May 2023       | Harshal Khanolkar   | Harshal Khanolkar    |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| PSI 2023 Conference                                                              | Hammersmith London West, England | 11-14 June 2023    | Martin Brown        | Christina Fillmore   | Oral & poster submission completed |
|                                                                                  |                                  |                    |                     |                      |                                    |
|                                                                                  |                                  |                    |                     | Lyn Taylor           |                                    |
|                                                                                  |                                  |                    |                     |                      |                                    |
|                                                                                  |                                  |                    |                     | Molly Macdiarmid     |                                    |
|                                                                                  |                                  |                    |                     |                      |                                    |
|                                                                                  |                                  |                    |                     | Martin Brown         |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| DIA 2023 Global Annual Meeting                                                   | Boston MA, USA                   | 25-29 June 2023    |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| Joint statistical meeting (JSM)                                                  | Toronto, Ontario, Canada         | 5-10 Aug 2023      |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| ISCB Conference                                                                  | Milan-Italy                      | 27-31 Aug 2023     |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| RSS conference                                                                   | Harrogate, England               | 4-7 sept 2023      |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| ASA Bio pharmaceutical Section Regulatory-industry Statistics Workshop           | Rockville, Maryland, USA         | 27-29 Sept 2023    |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| EASD 2023 - European Association for study of diabetes                           | Hamberg Germany                  | 02-06 Oct 2023     |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| PHUSE EU Connect 2023                                                            | ICC Birmingham, England          | 5-8 November 2023  | Christina Fillmore? |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+
| R in Pharma /\                                                                   | Virtual/ In person               | Nov?               | Christina Fillmore? |                      |                                    |
| POSIT conf.                                                                      |                                  |                    |                     |                      |                                    |
+----------------------------------------------------------------------------------+----------------------------------+--------------------+---------------------+----------------------+------------------------------------+

------------------------------------------------------------------------
