---
title: "2024 Goals"
date: "13 May 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,6)]), "html")
```

# Agenda & Minutes

## 2024 Goals

-   Our open issues are [here](https://github.com/PSIAIMS/CAMIS/issues)\
    Currently 32 are closed and we would like to increase this to 45 closed by the end of the year
-   In addition, we'd like to improve some of the incomplete content such as MMRM
-   Create a webpage for listings dissertation projects
-   Have Soma & Vikash represent us at the CSS workshop.

## CAMIS - Onco

To date there has not been much progress. Given the enthusiasm in the meeting to get things kicked off and starting to increase our survival content on the repository, Christina will set up a kick off meeting for those interested. To look at: weighted logrank, MaxCombo, RMST

This SAS link may also be [useful](https://support.sas.com/documentation/onlinedoc/stat/151/kaplan.pdf)

## Other content updates

We now have a new table of assignments saved in the following [readme](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content) Welcome to edit to update anything you would like to work on, so we keep track of whose working on what. Special shout out to David who has now completed chi-square for SAS and to Lukas for all the python content. Awesome work !

As SAS Viya is becoming more used now, we agreed OK to add Viya specific code such as proc freqtab as long as it's clear that this isn't a SAS Base procedure.

## Conference planning

Reminder that if you are attending a conference to represent CAMIS to add the detail [here](https://psiaims.github.io/CAMIS/Conferences.html). We need to ensure we continue to advertise the project to encourage people to use the repo and add content.

-   PHUSE CSS update (Soma/Vikash)
-   R/Pharma -- anyone like to present (openstatsware -- collab, python): Waiting to be open.
-   USER! -- Chi (Accepted)
-   Stephen phuse EU.
-   EU Connect -- Agnieska TBC
-   R/Medicine 2024- Agnieska accepted for Thurs 13th/14th 11am-6pm EST (20 min talk)

## AOB

Our Blog page dosn't appear in date order or aligned! If anyone can fix let us know ! Saved under News [here](https://psiaims.github.io/CAMIS/blogs/)
