---
title: "Package selection"
date: "14 July 2025"
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false
attend_list <- readr::read_csv("../CAMIS team members 2025")
knitr::kable(
       list(attend_list[c(1,7)]), "html")
```

# Agenda & Minutes

**Conferences.**

-   Brian attending SAS users in the fall,

-   Yannick got a poster accepted for ISBC & has a PHUSE EU presentation. 

-   Lyn & christina attended PSI - lots of interest in CAMIS, many had heard of us, but lots of people still using SAS as their main programing language. Hence, we expect usage of our site to increase as more companies transition to R. Currently, we have a steady 10-30 unique people viewing the website each day.

-   All to update the Conferences.qmd with any confences you are attending.

**Next steps for CAMIS.**

-   Over next few months, leadership team to do a review of current content & identify where improvements are needed. Identify new issues - & assign.

-   We plan to follow up with people assigned issues, but that we haven't heard from for a while. Chase up missing content.

**How to select packages to use in the comparison.**

Christina presented slides from PSI Conferenece with respect to how to check packages for best use see [CAMIS](../non_website_content/conferences/2025/202506_PSI_Christina_Lyn.pptx)

Brian suggested another useful package to run is pkgdiff written by david bossock, this checks through packages for changes that may break prevoius code and gives a stability score. <https://github.com/lvc/pkgdiff>

Michael also suggested you can use <https://diffify.com/R> to look at the differences between packages.
