---
title: "Repo Content Growth, Conferences 2024"
date: "14 July 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,8)]), "html")
```

# Agenda & Minutes

**Monthly Contributions**

-   Not much content this month, but per the below, lots on the way !

**Content updates / assignments**

We checked the assignments readme (under non-website content)

-   Survival -- perhaps split into: non parametric, parametric (rather than AFT & non-proportional hazards), Update readme.md table to assign these rows to the survival team.\
    Team will meet again in 2 weeks.

-   Negative binomial content has been posted, it's a comparison, but would now be quick to write the SAS page. **ACTION:** Orla to ask the Novartis team to add that too.

-   Keaven/Yulia -- Group sequential designs: pull request internally east vs R -- not doing comparison yet, but will do in future.

QUESTIONS: Do we need to use SAS enterprise or SAS studio and should we state the version that gave the output? It's probably good practice to do this in case something change. For R, we should use renv, any problem ask Christina. The R/Python code runs each time so output will be current per version being used. Only sas is static.

**22nd July -- Novartis hackathon** 150 signed up. Need to provide Orla with ideas of what we want them to look at. Stats SMEs will also review before doing pull requests. Possible topics could be:

-   Negative binomial -- comparison & SAS code Beecer -- covariate adjustment for logistic regression

-   Logistic regression page update -- improve content & investigate why p value different.

-   MANOVA -- why R different to SAS

-   Friedman test, Jonckheere test, bionomial, R / sas /comp both needed

-   Correlation in SAS

-   Christina may need help to review pull request. Both Pfizer, Novartis & merck will have internal reviews prior to pull requests so review can be reduced.

**Conferences**

-   Chi's UseR slides are now on the repository [under](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content/conferences/2024)
-   PHUSE EU Brussels 23rd Sept - Qian Wang (Merck) will attend.
-   POSIT conf, R in pharma...R open now https://github.com/rinpharma/rinpharma-summit-2024?tab=readme-ov-file
-   Harshal working with Daniel Sabanes Bove on the organizing committee for R in pharma: Asia pacific track -- woudl be good to have a repo from Asia represent us
-   25th July: Americas single day event pennylvania anyone going?
-   JSM -- 1st week august -- Keaven Anderson going, lyn to send 1 slide.

QUESTIONS: RE: funding to attend conferences, usually provided by your company, but in special circumstances we could request funding from: R consortium or PHUSE.

**Brainstorming session**

How can we engage wider to increase content creation?

-   PSI : enews,

-   PHUSE bi-weekly news: Let Alexandra Peace (mailto:workinggroups\@phuse.global) know of any events we are attending or new content we worked on and she will share in a weekly summary of progress.

-   Could volunteer to host hackathons for conferences. Christina & orla volunteering to host a hackathon for R in pharma this week.

-   Advertise to PSI/PHUSE RE: if you have Findings please add an issue (even if you can't look into it yourself).

-   Special media post to Thank you Merck, Pfizer, Novartis for your contributions. Also companies can post what they've contributed. New content blogs. -

-   Blog of Novartis hackathon.

**Dissertations** --still looking for new ideas for projects & widen engagement with universities.
