---
title: "White Paper, Website, Launch Plan"
date: "15 May 2023"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members.csv")
knitr::kable(
       list(attend_list[c(1,7)]), "html")
```

# Agenda

-   White paper - Lyn/Min-Hua
-   Website progress - Christina
-   Update on Launch - Lyn
-   CAMIS-ONCO - Soma Sekhar
-   Volunteer Open Roles
-   Conference Attendance 
-   AOB

# Meeting minutes

**White Paper Update: Min-Hua**
Paula at PHUSE will distribute for public review.  Over the next days we'll get a link to the official review.
ACTION :Christina will put the white paper onto the website as draft open for public review

**Website progress: Christina**
Website content progressing well.
Ben Arancibia - progressing MMRMs + other areas.  
Survival - With Christina to fix importing.
ANCOVA - Aditee in progress - change to CSV not SAV (SPSS file). Update to call it linear regression, Lyn to help find ANCOVA (testing treatments)
Independant Two-Sample t-test in SAS - Vikash got a few changes then will load ok.

Lyn: To create a FAQ doc for the website.  Make sure it references available material elsewhere so it doesn't become out of date quickly.

NOTE: When you do a pull request, check your action to see if the checks pass/fail & reach out to Lyn/CHristina if you have problems.
Remember to do snapshot::renv, so that any packages you install were snapshot to the central repo. Else it will fail when you do the pull request as the repo wont have the packages in it that your code needs.



**Launch Update**

-   Blog video now available [here](https://github.com/PSIAIMS/CAMIS/blob/main/non_website_content/20230505%20Blog%20Recording.mp4)

- Blog text to use with various lengths also available [here](https://github.com/PSIAIMS/CAMIS/blob/main/non_website_content/20230505%20Blog%20Text%20Introduction%20to%20CAMIS.docx)

- Conference slides & abstract available [here](https://github.com/PSIAIMS/CAMIS/tree/main/non_website_content/conferences)

Rather than a standard set, plan is to have abstracts & slides/posters put into this folder (inc. name & date of conference) then people can use the contact that they have preference to use.  

Harshal has loaded IASCT slides to same location.

 

-   Contacts for Societies

    -   PSI /EFSPI (Martin) - Content sent.

    -   R Consortium / PHUSE / RSS (Lyn) - Content sent.

    -   IASCT (Harshal) - Conference went well and lots of interest from IASCT.

    -   ASA (Leon) - TBC who are ASA to reach out to?  If Ben has any contacts that Leon could use please let him know.
    
    -   SAS - we may reach out to SAS directly through PHUSE. TBC if they would be Ok with us including their data, copyright.  Hopefully they'd give approval as not or project & advertising what you can do in SAS.  ACTION: to find contact who may be interested in update/review of SAS.
    Does PHUSE have a contact already that we can use. Lyn to ask Paula.  Aiming/ Martin to let Lyn know if she has a contact.
    ACTION : Lyn/Christina to Add a disclaimer that we are volunteers adding open source content, but if you see anything that infringes copyright please let us know and we'll remove it immediately.

    
**CAMIS- ONCO: Soma Sekhar**

* Validation of endpoints (primary/secondary oncology endpoints). Propose to do poster at PHUSE CSS.
Once Mia's survival section is loaded.  Sema Sekhar to review.  Then highlight what's missing - what else you want to add.
Max combo.
BICR vs RECIST?
In future we can discuss how these fit with current CAMIS structure.  Focus on the Stats method ideally.
ACTION :Christina to email Semar Sekhar once Survival is live on Website.

**Conferences** Let's review

Vikesh- plan for CSS. Abstract deadline 12th June, 30th june registration opens.  
Posters only - only invited people can be speakers.
Somar Sekhar,  Aditee Dani would be happy to do posters. Suggest all 3 meet to discuss contribution to poster or doing separate ones but not duplicating the same content.

Ask PHUSE CSS working group (Data visualization and open source technology) DVOST - if we can have a presentation next year at the CSS.

JSM -  ASA conference.  Leon attending.  Abstract due Feb 2024 - so try have a rep there next year.

PHUSE Single day event (SDE- Toronto Mississauga),  PHUSE EU got a poster abstract: Jayashree Vendanayagam
PHUSE Single day event (New york - regeneron hosting Oct 16, check check if Aiming can do any poster/presentation/advert)

AZ R pharm conference 7th June.  LYn & Martin presenting.

