---
title: "White Paper Finalization, Advertising CAMIS"
date: "19 June 2023"
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false
attend_list <- readr::read_csv("../CAMIS team members.csv")
knitr::kable(
       list(attend_list[c(1,8)]), "html")
```

# Agenda

-   Team announcements - Lyn
-   White paper - Lyn
-   Website progress - Christina
-   Conferences feedback (PSI/IASCT)- Lyn/Christina/Martin/Molly/Aiming/Harshal
-   Conference planning - All
-   CAMIS-ONCO - Soma Sekhar
-   AOB

# Meeting minutes

**Team Announcements**

Min-Hua Jen, Gave birth to twins -everyone is doing well !

Welcome to: Iris Wu (Incyte)

Harshal volunteered to be our Social Media Rep / co-ordinate our social media posts.

Role consists of:

1)  Helps to come up for ideas for blogs/posts. Examples could include, if someone writes content on MRMM, you ask them to write a short description on what they've done including link to their work on the website, or for example, once the white paper is final, one of us will write a blog post to advertise it. Molly's poster prize at PSI conference etc !

2)  Chases people up who said they'd write a blog to ensure we are marketing our work in a timely manner.

3)  Ensures that when you receive content (blog/posts), that it's sent to all the key contacts for organizations/Societies (See end of minutes for list)

**Social media post list of upcoming posts**

1\) Write a short message for Molly winning Poster prize. Just something in third person like "Congrats to Molly for winning a PSI Conference 2023 Poster Prize. If you want to see the poster it's here..<LINK> (Molly to write, Lyn review, then send to Harshil/Christine to review - then Harshil to forward to contacts for advertising).

2\) Once White paper released, PHUSE will advertize but we should write something to share with our wider contacts

**White Paper Update** No comments from Public review. Paper is [here](https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Under+Review/White_Paper_V6_11May23+(1).pdf) We checked for any last comments from the group. ACTION: Lyn to send confirmation that we are good to proceed to PHUSE tomorrow if no further comments.

**Website progress: Christina**

Substantial content been added in the last month.

Once key area we'd like to progress on though is MMRM. ACTION: Christina to ask Kevin Kunzmann if he can write up something.

Lyn - To create a FAQ doc for the website. Make sure it references available material elsewhere so it doesn't become out of date quickly.

PSI AIMS will create github training which we can utilize to onboard statisticians.

**Conference feedback:**

PSI Conference: Lyn/Christina/Martin/Molly/Aiming. Molly's conference poster won a Poster Prize ! Need to blog/advertise the award.

IASCT: Harshil. Spoken to board members, currently board going through election so will restart discussion after that.

**Conference planning**

Vikash- plan for CSS. Abstract has been submitted by Soma Sekhar (Co-author Vikash & Adittee), 30th june registration opens.

ACTION: Lyn: Ask PHUSE CSS working group (Data visualization and open source technology) DVOST - if we can have a presentation next year at the CSS.

JSM - ASA conference. Leon. Abstract due Feb 2024 - so try have a rep there next year.

PHUSE Single day event (SDE- Toronto Mississauga),

SCT - society of clinical trials - Michael kane? (ACTION : Lyn to update conf website)

SESUG - South Eastern SAS user group: Brian Varney (ACTION : Lyn to update conf website)

PHUSE EU got a poster abstract: Jayashree Vendanayagam

PHUSE Single day event (New york - regeneron hosting Oct 16, Aiming emailed host to see if she can do a poster/presentation/advert - Lyn to add to conf page)

R in Pharma - Brian or Christina to possibly submit something. Nov virtual. POSIT CONF - September in chicago. (Lyn update website - Christina wont be at POSIT, split into 2 )

Phuse EU connect : the CAMIS abstract was selected as back up talk only. However there are some companies who have company talks - which take priority so limited independent speakers to accept talks from. TBC if anyone on the list of speakers - could include a slide to advertise us at PHUSE EU!

Lessons learnt for conferences:

1\) Put PHUSE CAMIS on abstract (part of PHUSE DVOST).

2\) submit abstract for Poster & Talk - then you have the back up of a poster if talk is rejected.

**CAMIS- ONCO: Soma Sekhar**

-   No update this month, carry to next month. Validation of endpoints (primary/secondary oncology endpoints). Propose to do poster at PHUSE CSS. Once Mia's survival section is loaded. Sema Sekhar to review. Then highlight what's missing - what else you want to add. Max combo. BICR vs RECIST? In future we can discuss how these fit with current CAMIS structure. Focus on the Stats method ideally. ACTION :Christina to email Semar Sekhar once Survival is live on Website.

**Previous meeting notes/ Key Information**

-   Contacts for Organizations/ Societies

    -   PSI /EFSPI (Martin)

    -   R Consortium / PHUSE / RSS (Lyn)

    -   IASCT (Harshal)

    -   ASA (Leon) - TBC who are ASA to reach out to? If Ben has any contacts that Leon could use please let him know.

    -   SAS - Contact TBC.

-   Roles

    -   Lyn Taylor - Lead

    -   Christina Fillmore - Website/ co-lead

    -   Soma Sekhar Sriadibhatla- CAMIS ONCO

    -   Harshal Khanolkar - Social media rep

    -   Linear models team - Brian Varney, Vikash Jain,

    -   MMRM - Ben Arancibia / Kevin Kunzmann
