---
title: "General linear models is complete"
date: "8 Apr 2024"
output:
  html_document: 
     toc: true
     toc_float: false
     toc_level: 5
     df_print: paged
---

# Attendees

```{r attendees, echo=FALSE, message=FALSE,  warning=FALSE, }
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,5)]), "html")
```

# Agenda & Minutes

## This months achievements

General Linear Models is Complete !

Thanks David & others for great contributions this month.

We are seeing more python examples coming through too.

## Checklist for pull requests

Christina will add something to help ensure a smooth process

## CSS Connect progress update -- Soma/ Vikash

Vikash to reach out to Soma. Harshil unlikely to be available in person, so we can look for further support to attend & help you if needed.

## Any other Conferences that people have applied for?

-   Lukus & Stephen are attending PHUSE EU Connect with other topics, but if others going CAMIS members could meet up in person, TBC nearer the date

## Current assignments

Lyn to put together Table so we can easily see whose doing what.

-   Sarah Rathwell & Christina volunteered to work on Kolmogorov-Smirnov test

-   Lukas Brausch to pick up Python one sample t-test, paired & 2 sample t-test

-   Chi to reach out to open stats ware to see if they can improve MMRM & add any bayesian MMRM

-   Leon to look at Reference-based MI (using either SAS macro, or procedures directly).

-   Keaven/Martin to look at group sequential design

-   CAMIS-ONCO no kick off yet, so Stephen McCawille will start to look at SAS Accelerated failure time models, Volunteer needed to run the same in R.

-   Todd/Cuifeng will be looking at Non linear models

-   ALL - if you are looking for an assignment reach out to Christina & Lyn and we can group you together to collaborate.
