---
title: "CAMIS End of Year Thank you"
date: "09 December 2024"
output:
  html_document: 
    toc: true
    toc_float: false
    toc_level: 5
    df_print: paged
---

# Attendees

```{r}
#| label: attendees
#| echo: false
#| message: false
#| warning: false
attend_list <- readr::read_csv("../CAMIS team members 2024.csv")
knitr::kable(
       list(attend_list[c(1,12)]), "html")
```

# Agenda & Minutes

-   2024 resulted in 160 pull requests and 64 pages of new content

-   CAMIS 2024 Awards

    -   Longest Serving Active members (from CSRMLW to CAMIS!): **Brian Varney, Min-Hua & Mia Qi**

    -   Most Pull Requests Reviewed: **Orla Doyle**

    -   Most Contributions (especially for python content): **Seemani Abhilipsa & Lukas Brausch**

    -   Section Closer (for general linear model section): D**avid Bosak**

    -   Expanding Project Remit: **Yuli Sidi & Nan Xiao** (EAST), and **Michael Walshe** (Survey stats)

    -   Best Written (SAS and R cumulative incidence functions): **Lillian Yau**

    -   Most Shocking Finding (epibasix package undocumented CI method): **Molly Mcdiarmid**

    -   Rookie of the Year (From first PR to completing Wilcoxon signed rank section, presenting at PHUSE EU & winning Best Presentation award in the Analytics and Statistics Stream: **Agnieszka Tomczyk**

**2025 Objectives**

Working group re: Improving Technical back end (CICD, tech team)\
Volunteers needed - So far Christina & Michael Walshe

To explore: - Posit workbench to improve rendering

-   When PRs come in, be able to render view before pulling in
-   Strategy for how to make Comparison pages more stable with respect to R version changes
-   Possibility to include checks which run the code & check for change

Expand our influence (particular through representation in USA)

Key Content

-   MMRM -- Stephen Waugh

-   Sample size - Agnieszka & Andisheh & Molly

-   Tobit regression - Yannick

-   CIs for Props & Logistic regression & RTSM- Lyn

Review conference attendance at January 2025 meeting.

All to let us know any feedback or suggestions for 2025.
